apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-a4cc82d3-b2c8-46a7-84b0-13f01787d45b
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-rbd
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: necesse
    namespace: necesse
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000014-7843a47a-7efe-4d81-a574-e6556a4ea42a
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      pool: default-ssd
      journalPool: default-ssd
      imageName: csi-vol-7843a47a-7efe-4d81-a574-e6556a4ea42a
      imageFeatures: layering
      imageFormat: "2"
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
