---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slackerworld
  namespace: slackerworld
spec:
  encryptedData:
    adminPassword: AgCGM8u5LkVu8GTKI/arvk5WIm0RXRDI+9Tk9Bx6SYZ4g6gPJ98ptEFwhSItMjJf+cINFwo6YcoNhP/9fxKi751kCZkggY1VFW7Z+LG4j0qsm1K1EaDCy0N/yly1IxEytEuaXLQLbjYryK2TT+hU5f2deN61GyQAjKmnozCWGYurKo4lQlXohRxpz38aNbTicexe6GQstbZu6fDyKIHD71P5VFxu1F1sUNa+ckM5duPeAFemzDUu4yjxgSU705DbhVC0OhhPGDMfJVtAvkY/W6eruL7TQjE03Ynn/HXk7vFbyKTe+2DjIAU+If0U2UTG5zYrIF+uV6c4v8n9j0y7H19fnzfMb1TM013td5MZJyeW97Mc2Kx3PDHiYzEoDccN2Mzq2fQPnpOxO+VpGLzOqIKFvDaY1Ix+t6AQI5LTbmyRClj5ni2W+0+pVMDuPbw04RJcUrhDHlSeRSbmH5OBx1oeWAc+3NLjyM1j0mOvG4WtAa/rCwaaQUV/C8Ne6Maz5/6WHmmTUBpiSUBgBG2JyYsvCz753onch/+45k/eeCTHhwHyF5XgY5f+Gyr0un7j+m5iHGiPU8N7z3zpAo9lFuSGPxL003FSiMjG3pBAYyDryfhHZntJlVQP7LXqLFfIg6uqRtBY31uEe2MJ/CQyDNWneZsX6Gw0m3AIQw1UgBWDPV8FXIp7TAqdfK56iqf1NNKWm+7yJlsvzVuQ6dHzbczImyaS
  template:
    metadata:
      name: slackerworld
      namespace: slackerworld
    type: Opaque
