// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Metal.V1Alpha1
{

    /// <summary>
    /// ServerStatus defines the observed state of Server.
    /// </summary>
    [OutputType]
    public sealed class ServerStatus
    {
        /// <summary>
        /// Addresses lists discovered node IPs.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Metal.V1Alpha1.ServerStatusAddresses> Addresses;
        /// <summary>
        /// Conditions defines current service state of the Server.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Metal.V1Alpha1.ServerStatusConditions> Conditions;
        /// <summary>
        /// InUse is true when server is assigned to some MetalMachine.
        /// </summary>
        public readonly bool InUse;
        /// <summary>
        /// IsClean is true when server disks are wiped.
        /// </summary>
        public readonly bool IsClean;
        /// <summary>
        /// Power is the current power state of the server: "on", "off" or "unknown".
        /// </summary>
        public readonly string Power;
        /// <summary>
        /// Ready is true when server is accepted and in use.
        /// </summary>
        public readonly bool Ready;

        [OutputConstructor]
        private ServerStatus(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Metal.V1Alpha1.ServerStatusAddresses> addresses,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Metal.V1Alpha1.ServerStatusConditions> conditions,

            bool inUse,

            bool isClean,

            string power,

            bool ready)
        {
            Addresses = addresses;
            Conditions = conditions;
            InUse = inUse;
            IsClean = isClean;
            Power = power;
            Ready = ready;
        }
    }
}
