name: thecluster-archive
description: Hoarding resources for THECLUSTER
runtime:
  name: nodejs
  options:
    packagemanager: yarn
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
