apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare-operator
  namespace: flux-system
spec:
  url: https://unstoppablemango.github.io/cloudflare-operator
  interval: 1m
