apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  url: https://bitnami-labs.github.io/sealed-secrets
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m
  releaseName: sealed-secrets
  targetNamespace: flux-system
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.6
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets
  values:
    fullnameOverride: sealed-secrets-controller
    image:
      registry: docker.io # default
      repository: bitnami/sealed-secrets-controller # default
      tag: 0.32.2
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 512Mi
    ingress:
      enabled: true
      pathType: Prefix
      path: /
      ingressClassName: nginx
      hostname: sealed-secrets.thecluster.lan
