apiVersion: v2
name: deemix
description: Helm chart for installing Deemix
type: application
version: 0.1.0
appVersion: '2022.12.14-r222.5d447b6035'
sources:
- https://gitlab.com/Bockiii/deemix-docker
- https://github.com/UnstoppableMango/the-cluster/tree/main/charts/deemix
kubeVersion: '>= 1.25'
maintainers:
- name: UnstoppableMango
  url: https://github.com/UnstoppableMango
dependencies:
- name: oauth2-proxy
  repository: https://oauth2-proxy.github.io/manifests
  version: 6.24.1
  condition: oauth2-proxy.enabled
