apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    cluster.x-k8s.io/aggregate-to-manager: "true"
    cluster.x-k8s.io/provider: infrastructure-proxmox
    clusterctl.cluster.x-k8s.io: ""
  name: cappx-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cappx-manager-role
subjects:
- kind: ServiceAccount
  name: cappx-controller-manager
  namespace: cappx-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
    app.kubernetes.io/instance: proxy-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    cluster.x-k8s.io/aggregate-to-manager: "true"
    cluster.x-k8s.io/provider: infrastructure-proxmox
    clusterctl.cluster.x-k8s.io: ""
  name: cappx-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cappx-proxy-role
subjects:
- kind: ServiceAccount
  name: cappx-controller-manager
  namespace: cappx-system
