apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-proxmox
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: cluster-api-provider-proxmox
    cluster.x-k8s.io/aggregate-to-manager: "true"
    cluster.x-k8s.io/provider: infrastructure-proxmox
    clusterctl.cluster.x-k8s.io: ""
  name: cappx-leader-election-rolebinding
  namespace: cappx-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cappx-leader-election-role
subjects:
- kind: ServiceAccount
  name: cappx-controller-manager
  namespace: cappx-system
