apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unstoppablemango-renovate
  namespace: renovate
spec:
  interval: 1h
  releaseName: unstoppablemango-renovate
  targetNamespace: renovate
  chart:
    spec:
      chart: renovate
      version: 46.120.0
      sourceRef:
        kind: HelmRepository
        name: renovate
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/renovatebot/helm-charts/blob/main/charts/renovate/values.yaml
  values:
    image:
      registry: ghcr.io # default
      repository: renovatebot/renovate # default
      tag: 43.132.1
    renovate:
      configIsJavaScript: true
      config: |
        const fs = require('fs');

        const token = fs.readFileSync('/shared/token', 'utf8').trim();

        module.exports = {
          token,
          platform: 'github',
          autodiscover: false, // default
          autodiscoverFilter: [], // default
          repositories: [
            'UnstoppableMango/a2b',
            'UnstoppableMango/audio',
            'UnstoppableMango/CliWrap.FSharp',
            'UnstoppableMango/dotfiles',
            'UnstoppableMango/fenced',
            'UnstoppableMango/github',
            'UnstoppableMango/ihfs',
            'UnstoppableMango/lang',
            'UnstoppableMango/openapi2go',
            'UnstoppableMango/openapi2terraform',
            'UnstoppableMango/ouranosis',
            'UnstoppableMango/minecraft-manager',
            'UnstoppableMango/nixos',
            'UnstoppableMango/pia-manual-connections',
            'UnstoppableMango/pulumi2crd',
            'UnstoppableMango/pulumi-bun',
            'UnstoppableMango/renovate-config',
            'UnstoppableMango/resume',
            'UnstoppableMango/thecluster.io',
            'UnstoppableMango/the-cluster',
            'UnstoppableMango/unstoppablemango.io',
            'UnstoppableMango/ux',
            'UnstoppableMango/wireguard-cni',
            'UnstoppableMango/xmage-docker',
            'UnstoppableMango/x12',
          ],
          presetCachePersistence: true,
        };
    cronjob:
      schedule: '*/30 * * * *'
      timeZone: 'America/Chicago'
      initContainers:
        - name: github-app-auth
          image: oven/bun:1.3.12
          env:
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: thecluster-app
                  key: app-id
            - name: GITHUB_INSTALLATION_ID
              valueFrom:
                configMapKeyRef:
                  name: installation-ids
                  key: unstoppablemango
          command:
            - /bin/sh
            - -c
            - |
              bunx github-app-installation-token \
              --appId "${GITHUB_APP_ID}" \
              --installationId "${GITHUB_INSTALLATION_ID}" \
              --privateKeyLocation /auth/key.pem \
              > /shared/token
          volumeMounts:
            - name: private-key
              mountPath: /auth/key.pem
              subPath: key.pem
            - name: shared
              mountPath: /shared
    env:
      LOG_LEVEL: debug
      RENOVATE_REDIS_URL: redis://redis.renovate.svc.cluster.local:6379/0
    extraVolumeMounts:
      - name: shared
        mountPath: /shared
    extraVolumes:
      - name: private-key
        secret:
          secretName: thecluster-app
      - name: shared
        emptyDir: {}
    resources:
      requests:
        cpu: '1'
        memory: 256Mi
      limits:
        cpu: '2'
        memory: 4Gi
