apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: haproxy-ingress
spec:
  interval: 10m
  releaseName: haproxy-ingress
  targetNamespace: haproxy-ingress
  chart:
    spec:
      chart: haproxy-ingress
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  # https://github.com/haproxy-ingress/charts/blob/master/haproxy-ingress/values.yaml
  values:
    controller:
      ingressClassResource:
        name: haproxy
        enabled: true
        controllerValue: haproxy-ingress.github.io/controller
      replicaCount: 2
      publishService:
        enabled: true
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.43
        externalTrafficPolicy: Local
