// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Infrastructure.V1Beta1
{

    /// <summary>
    /// K8sInstallerConfigStatus defines the observed state of K8sInstallerConfig
    /// </summary>
    public class K8sInstallerConfigStatusArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// InstallationSecret is an optional reference to a generated installation secret by K8sInstallerConfig controller
        /// </summary>
        [Input("installationSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Infrastructure.V1Beta1.K8sInstallerConfigStatusInstallationSecretArgs>? InstallationSecret { get; set; }

        /// <summary>
        /// Ready indicates the InstallationSecret field is ready to be consumed
        /// </summary>
        [Input("ready")]
        public Input<bool>? Ready { get; set; }

        public K8sInstallerConfigStatusArgs()
        {
        }
        public static new K8sInstallerConfigStatusArgs Empty => new K8sInstallerConfigStatusArgs();
    }
}
