// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Infrastructure.V1Beta1
{

    /// <summary>
    /// to do : should accept multiple IPConfig
    /// </summary>
    public class ProxmoxMachineTemplateSpecTemplateSpecNetworkIpConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// gateway IPv4
        /// </summary>
        [Input("gateway")]
        public Input<string>? Gateway { get; set; }

        /// <summary>
        /// gateway IPv6
        /// </summary>
        [Input("gateway6")]
        public Input<string>? Gateway6 { get; set; }

        /// <summary>
        /// IPv4 with CIDR
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        /// <summary>
        /// IPv6 with CIDR
        /// </summary>
        [Input("ip6")]
        public Input<string>? Ip6 { get; set; }

        public ProxmoxMachineTemplateSpecTemplateSpecNetworkIpConfigArgs()
        {
        }
        public static new ProxmoxMachineTemplateSpecTemplateSpecNetworkIpConfigArgs Empty => new ProxmoxMachineTemplateSpecTemplateSpecNetworkIpConfigArgs();
    }
}
