// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Cluster.V1Alpha4
{

    /// <summary>
    /// ClusterSpec defines the desired state of Cluster.
    /// </summary>
    public class ClusterSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cluster network configuration.
        /// </summary>
        [Input("clusterNetwork")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Alpha4.ClusterSpecClusterNetworkArgs>? ClusterNetwork { get; set; }

        /// <summary>
        /// ControlPlaneEndpoint represents the endpoint used to communicate with the control plane.
        /// </summary>
        [Input("controlPlaneEndpoint")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Alpha4.ClusterSpecControlPlaneEndpointArgs>? ControlPlaneEndpoint { get; set; }

        /// <summary>
        /// ControlPlaneRef is an optional reference to a provider-specific resource that holds the details for provisioning the Control Plane for a Cluster.
        /// </summary>
        [Input("controlPlaneRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Alpha4.ClusterSpecControlPlaneRefArgs>? ControlPlaneRef { get; set; }

        /// <summary>
        /// InfrastructureRef is a reference to a provider-specific resource that holds the details for provisioning infrastructure for a cluster in said provider.
        /// </summary>
        [Input("infrastructureRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Alpha4.ClusterSpecInfrastructureRefArgs>? InfrastructureRef { get; set; }

        /// <summary>
        /// Paused can be used to prevent controllers from processing the Cluster and all its associated objects.
        /// </summary>
        [Input("paused")]
        public Input<bool>? Paused { get; set; }

        /// <summary>
        /// This encapsulates the topology for the cluster. NOTE: It is required to enable the ClusterTopology feature gate flag to activate managed topologies support; this feature is highly experimental, and parts of it might still be not implemented.
        /// </summary>
        [Input("topology")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Alpha4.ClusterSpecTopologyArgs>? Topology { get; set; }

        public ClusterSpecArgs()
        {
        }
        public static new ClusterSpecArgs Empty => new ClusterSpecArgs();
    }
}
