// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Externaldns.V1
{

    /// <summary>
    /// Endpoint describes DNS Endpoint.
    /// </summary>
    public class DNSEndpointSpecEndpointsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The hostname for the DNS record
        /// </summary>
        [Input("dnsName")]
        public Input<string>? DnsName { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;

        /// <summary>
        /// Labels stores labels defined for the Endpoint
        /// </summary>
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("providerSpecific")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Externaldns.V1.DNSEndpointSpecEndpointsProviderSpecificArgs>? _providerSpecific;

        /// <summary>
        /// ProviderSpecific stores provider specific config
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Externaldns.V1.DNSEndpointSpecEndpointsProviderSpecificArgs> ProviderSpecific
        {
            get => _providerSpecific ?? (_providerSpecific = new InputList<Pulumi.Kubernetes.Types.Inputs.Externaldns.V1.DNSEndpointSpecEndpointsProviderSpecificArgs>());
            set => _providerSpecific = value;
        }

        /// <summary>
        /// TTL for the record
        /// </summary>
        [Input("recordTTL")]
        public Input<int>? RecordTTL { get; set; }

        /// <summary>
        /// RecordType type of record, e.g. CNAME, A, SRV, TXT, MX
        /// </summary>
        [Input("recordType")]
        public Input<string>? RecordType { get; set; }

        [Input("targets")]
        private InputList<string>? _targets;

        /// <summary>
        /// The targets the DNS service points to
        /// </summary>
        public InputList<string> Targets
        {
            get => _targets ?? (_targets = new InputList<string>());
            set => _targets = value;
        }

        public DNSEndpointSpecEndpointsArgs()
        {
        }
        public static new DNSEndpointSpecEndpointsArgs Empty => new DNSEndpointSpecEndpointsArgs();
    }
}
