version: 2
updates:
- package-ecosystem: npm
  directory: ''
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: '/lib/shared'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: '/stacks/networking'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: '/stacks/rancher'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
