version: 2
updates:
- package-ecosystem: npm
  directory: ''
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: 'external'
  schedule:
    interval: daily
  open-pull-requests-limit: 10
