---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor
  namespace: harbor-system
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgA/cxwwe/qHKDmnoGipTt9ktPXRiORU1JM2VHEP3R0exiY1ltISuVRbsMOnS6OdGRGvi+I8yq44STQyuiSaGnXhHLy6vvKWZjAfaxLU9zLQ9kgOZmzSn4h4H/cAg5q3cnlgFNKQUNXc0GYvYg715XvhpBDoeNVtcJl5MN+galDLwV+I9g7LOPY95EGcbOnIsGXnaHwXIr0X9vwaNROUx/J/XVlgPwDf5HUXfaFl5nU0aij/u0ibK/xPKybR6xlNj+4gZM0nELIqP6t9R2RPdmfviP4KOQZCf35zz5QDmKOsk1W13osEgsk34wsaS3rNCEP2xfZvwob8ybOHYB7NTjJ1YoOTYtkuL0f4F0oaJLAMsCInAGJaEcPnSfx2ZRlGneHyaenN7fojWUu73mG6Ly8CFZTCIkqvIWXLh24lbKAW2XO86tAg2c0d8+ItUvQstxlsyvsFcQ87z2BvX2UVxoAFauxb5I9FOSlhPK61a3C4JnG/2uW/JmB3tTPg96JuuJ6yTSeHmKmILYXTHwdhOFMHXkqzGgUPfMrpIKXCwYW82Fu4O6LrDICJkV3mpeC6vTwCZY/UG8WNF3qCk0XCwhyhsPhc9K4XcMvYR2KEkRnIjCiruXqgAQGHrHGAGpIcr+jGk24hIFUPUWLynY6U5hMCeeeUaoNshAWt1/QHvKY1/DXCkWIs8rn+LiYr5ZHzpncU2dY6w/UZDEjus/8VecQTqLEE3mLt0Vpj59C6PUFheQ==
    secretKey: AgBxeT8na0vK64wL5wirQkTJHF9zjVeV7BcKRsD830pYCBLUz/g4wiFsBsMe5skABca+XMt/Yjt8pZabDSDLig+qkGl/3jt6kIXSDrrVsbUNXmaNjPMDADT9xZ6MBGh9aGkb7pf9CU2qJjXftY4TLukstgaQjMvy0xc63/NRT+DjILjWCdgub3wxl3toCtyxJ8qcKNXsMhTFpCzK4fLyf0FaT900+jSbIuyl8Gx3GpDMWHxvxmU0bnG3nXBWOiaNtShNGyh2cOfc4KnA37j7TbojnGKdnDbcO6BsuHVmaGLl3mtIosfwji4ZF7JNbx7bvlZBSoYoeT7AKWHm/QuBWaH4ysIhS7LvDqPrZFQPFg+vN8tZyvFVlaAN0Y4Lo/cRJslfGnbeZEzpVunLBpG3Q92v0Rtk3ZVniLZZ+YkYWBQJcZY1rLOx7YfrZ/gsn8Eb1utu5bJ9vLCKYlqiSzxzxTT5b9Hce96qiyDAFsTR5q1pXkm5VZK5hsPNQvzx0ZbqHHg1Pt2CbXQjlZO56Iy4mp65zoDmo1ov1BB/6W0zgFCVmkFmhmhuWCvlAbnGNmP6GmuSqqgSO7AA/1w299GlXsmTeJDb0VSXomB9gJK31+6E1RluegrD/dT5FSZAnG7e41p/nwQZUT+iKUoAdL6LBWna56ImMRF3eibBy1SNWEQgs66BXZzwCw9v3cARwU/up6Hp69yXvBWJqGmHo031qVVw
  template:
    metadata:
      name: harbor
      namespace: harbor-system
    type: Opaque
