apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lang-runners
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/UnstoppableMango/lang
    githubConfigSecret: thecluster-bot
    template:
      spec:
        containers:
          - name: runner # default
            image: ghcr.io/actions/actions-runner:2.328.0
            command: [/home/runner/run.sh] # default
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thecluster-runners
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/UnstoppableMango/the-cluster
    githubConfigSecret: thecluster-bot
    minRunners: 1
    template:
      spec:
        containers:
          - name: runner # default
            image: ghcr.io/actions/actions-runner:2.328.0
            command: [/home/runner/run.sh] # default
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ux-runners
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/UnstoppableMango/ux
    githubConfigSecret: thecluster-bot
    template:
      spec:
        initContainers:
          - name: dind
            image: docker:28.4.0-dind
            restartPolicy: Always # sidecar
            command: [ dockerd, --host=unix:///var/run/docker.sock ]
            securityContext:
              privileged: true
            volumeMounts:
              - name: dind-sock
                mountPath: /var/run
        containers:
          - name: runner # default
            image: ghcr.io/unstoppablemango/the-cluster/actions-runner:sha-0eb8334
            command: [ /home/runner/run.sh ] # default
            env:
              - name: DOCKER_HOST
                value: unix:///var/run/docker.sock
            volumeMounts:
              - name: dind-sock
                mountPath: /var/run
                readOnly: true
            resources:
              limits:
                cpu: '8'
                memory: 4Gi
              requests:
                cpu: '1'
                memory: 256Mi
        volumes:
          - name: dind-sock
            emptyDir:
              medium: Memory
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: xmage-docker-runners
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/UnstoppableMango/xmage-docker
    githubConfigSecret: thecluster-bot
    template:
      spec:
        containers:
          - name: runner # default
            image: ghcr.io/actions/actions-runner:2.328.0
            command: [/home/runner/run.sh] # default
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thecluster.io-runners
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/UnstoppableMango/thecluster.io
    githubConfigSecret: thecluster-bot
    template:
      spec:
        containers:
          - name: runner # default
            image: ghcr.io/actions/actions-runner:2.328.0
            command: [/home/runner/run.sh] # default
