apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lang-runners
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/UnstoppableMango/lang
    githubConfigSecret: thecluster-bot
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: [ReadWriteOnce]
        storageClassName: unsafe-rbd
        resources:
          requests:
            storage: 250Gi
    template:
      spec:
        # https://github.com/actions/actions-runner-controller/issues/2890
        initContainers:
          - name: kube-init
            image: ghcr.io/actions/actions-runner:2.238.0
            command: [sudo, chown, -R, 1001:123, /home/runner/_work]
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.328.0
            command: [/home/runner/run.sh]
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thecluster-runners
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/UnstoppableMango/the-cluster
    githubConfigSecret: thecluster-bot
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: [ReadWriteOnce]
        storageClassName: unsafe-rbd
        resources:
          requests:
            storage: 1Gi
    template:
      spec:
        # https://github.com/actions/actions-runner-controller/issues/2890
        initContainers:
          - name: kube-init
            image: ghcr.io/actions/actions-runner:2.238.0
            command: [sudo, chown, -R, 1001:123, /home/runner/_work]
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.328.0
            command: [/home/runner/run.sh]
