kind: pipeline
type: docker
name: default

# metadata:
#   namespace: drone
#   annotations:
#     thecluster.io/pipeline: test
# trigger:
#   event:
#     - push
#   branch:
#     - main
#     - drones

steps:
- name: echo
  image: pulumi/pulumi-nodejs
  commands:
  - echo "Hiya friendo"
