kind: pipeline
type: docker
name: test

# metadata:
#   namespace: drone
#   annotations:
#     thecluster.io/pipeline: test
trigger:
  event:
    - push
  branch:
    - main

steps:
- name: echo
  image: plugins/docker
  commands:
  - echo "Hiya friendo"
