apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unmango-runners
  namespace: unmango-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/unmango
    githubConfigSecret: thecluster-bot
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.329.0
            command: [/home/runner/run.sh]
