apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: caps-serving-cert
  namespace: sidero-system
spec:
  dnsNames:
  - caps-webhook-service.sidero-system.svc
  - caps-webhook-service.sidero-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: caps-selfsigned-issuer
  secretName: caps-webhook-service-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-serving-cert
  namespace: sidero-system
spec:
  dnsNames:
  - sidero-webhook-service.sidero-system.svc
  - sidero-webhook-service.sidero-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: sidero-selfsigned-issuer
  secretName: sidero-webhook-service-cert
