apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: caps-leader-election-rolebinding
  namespace: sidero-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: caps-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: sidero-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: sidero
    cluster.x-k8s.io/provider: infrastructure-sidero
    cluster.x-k8s.io/v1alpha3: v1alpha3
    cluster.x-k8s.io/v1alpha4: v1alpha3
    cluster.x-k8s.io/v1beta1: v1alpha3
    clusterctl.cluster.x-k8s.io: ""
  name: sidero-leader-election-rolebinding
  namespace: sidero-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sidero-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: sidero-system
