apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ncps
  namespace: nix-system
spec:
  selector:
    matchLabels:
      app: ncps
      tier: proxy
  endpoints:
    - port: http-web
      path: /metrics
