// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Gateway.V1Alpha2
{

    /// <summary>
    /// Spec defines the desired state of BackendTLSPolicy.
    /// </summary>
    public class BackendTLSPolicySpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// TargetRef identifies an API object to apply the policy to. Only Services have Extended support. Implementations MAY support additional objects, with Implementation Specific support. Note that this config applies to the entire referenced resource by default, but this default may change in the future to provide a more granular application of the policy. 
        ///  Support: Extended for Kubernetes Service 
        ///  Support: Implementation-specific for any other resource
        /// </summary>
        [Input("targetRef", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Gateway.V1Alpha2.BackendTLSPolicySpecTargetRefArgs> TargetRef { get; set; } = null!;

        /// <summary>
        /// TLS contains backend TLS policy configuration.
        /// </summary>
        [Input("tls", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Gateway.V1Alpha2.BackendTLSPolicySpecTlsArgs> Tls { get; set; } = null!;

        public BackendTLSPolicySpecArgs()
        {
        }
        public static new BackendTLSPolicySpecArgs Empty => new BackendTLSPolicySpecArgs();
    }
}
