// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Bootstrap.V1Alpha2
{

    /// <summary>
    /// TalosConfigSpec defines the desired state of TalosConfig
    /// </summary>
    public class TalosConfigSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("data")]
        public Input<string>? Data { get; set; }

        [Input("generateType", required: true)]
        public Input<string> GenerateType { get; set; } = null!;

        public TalosConfigSpecArgs()
        {
        }
        public static new TalosConfigSpecArgs Empty => new TalosConfigSpecArgs();
    }
}
