apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 10m
  releaseName: plex
  targetNamespace: media
  chart:
    spec:
      chart: plex-media-server
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: plex
  values:
    pms:
      configExistingClaim: plex-config
      resources:
        limits:
          cpu: "8"
          memory: 10Gi
        requests:
          cpu: 250m
          memory: 5Gi
    image:
      registry: index.docker.io
      repository: plexinc/pms-docker
      tag: 1.42.2.10156-f737b826c
    extraEnv:
      HOSTNAME: plex
      TZ: America/Chicago
      # What do the numbers mean
      PLEX_UPDATE_CHANNEL: "8"
      ALLOWED_NETWORKS: 192.168.1.1/24
    service:
      type: LoadBalancer
    dnsConfig:
      options:
        - name: ndots
          value: "0"
    ingress:
      enabled: true
      ingressClassName: nginx
      url: plex.thecluster.lan
    extraVolumeMounts:
      - name: movies
        mountPath: /mnt/movies
      - name: movies4k
        mountPath: /mnt/movies4k
      - name: tv
        mountPath: /mnt/tv
      - name: tv4k
        mountPath: /mnt/tv4k
      - name: anime
        mountPath: /mnt/anime
      - name: music
        mountPath: /mnt/music
    extraVolumes:
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: movies4k
        persistentVolumeClaim:
          claimName: movies4k
      - name: tv
        persistentVolumeClaim:
          claimName: tv
      - name: tv4k
        persistentVolumeClaim:
          claimName: tv4k
      - name: anime
        persistentVolumeClaim:
          claimName: anime
      - name: music
        persistentVolumeClaim:
          claimName: music
