apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: bulk-rwx
  accessModes:
    - ReadWriteMany
  volumeName: pvc-77c91c0c-50e5-4957-a3e6-4ce91846deba
  resources:
    requests:
      storage: 20Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies4k
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: bulk-rwx
  accessModes:
    - ReadWriteMany
  volumeName: pvc-639475fc-49aa-4368-8a97-b41f3dc818a3
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: bulk-rwx
  accessModes:
    - ReadWriteMany
  volumeName: pvc-7b37a458-cd1f-47b5-81be-229019fc1a9d
  resources:
    requests:
      storage: 20Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv4k
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: bulk-rwx
  accessModes:
    - ReadWriteMany
  volumeName: pvc-c83917ed-3605-4952-91ee-7136781b5d1a
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anime
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: default-cephfs
  accessModes:
    - ReadWriteMany
  volumeName: pvc-6a7587dc-d3b6-4ffe-a82b-df6ccffcb124
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music
  namespace: media
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  storageClassName: default-cephfs
  accessModes:
    - ReadWriteMany
  volumeName: pvc-1700e5ee-c43b-4dd8-be95-cfef2c281b5b
  resources:
    requests:
      storage: 5Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube
  namespace: media
spec:
  storageClassName: ec-cephfs
  accessModes:
    - ReadWriteMany
  volumeName: pvc-27168545-2568-4b99-9f1f-338fde4132da
  resources:
    requests:
      storage: 20Ti
