apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deluge-downloads-pvc.yml
  - deluge-ingress.yml
  - deluge-service.yml
  - deluge-statefulset.yml
  - private-internet-access-sealed.yml
  - qbittorrent-sealed.yml
  - qbittorrent-downloads-pvc.yml
  - qbittorrent-ingress.yml
  - qbittorrent-service.yml
  - qbittorrent-statefulset.yml
