apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: api-server
  namespace: default
subjects:
  - name: kubernetes
    spec:
      fqdn: k8s.thecluster.io
      protocol: https
      noTlsVerify: true
tunnelRef:
  kind: ClusterTunnel
  name: thecluster.io
