apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agones-system-helm-repository.yml
  - arc-system-oci-repository.yml
  - awx-system-git-repository.yml
  - cloudflare-operator-system-git-repository.yml
  - cloudflare-system-git-repository.yml
  - cloudflare-system-helm-repository.yml
  - cloudflare-system-oci-repository.yml
  - cnpg-system-helm-repository.yml
  - crossplane-system-helm-repository.yml
  - monitoring-system-helm-repository.yml
  - nats-system-helm-repository.yml
  - nginx-gateway-system-oci-repository.yml
  - olmv1-system-git-repository.yml
  - shulker-system-helm-repository.yml
