apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: deemix
  serviceName: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: deemix
    spec:
      containers:
        - name: deemix
          image: {{ include "image" . }}
          ports:
            - name: http
              containerPort: 6595
          env:
            - name: PUID
              value: {{ .Values.global.uid | quote }}
            - name: PGID
              value: {{ .Values.global.gid | quote }}
            {{- if .Values.singleUser }}
            - name: DEEMIX_SINGLE_USER
              value: {{ .Values.singleUser | quote }}
            {{- end }}
            {{- if .Values.disableOwnershipCheck }}
            - name: DISABLE_OWNERSHIP_CHECK
              value: {{ .Values.disableOwnershipCheck | quote }}
            {{- end }}
            - name: UMASK_SET
              value: {{ .Values.umask | quote }}
          {{- if .Values.ingress.enabled }}
            - name: DEEMIX_LOCATION_BASE
              value: {{ .Values.ingress.path | quote }}
          {{- end }}
        {{- if or .Values.persistence.downloads.enabled .Values.persistence.config.enabled (lt 0 (len .Values.extraVolumeMounts)) }}
          volumeMounts:
          {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: '/config'
          {{- end }}
          {{- if .Values.persistence.downloads.enabled }}
            - name: downloads
              mountPath: '/downloads'
          {{- end }}
          {{- if lt 0 (len .Values.extraVolumeMounts) }}
            {{ .Values.extraVolumeMounts | toYaml | nindent 12 }}
          {{- end }}
        {{- end }}
          readinessProbe:
            httpGet:
              port: http
              path: {{ .Values.ingress.path }}
            initialDelaySeconds: 0
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: http
              path: {{ .Values.ingress.path }}
            initialDelaySeconds: 0
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
        {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      securityContext:
        fsGroup: {{ .Values.global.gid }}
      {{- if lt 0 (len .Values.extraVolumes) }}
      volumes:
        {{- .Values.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
  {{- if  or .Values.persistence.downloads.enabled .Values.persistence.config.enabled }}
  volumeClaimTemplates:
  {{- if .Values.persistence.config.enabled }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: config
      spec:
        storageClassName: {{ .Values.persistence.config.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.config.size }}
  {{- end }}
  {{- if .Values.persistence.downloads.enabled }}
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: downloads
      spec:
        storageClassName: {{  .Values.persistence.downloads.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.persistence.downloads.size }}
  {{- end }}
  {{- end }}
