// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Pulumi.V1
{

    [OutputType]
    public sealed class ProgramProgram
    {
        /// <summary>
        /// configuration specifies the Pulumi config inputs to the deployment. Either type or default is required.
        /// </summary>
        public readonly ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.Pulumi.V1.ProgramProgramConfiguration> Configuration;
        /// <summary>
        /// outputs specifies the Pulumi stack outputs of the program and how they are computed from the resources.
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableDictionary<string, object>> Outputs;
        /// <summary>
        /// resources declares the Pulumi resources that will be deployed and managed by the program.
        /// </summary>
        public readonly ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.Pulumi.V1.ProgramProgramResources> Resources;
        /// <summary>
        /// variables specifies intermediate values of the program; the values of variables are expressions that can be re-used.
        /// </summary>
        public readonly ImmutableDictionary<string, ImmutableDictionary<string, object>> Variables;

        [OutputConstructor]
        private ProgramProgram(
            ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.Pulumi.V1.ProgramProgramConfiguration> configuration,

            ImmutableDictionary<string, ImmutableDictionary<string, object>> outputs,

            ImmutableDictionary<string, Pulumi.Kubernetes.Types.Outputs.Pulumi.V1.ProgramProgramResources> resources,

            ImmutableDictionary<string, ImmutableDictionary<string, object>> variables)
        {
            Configuration = configuration;
            Outputs = outputs;
            Resources = resources;
            Variables = variables;
        }
    }
}
