name: thecluster-postgres
description: Postgres resources for THECLUSTER
runtime:
  name: nodejs
  options:
    packagemanager: npm
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
