apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: cacppt-system/cacppt-serving-cert
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: cacppt-webhook-service
      namespace: cacppt-system
      path: /mutate-controlplane-cluster-x-k8s-io-v1alpha3-taloscontrolplane
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.taloscontrolplane.controlplane.cluster.x-k8s.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - taloscontrolplanes
  sideEffects: None
