apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: cacppt-system/cacppt-serving-cert
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: cacppt-webhook-service
      namespace: cacppt-system
      path: /validate-controlplane-cluster-x-k8s-io-v1alpha3-taloscontrolplane
  failurePolicy: Fail
  name: validate.taloscontrolplane.controlplane.cluster.x-k8s.io
  rules:
  - apiGroups:
    - controlplane.cluster.x-k8s.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - taloscontrolplanes
  sideEffects: None
