// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Minio.V2
{

    public class TenantSpecKesArgs : global::Pulumi.ResourceArgs
    {
        [Input("affinity")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesAffinityArgs>? Affinity { get; set; }

        [Input("annotations")]
        private InputMap<string>? _annotations;
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("clientCertSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesClientCertSecretArgs>? ClientCertSecret { get; set; }

        [Input("env")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesEnvArgs>? _env;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesEnvArgs> Env
        {
            get => _env ?? (_env = new InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesEnvArgs>());
            set => _env = value;
        }

        [Input("externalCertSecret")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesExternalCertSecretArgs>? ExternalCertSecret { get; set; }

        [Input("gcpCredentialSecretName")]
        public Input<string>? GcpCredentialSecretName { get; set; }

        [Input("gcpWorkloadIdentityPool")]
        public Input<string>? GcpWorkloadIdentityPool { get; set; }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("imagePullPolicy")]
        public Input<string>? ImagePullPolicy { get; set; }

        [Input("kesSecret", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesKesSecretArgs> KesSecret { get; set; } = null!;

        [Input("keyName")]
        public Input<string>? KeyName { get; set; }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("replicas")]
        public Input<int>? Replicas { get; set; }

        [Input("resources")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesResourcesArgs>? Resources { get; set; }

        [Input("securityContext")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesSecurityContextArgs>? SecurityContext { get; set; }

        [Input("serviceAccountName")]
        public Input<string>? ServiceAccountName { get; set; }

        [Input("tolerations")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesTolerationsArgs>? _tolerations;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesTolerationsArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesTolerationsArgs>());
            set => _tolerations = value;
        }

        [Input("topologySpreadConstraints")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesTopologySpreadConstraintsArgs>? _topologySpreadConstraints;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesTopologySpreadConstraintsArgs> TopologySpreadConstraints
        {
            get => _topologySpreadConstraints ?? (_topologySpreadConstraints = new InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecKesTopologySpreadConstraintsArgs>());
            set => _topologySpreadConstraints = value;
        }

        public TenantSpecKesArgs()
        {
        }
        public static new TenantSpecKesArgs Empty => new TenantSpecKesArgs();
    }
}
