// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Minio.V2
{

    public class TenantSpecSideCarsVolumesDownwardApiArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaultMode")]
        public Input<int>? DefaultMode { get; set; }

        [Input("items")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecSideCarsVolumesDownwardApiItemsArgs>? _items;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecSideCarsVolumesDownwardApiItemsArgs> Items
        {
            get => _items ?? (_items = new InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecSideCarsVolumesDownwardApiItemsArgs>());
            set => _items = value;
        }

        public TenantSpecSideCarsVolumesDownwardApiArgs()
        {
        }
        public static new TenantSpecSideCarsVolumesDownwardApiArgs Empty => new TenantSpecSideCarsVolumesDownwardApiArgs();
    }
}
