// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Minio.V2
{

    public class TenantSpecPoolsVolumeClaimTemplateArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecPoolsVolumeClaimTemplateMetadataArgs>? Metadata { get; set; }

        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecPoolsVolumeClaimTemplateSpecArgs>? Spec { get; set; }

        [Input("status")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecPoolsVolumeClaimTemplateStatusArgs>? Status { get; set; }

        public TenantSpecPoolsVolumeClaimTemplateArgs()
        {
        }
        public static new TenantSpecPoolsVolumeClaimTemplateArgs Empty => new TenantSpecPoolsVolumeClaimTemplateArgs();
    }
}
