// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Minio.V2
{

    public class TenantSpecSideCarsVolumesScaleIoSecretRefArgs : global::Pulumi.ResourceArgs
    {
        [Input("name")]
        public Input<string>? Name { get; set; }

        public TenantSpecSideCarsVolumesScaleIoSecretRefArgs()
        {
        }
        public static new TenantSpecSideCarsVolumesScaleIoSecretRefArgs Empty => new TenantSpecSideCarsVolumesScaleIoSecretRefArgs();
    }
}
