// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Minio.V2
{

    public class TenantSpecAdditionalVolumesEmptyDirArgs : global::Pulumi.ResourceArgs
    {
        [Input("medium")]
        public Input<string>? Medium { get; set; }

        [Input("sizeLimit")]
        public InputUnion<int, string>? SizeLimit { get; set; }

        public TenantSpecAdditionalVolumesEmptyDirArgs()
        {
        }
        public static new TenantSpecAdditionalVolumesEmptyDirArgs Empty => new TenantSpecAdditionalVolumesEmptyDirArgs();
    }
}
