// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Minio.V2
{

    public class TenantSpecAdditionalVolumesProjectedSourcesSecretArgs : global::Pulumi.ResourceArgs
    {
        [Input("items")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecAdditionalVolumesProjectedSourcesSecretItemsArgs>? _items;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecAdditionalVolumesProjectedSourcesSecretItemsArgs> Items
        {
            get => _items ?? (_items = new InputList<Pulumi.Kubernetes.Types.Inputs.Minio.V2.TenantSpecAdditionalVolumesProjectedSourcesSecretItemsArgs>());
            set => _items = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("optional")]
        public Input<bool>? Optional { get; set; }

        public TenantSpecAdditionalVolumesProjectedSourcesSecretArgs()
        {
        }
        public static new TenantSpecAdditionalVolumesProjectedSourcesSecretArgs Empty => new TenantSpecAdditionalVolumesProjectedSourcesSecretArgs();
    }
}
