apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-ingress-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: cloudflare-ingress-test
spec:
  selector:
    matchLabels:
      app: cf-ing-test
  template:
    metadata:
      labels:
        app: cf-ing-test
    spec:
      containers:
        - name: cf-ing-test
          image: nginxinc/nginx-unprivileged
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ['ALL']
            runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: cloudflare-ingress-test
spec:
  selector:
    app: cf-ing-test
  ports:
  - port: 443
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
  namespace: cloudflare-ingress-test
  labels:
    name: test-ingress
spec:
  ingressClassName: $INGRESS_CLASS_NAME
  rules:
  - host: $SUBDOMAIN.thecluster.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: test-service
            port:
              number: 443
