apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc-runners
  - harbor-system
  - kube-system
  - media
  - necesse
  - nix-system
  - renovate
  - unmango-runners
  - xmage
