// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Bootstrap.V1Alpha3
{

    /// <summary>
    /// TalosConfigStatus defines the observed state of TalosConfig
    /// </summary>
    public class TalosConfigStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Bootstrap.V1Alpha3.TalosConfigStatusConditionsArgs>? _conditions;

        /// <summary>
        /// Conditions defines current service state of the TalosConfig.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Bootstrap.V1Alpha3.TalosConfigStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Bootstrap.V1Alpha3.TalosConfigStatusConditionsArgs>());
            set => _conditions = value;
        }

        /// <summary>
        /// DataSecretName is the name of the secret that stores the bootstrap data script.
        /// </summary>
        [Input("dataSecretName")]
        public Input<string>? DataSecretName { get; set; }

        /// <summary>
        /// FailureMessage will be set on non-retryable errors
        /// </summary>
        [Input("failureMessage")]
        public Input<string>? FailureMessage { get; set; }

        /// <summary>
        /// FailureReason will be set on non-retryable errors
        /// </summary>
        [Input("failureReason")]
        public Input<string>? FailureReason { get; set; }

        /// <summary>
        /// ObservedGeneration is the latest generation observed by the controller.
        /// </summary>
        [Input("observedGeneration")]
        public Input<int>? ObservedGeneration { get; set; }

        /// <summary>
        /// Ready indicates the BootstrapData field is ready to be consumed
        /// </summary>
        [Input("ready")]
        public Input<bool>? Ready { get; set; }

        /// <summary>
        /// Talos config will be a string containing the config for download. 
        ///  Deprecated: please use `&lt;cluster&gt;-talosconfig` secret.
        /// </summary>
        [Input("talosConfig")]
        public Input<string>? TalosConfig { get; set; }

        public TalosConfigStatusArgs()
        {
        }
        public static new TalosConfigStatusArgs Empty => new TalosConfigStatusArgs();
    }
}
