apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator: thecluster
  name: autoscalingtranscodesets.thecluster.io
spec:
  group: thecluster.io
  names:
    kind: AutoScalingTranscodeSet
    listKind: AutoScalingTranscodeSetList
    plural: autoscalingtranscodesets
    singular: autoscalingtranscodeset
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            nullable: false
            properties:
              maxJobs:
                nullable: false
                type: string
              minJobs:
                nullable: false
                type: string
            type: object
          status:
            nullable: false
            properties:
              currentJobs:
                nullable: false
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
