name: Teardown End to End Tests
description: Teardown end to end tests
inputs:
  stack:
    description: The stack for this run
    required: true
runs:
  using: composite
  steps:
    - name: Tear down Cluster API
      if: always()
      working-directory: apps/clusterapi
      run: |
        pulumi down -yf
        pulumi stack rm -yf "rq-${{ inputs.stack-id }}"
      shell: bash

    - name: Tear down metrics-server
      if: always()
      working-directory: apps/metrics-server
      run: |
        pulumi down -yf
        pulumi stack rm -yf "rq-${{ inputs.stack-id }}"
      shell: bash

    - name: Tear down cert-manager
      if: always()
      working-directory: apps/cert-manager
      run: |
        pulumi down -yf
        pulumi stack rm -yf "rq-${{ inputs.stack-id }}"
      shell: bash

    - name: Tear down rosequartz
      if: always()
      working-directory: clusters/rosequartz
      run: |
        pulumi down -yf
        pulumi stack rm -yf "rq-${{ inputs.stack-id }}"
      shell: bash
