// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1
{

    /// <summary>
    /// The deployment strategy to use to replace existing machines with new ones. NOTE: This value can be overridden while defining a Cluster.Topology using this MachineDeploymentClass.
    /// </summary>
    public class ClusterClassSpecWorkersMachineDeploymentsStrategyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Rolling update config params. Present only if MachineDeploymentStrategyType = RollingUpdate.
        /// </summary>
        [Input("rollingUpdate")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterClassSpecWorkersMachineDeploymentsStrategyRollingUpdateArgs>? RollingUpdate { get; set; }

        /// <summary>
        /// Type of deployment. Allowed values are RollingUpdate and OnDelete. The default is RollingUpdate.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ClusterClassSpecWorkersMachineDeploymentsStrategyArgs()
        {
        }
        public static new ClusterClassSpecWorkersMachineDeploymentsStrategyArgs Empty => new ClusterClassSpecWorkersMachineDeploymentsStrategyArgs();
    }
}
