// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1
{

    /// <summary>
    /// Template is a local struct containing a collection of templates for creation of MachinePools objects representing a pool of worker nodes.
    /// </summary>
    public class ClusterClassSpecWorkersMachinePoolsTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Bootstrap contains the bootstrap template reference to be used for the creation of the Machines in the MachinePool.
        /// </summary>
        [Input("bootstrap", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterClassSpecWorkersMachinePoolsTemplateBootstrapArgs> Bootstrap { get; set; } = null!;

        /// <summary>
        /// Infrastructure contains the infrastructure template reference to be used for the creation of the MachinePool.
        /// </summary>
        [Input("infrastructure", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterClassSpecWorkersMachinePoolsTemplateInfrastructureArgs> Infrastructure { get; set; } = null!;

        /// <summary>
        /// Metadata is the metadata applied to the MachinePool. At runtime this metadata is merged with the corresponding metadata from the topology.
        /// </summary>
        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterClassSpecWorkersMachinePoolsTemplateMetadataArgs>? Metadata { get; set; }

        public ClusterClassSpecWorkersMachinePoolsTemplateArgs()
        {
        }
        public static new ClusterClassSpecWorkersMachinePoolsTemplateArgs Empty => new ClusterClassSpecWorkersMachinePoolsTemplateArgs();
    }
}
