// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1
{

    /// <summary>
    /// ValueFrom defines the value of the patch. Note: Either Value or ValueFrom is required for add and replace operations. Only one of them is allowed to be set at the same time.
    /// </summary>
    public class ClusterClassSpecPatchesDefinitionsJsonPatchesValueFromArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Template is the Go template to be used to calculate the value. A template can reference variables defined in .spec.variables and builtin variables. Note: The template must evaluate to a valid YAML or JSON value.
        /// </summary>
        [Input("template")]
        public Input<string>? Template { get; set; }

        /// <summary>
        /// Variable is the variable to be used as value. Variable can be one of the variables defined in .spec.variables or a builtin variable.
        /// </summary>
        [Input("variable")]
        public Input<string>? Variable { get; set; }

        public ClusterClassSpecPatchesDefinitionsJsonPatchesValueFromArgs()
        {
        }
        public static new ClusterClassSpecPatchesDefinitionsJsonPatchesValueFromArgs Empty => new ClusterClassSpecPatchesDefinitionsJsonPatchesValueFromArgs();
    }
}
