// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1
{

    /// <summary>
    /// This encapsulates the topology for the cluster. NOTE: It is required to enable the ClusterTopology feature gate flag to activate managed topologies support; this feature is highly experimental, and parts of it might still be not implemented.
    /// </summary>
    public class ClusterSpecTopologyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the ClusterClass object to create the topology.
        /// </summary>
        [Input("class", required: true)]
        public Input<string> Class { get; set; } = null!;

        /// <summary>
        /// ControlPlane describes the cluster control plane.
        /// </summary>
        [Input("controlPlane")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterSpecTopologyControlPlaneArgs>? ControlPlane { get; set; }

        /// <summary>
        /// RolloutAfter performs a rollout of the entire cluster one component at a time, control plane first and then machine deployments. 
        ///  Deprecated: This field has no function and is going to be removed in the next apiVersion.
        /// </summary>
        [Input("rolloutAfter")]
        public Input<string>? RolloutAfter { get; set; }

        [Input("variables")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterSpecTopologyVariablesArgs>? _variables;

        /// <summary>
        /// Variables can be used to customize the Cluster through patches. They must comply to the corresponding VariableClasses defined in the ClusterClass.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterSpecTopologyVariablesArgs> Variables
        {
            get => _variables ?? (_variables = new InputList<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterSpecTopologyVariablesArgs>());
            set => _variables = value;
        }

        /// <summary>
        /// The Kubernetes version of the cluster.
        /// </summary>
        [Input("version", required: true)]
        public Input<string> Version { get; set; } = null!;

        /// <summary>
        /// Workers encapsulates the different constructs that form the worker nodes for the cluster.
        /// </summary>
        [Input("workers")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Cluster.V1Beta1.ClusterSpecTopologyWorkersArgs>? Workers { get; set; }

        public ClusterSpecTopologyArgs()
        {
        }
        public static new ClusterSpecTopologyArgs Empty => new ClusterSpecTopologyArgs();
    }
}
