apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - mongo-credentials-sealed.yml
  - mongo-init.yml
  - mongo-service.yml
  - mongo-statefulset.yml
  - service.yml
  - statefulset.yml
