---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongo-credentials
  namespace: unifi
spec:
  encryptedData:
    mongodb-password: AgCPIv/HSwyxk2M/t0i1FoIXSCgih/03uqzHzwDdKsg4VK3hzfNmmyljAqHDIaCCYPJeGlqD+t4F1zbQFkIPn7PLRMZjq/hPICkvdwA+cXVe/lUxx+e8izItMl8qS6JldXj6bpekshwz2i/zsaAzNtXm7N83o0q9fSgvV0VpLKeK4Ydyo/Yx3YkpGF/VZxeugQ16Mp0xhl2vcbTKbsOczH8dPy2mOBbC4FHLXCaHaWlXvXv/HxxEL/i/d8RsfUKxyA94actqySZVVXtdsQ6fWPi7faKt4cpp9qhw4EEI12crrNtMQfF67UvZNkHVfSQF2o3lWUY2gaCGxph2QPZs6aELw0CkmIIkVY+wq4D8IM5qoVihpa5Z1ybzKLEpgT8oLGI+Hg7R6pS8DvLWkvUCWzmsDqqPNVD0idO63VlClGJYorXHGg2X4lTJ2fGQMPAU0nKFjeRbuOfhBdWqeQl4kFbrg1AmTkiVig7yaPDxBvXX3eeRPaeVDtONctWXoXYPzHlKTAdIFMasEVgr8TogeAomb4pXkD4sXcMBumBHwZanlIatt+0S/4gqddmZGDcjNi3LSsIkFNxpap19xncjz5J3jQTgA/QPBJrUTzkDZg/dq/VeJIFoCJtNgxLeB1dtKuPh5kckGifo5MgkZ8zjQxuhP5zOakOw7ezKq92mXsBLho9Lm3a+r22vZ+fRRu+d/YHz0XILtKS9k3iONVy3CxgA71nqj5PsMYz6s+TjgaCmfp8d0+1vixD7
    mongodb-root-password: AgAWp7s4Gb3iNo8au1gPcllgoggeViZMIw5O+yObFHYKfnHB820URzCP082B6x36D+RmBMp/Mu1JrJAeel4SmkmlihwyQKRq+1fEFM+KeGb2tT4qnhna/fJ6ygX/HXyZ5OBtztaJAFnVGdUERSwcYaMkooGxOF8CRwp9vXUOGqCus+qNSWJj7XsSpKiW5eGgZ7cn2BgTMaJkN83YlGsKMX1U/RsAV8iNW9YH5ZZgzqYc0VS1QNqPtetl+TK+1oAawGVj2A8sFUuyqT4lyMvVjtiXHufPrdCViaICJYH5ZKJwv4RN4AOIEtv1ByrEcgUMBD6t/IyFRO9tRvnoSWJux/Bb23wW6IurSk7fDs351TsRG1impjjwVvmi2gi4oqgaqWLTJdGf2KyzrpnmLXfc2vjldD92lq+P2T/cs3vzm2+vZ1hfcKmt3N+gww0p0uP6+xcStJc1UDBSFJ8cGYZlweUA1Bcc+YiyoC5NFYd6UUauQr2Ju/fb8AfxlTxIat+lhNsumdH67a8s4h4lqWFWb8ZAi3jWIZ3dBK+5ro/MjbWfwhYFfmbckMdQ2hfk4xc2EaW8apuNnARiDPCgvn1s+beJr184DQBRytwRSoQXXhC7XLXS8Ax8hf6CmaN7fXgO7eCw43XIz2JOCJy5T7qnIoL8f/kxCofSzvXPJ7rs2TZsdmWH99dpzBk6LFq3AZoJtRO/DPYK8u+qbweF41ncE7TBdGxVxx5MoT5gd2RgQ8TiOR0QTKyfsQa9
  template:
    metadata:
      name: mongo-credentials
      namespace: unifi
    type: Opaque
