apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unmango-runners
  namespace: unmango-runners
spec:
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
    namespace: arc-system
  interval: 10m
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    githubConfigUrl: https://github.com/unmango
    githubConfigSecret: thecluster-bot
    minRunners: 3
    maxRunners: 30
    # 99% the dind template
    # https://github.com/actions/actions-runner-controller/blob/8c84ab2f4267ce61df1f6b2e26a3ca12b2d1e4ca/charts/gha-runner-scale-set/values.yaml#L310
    template:
      spec:
        initContainers:
        - name: init-dind-externals
          image: ghcr.io/unstoppablemango/the-cluster/actions-runner:v2.334.0@sha256:5c4288f08305f8e8574c8f00c779426fc4731e322917659cbc337a1178fcae3c
          command: ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
          volumeMounts:
            - name: dind-externals
              mountPath: /home/runner/tmpDir
        - name: dind
          image: docker:dind
          args:
            - dockerd
            - --host=unix:///var/run/docker.sock
            - --group=$(DOCKER_GROUP_GID)
          env:
            - name: DOCKER_GROUP_GID
              value: "123"
          securityContext:
            privileged: true
          restartPolicy: Always
          startupProbe:
            exec:
              command:
                - docker
                - info
            initialDelaySeconds: 0
            failureThreshold: 24
            periodSeconds: 5
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
            - name: dind-externals
              mountPath: /home/runner/externals
        containers:
        - name: runner
          image: ghcr.io/unstoppablemango/the-cluster/actions-runner:v2.334.0@sha256:5c4288f08305f8e8574c8f00c779426fc4731e322917659cbc337a1178fcae3c
          command: [/home/runner/run.sh]
          env:
            - name: DOCKER_HOST
              value: unix:///var/run/docker.sock
            - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
              value: "120"
          volumeMounts:
            - name: work
              mountPath: /home/runner/_work
            - name: dind-sock
              mountPath: /var/run
        volumes:
        - name: work
          emptyDir: {}
        - name: dind-sock
          emptyDir: {}
        - name: dind-externals
          emptyDir: {}
