apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: olmv1
  namespace: olmv1-system
spec:
  interval: 30m
  releaseName: olmv1
  targetNamespace: olmv1-system
  chart:
    spec:
      chart: helm/olmv1
      interval: 30m
      sourceRef:
        kind: GitRepository
        name: operator-controller
  # https://github.com/operator-framework/operator-controller/blob/v1.8.0/helm/olmv1/values.yaml
  values:
    options:
      operatorController:
        deployment:
          image: quay.io/operator-framework/operator-controller:v1.8.0
      catalogd:
        deployment:
          image: quay.io/operator-framework/catalogd:v1.8.0
    deployments:
      templateSpec:
        # k3s sets node-role.kubernetes.io/control-plane=true; chart default expects empty string
        nodeSelector:
          kubernetes.io/os: linux
          node-role.kubernetes.io/control-plane: "true"
