// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2
{

    /// <summary>
    /// Status defines the current state of BackendTLSPolicy.
    /// </summary>
    [OutputType]
    public sealed class BackendTLSPolicyStatus
    {
        /// <summary>
        /// Ancestors is a list of ancestor resources (usually Gateways) that are associated with the policy, and the status of the policy with respect to each ancestor. When this policy attaches to a parent, the controller that manages the parent and the ancestors MUST add an entry to this list when the controller first sees the policy and SHOULD update the entry as appropriate when the relevant ancestor is modified. 
        ///  Note that choosing the relevant ancestor is left to the Policy designers; an important part of Policy design is designing the right object level at which to namespace this status. 
        ///  Note also that implementations MUST ONLY populate ancestor status for the Ancestor resources they are responsible for. Implementations MUST use the ControllerName field to uniquely identify the entries in this list that they are responsible for. 
        ///  Note that to achieve this, the list of PolicyAncestorStatus structs MUST be treated as a map with a composite key, made up of the AncestorRef and ControllerName fields combined. 
        ///  A maximum of 16 ancestors will be represented in this list. An empty list means the Policy is not relevant for any ancestors. 
        ///  If this slice is full, implementations MUST NOT add further entries. Instead they MUST consider the policy unimplementable and signal that on any related resources such as the ancestor that would be referenced here. For example, if this list was full on BackendTLSPolicy, no additional Gateways would be able to reference the Service targeted by the BackendTLSPolicy.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.BackendTLSPolicyStatusAncestors> Ancestors;

        [OutputConstructor]
        private BackendTLSPolicyStatus(ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.BackendTLSPolicyStatusAncestors> ancestors)
        {
            Ancestors = ancestors;
        }
    }
}
