// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2
{

    /// <summary>
    /// TLS contains backend TLS policy configuration.
    /// </summary>
    [OutputType]
    public sealed class BackendTLSPolicySpecTls
    {
        /// <summary>
        /// CACertRefs contains one or more references to Kubernetes objects that contain a PEM-encoded TLS CA certificate bundle, which is used to validate a TLS handshake between the Gateway and backend Pod. 
        ///  If CACertRefs is empty or unspecified, then WellKnownCACerts must be specified. Only one of CACertRefs or WellKnownCACerts may be specified, not both. If CACertRefs is empty or unspecified, the configuration for WellKnownCACerts MUST be honored instead. 
        ///  References to a resource in a different namespace are invalid for the moment, although we will revisit this in the future. 
        ///  A single CACertRef to a Kubernetes ConfigMap kind has "Core" support. Implementations MAY choose to support attaching multiple certificates to a backend, but this behavior is implementation-specific. 
        ///  Support: Core - An optional single reference to a Kubernetes ConfigMap, with the CA certificate in a key named `ca.crt`. 
        ///  Support: Implementation-specific (More than one reference, or other kinds of resources).
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.BackendTLSPolicySpecTlsCaCertRefs> CaCertRefs;
        /// <summary>
        /// Hostname is used for two purposes in the connection between Gateways and backends: 
        ///  1. Hostname MUST be used as the SNI to connect to the backend (RFC 6066). 2. Hostname MUST be used for authentication and MUST match the certificate served by the matching backend. 
        ///  Support: Core
        /// </summary>
        public readonly string Hostname;
        /// <summary>
        /// WellKnownCACerts specifies whether system CA certificates may be used in the TLS handshake between the gateway and backend pod. 
        ///  If WellKnownCACerts is unspecified or empty (""), then CACertRefs must be specified with at least one entry for a valid configuration. Only one of CACertRefs or WellKnownCACerts may be specified, not both. 
        ///  Support: Core for "System"
        /// </summary>
        public readonly string WellKnownCACerts;

        [OutputConstructor]
        private BackendTLSPolicySpecTls(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.BackendTLSPolicySpecTlsCaCertRefs> caCertRefs,

            string hostname,

            string wellKnownCACerts)
        {
            CaCertRefs = caCertRefs;
            Hostname = hostname;
            WellKnownCACerts = wellKnownCACerts;
        }
    }
}
