// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2
{

    /// <summary>
    /// Spec defines the desired state of ReferenceGrant.
    /// </summary>
    [OutputType]
    public sealed class ReferenceGrantSpec
    {
        /// <summary>
        /// From describes the trusted namespaces and kinds that can reference the resources described in "To". Each entry in this list MUST be considered to be an additional place that references can be valid from, or to put this another way, entries MUST be combined using OR. 
        ///  Support: Core
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.ReferenceGrantSpecFrom> From;
        /// <summary>
        /// To describes the resources that may be referenced by the resources described in "From". Each entry in this list MUST be considered to be an additional place that references can be valid to, or to put this another way, entries MUST be combined using OR. 
        ///  Support: Core
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.ReferenceGrantSpecTo> To;

        [OutputConstructor]
        private ReferenceGrantSpec(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.ReferenceGrantSpecFrom> from,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gateway.V1Alpha2.ReferenceGrantSpecTo> to)
        {
            From = from;
            To = to;
        }
    }
}
