// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Metallb.V1Beta2
{

    /// <summary>
    /// passwordSecret is name of the authentication secret for BGP Peer. the secret must be of type "kubernetes.io/basic-auth", and created in the same namespace as the MetalLB deployment. The password is stored in the secret as the key "password".
    /// </summary>
    public class BGPPeerSpecPasswordSecretArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// name is unique within a namespace to reference a secret resource.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// namespace defines the space within which the secret name must be unique.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        public BGPPeerSpecPasswordSecretArgs()
        {
        }
        public static new BGPPeerSpecPasswordSecretArgs Empty => new BGPPeerSpecPasswordSecretArgs();
    }
}
