apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: pulumi-kubernetes-operator
  namespace: pulumi-system
spec:
  interval: 30m
  url: oci://ghcr.io/pulumi/helm-charts/pulumi-kubernetes-operator
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.9.3
