// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Runtime.V1Alpha1
{

    /// <summary>
    /// ExtensionConfigSpec is the desired state of the ExtensionConfig
    /// </summary>
    public class ExtensionConfigSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ClientConfig defines how to communicate with the Extension server.
        /// </summary>
        [Input("clientConfig", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Runtime.V1Alpha1.ExtensionConfigSpecClientConfigArgs> ClientConfig { get; set; } = null!;

        /// <summary>
        /// NamespaceSelector decides whether to call the hook for an object based on whether the namespace for that object matches the selector. Defaults to the empty LabelSelector, which matches all objects.
        /// </summary>
        [Input("namespaceSelector")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Runtime.V1Alpha1.ExtensionConfigSpecNamespaceSelectorArgs>? NamespaceSelector { get; set; }

        [Input("settings")]
        private InputMap<string>? _settings;

        /// <summary>
        /// Settings defines key value pairs to be passed to all calls to all supported RuntimeExtensions. Note: Settings can be overridden on the ClusterClass.
        /// </summary>
        public InputMap<string> Settings
        {
            get => _settings ?? (_settings = new InputMap<string>());
            set => _settings = value;
        }

        public ExtensionConfigSpecArgs()
        {
        }
        public static new ExtensionConfigSpecArgs Empty => new ExtensionConfigSpecArgs();
    }
}
