---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium
  namespace: technitium
spec:
  encryptedData:
    adminPassword: AgBsO7IaY7P9aGYT8FNg4083Tk5XNyW0Kpi2GmgZARJRbgiAHJRurqw2npLNyB8pma6x/PIj9XSeSyo6vjlD8EsJBG3OXq/dlD0OP7710yyeFP3a3ZeupQFEnnCKNl6ebDFtl3toAzc5e3R3W8vqheoAgBdbGKz6+RDHf6FQirhd4dew7Ulwmo1uLxlBwLTWfaVrtj6r06DS08lotO6cDXRM9djwHOLQltz1LEAVBQFiJM8iA+SJM+vkeyKsVYlRb4nqj0GVGBRWaNKD48x4zXLpwd0abFJvvaX+cE/y4wz/f0ZUvt6g1p9smOlhtXK8lm6bqZr27e/cUmaTznmQklTJyXI4RdCPgwkjwOHbnw5kKBy7gi1zi8FrJgKamSwpvGXqhRGUcWdK2hx/v9qhiKCxzJNHybsfGKXLFDXhr+y89xhfGrtdDmoABKSNeY9+zy+/eav4sTMT9FNcmTRhH98NVACR8fseLqIYB9f5xNDdwmCboG95EIX6v4uA0tyUX0yd9Ksw5cL6zaEcRl+076QMsW4CSzvzBVbDRNGxEG+pfch/eT6Nd0ltB73K3vow1owzWUBk6fToXiRBrKfpUu6cqqzgg8L2cLGMC/+0LMG3yBC6zz+6fwLI22F0ZWmv9XbIvjvRz2MnexeMeuDRTUUQLe/5YtqyT8gY/2yMU5+RepgJj/RhcjJruTZeeermwhuUy8V89U/ilJhWdfA/oepbVFof2JyhDiVZYIYvoQk=
  template:
    metadata:
      name: technitium
      namespace: technitium
    type: Opaque
