---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ceph-credentials
  namespace: velero-system
spec:
  encryptedData:
    cloud: AgBn4RSeagN02QQOWHR59BQ+oVzEEj06FB6mEQSJv2SUFcM94uABxjFmDcBlodGrwBohpX/NnBRagBFAi6AhNi2ajXDAAJM8dr0sNnHCYJ0WYTAk0Yq3ZmlwtvaVJ2/pafBZcb+UP3sa+iKOj1F4Tdoad3uRczoCGChDOyck+rRi0sW7s83aHSHUMHH2CYYtNk+CCHgk3BO0cNaoKzcJbVkwi59kIDJcmVrMWF+D6mtEkqydOBP+99aEhoT54PzTm1UVAz+uFI/enOmg5wnrlvCcWQw/DOp8tamWAcBjX9WcWGCoPUEtR6fK8yncZbqW6WkLPl61VByrPRuph0MGktR+vBO+YL4OSbN0M4kmP6KxsgvLlhJ5dJdNOL3g/ZaguJHpkAg227a2PADKITXKmCCJ2G8uV/EEgpf4b5z96EGoZ0UBmp7ZO2nV5xNciAdDY3jx7FJGpt7rZELokoTv+5cW5ZQuq9G1R6A/OgFZCi/PISakhNzsN7l8aREuutt+H1CgEI64jxQf+dOLQyL9CCfzqXEUQA7z1eSym6/SgfeRnRybMO5cxGlgVlTzZ6/RF7IM2ClkPyGNOEIxkjXJn8J1xPCn37Ey+YEfTZ9k62CbTBK2LduZKEWWhmAIh9myux63j+ZXgaV2EI0Sl5C620Yl00a8xGJ2O2IJYwrhqlJ3SN2xUeVWgtv6Q+3Tlui5Tfux3nu7LdkkjVs7oQ+AgZnY1qJlQYQkvBd1lXX5k8+Tn0/CIg1Y4q0JSor8jvaq6/nxAoVUKJVIlrIZRXpuyLrXDJMpYkvJm2KP1W10iRl3/c7wOwoGNAPCfdnqQw7NyeBEQ/efLWPoxxB5BBj+O4k=
  template:
    metadata:
      name: ceph-credentials
      namespace: velero-system
