apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: backblaze
  namespace: velero-system
spec:
  provider: velero.io/aws
  credential:
    name: backblaze-credentials
    key: cloud
  config:
    region: us-west-002
    profile: default
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: thecluster
  namespace: velero-system
spec:
  provider: velero.io/aws
  credential:
    name: ceph-credentials
    key: cloud
  config:
    region: us-east-1
    profile: default
