---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgAZ4kAoCi+NVd1qKILwcZOH02U8Z5fNXG8++0WT++KzV6ZxcUrrzsUtzzYBB8gv8g7BC7B2uds/TVhf8CPNeD+0YBmT7x1R3f6iQj14dgaOArQ/NSuZTOgxyGzrRTY1bmRcIQkFmARp5qvg+GvNCZi2gky3Ew8u/j+qTSJyUWKOQ0MPpDMuvHtyL4adfpbRO/U7WAhMEtkms/BjaCTTphyQMZ38HytTjeBDVHS6gIXAqtOEvgDGZb55z7JMpxlGBqWNnBdP6m6/bSYYZLkoYMFbQR44iBPEeflpsciF6V3/YiLjZYHbJrHdu0OmgJcEZgPoF+L87/+sfDyBHHp8BXpXKOnK/XyfgZuQW1MeVp6H7FClqQsuXDvZ8SRjRrtb2GUsUEwJSWKCLj7ka6QIZRNxlFJkrUHMSGYMniE5g15Fm9iBFZTmf/HLYpTkihON0un56cg5Y21aOCaoyYXNC90s6lwglNa/ajXg9JSFy+O5NQbx41VfzN04KtKrQWp9GAHK20ELYHqSgz3G/C6rMwOzE4aj6o7o7FL+lJpeD8m5r6c+8yDb8g9wLDtLfUcSiDJvZKEeghEANgeQ8q8udMhsoUYjqvkOgP4Ubzz7vKaXdYx4tiVtLMeWBAbUM1xD1Hq0LTGA0LxLzF5Oqyg5L2oqsdikke7AyMQFZM1wN6IDC7Hnez/+//YupFuD72A3v7za4G2YvP0hvzFNhFrPtC31EfuEGS1EGd5lxAb86A3Oe7JAIbdJJTvoGk47TsSWDsK8OwAVFIyYuGfGb1HkVbmjN77ZrBSSJ6aRhSdam9UBxjDvmfop/I+Ktwnq3IR9fRfvEtOOCvFjX2BlXmfBD5tOhUEvn9GTeMxxiTGhfVslkO2A0RHcJU3EUDQAYv1yXQWxABJtCrKx9SVE0vF2FpKgLg+5Ej5D1TVuyVb8D7CYTQJ+1X5+zWwBbNDvRSdCsg==
  template:
    metadata:
      name: keycloak-credentials
      namespace: crossplane-system
