- hosts: "*"
  become: yes
  tasks:
  - name: Fetch install script
    get_url:
      url: "https://get.k3s.io"
      dest: "/usr/local/bin/k3s-install.sh"
      mode: u+rwx

  - name: Create /etc/rancher/k3s
    file:
      path: /etc/rancher/k3s
      state: directory

- hosts: "master"
  become: yes
  tasks:
  - name: Copy master config
    template:
      src: ../templates/k3s/config.yaml.j2
      dest: /etc/rancher/k3s/config.yaml

  - name: Install master
    shell:
      cmd: "/usr/local/bin/k3s-install.sh server --cluster-init"
      creates: "/usr/local/bin/k3s-uninstall.sh"
    environment:
      INSTALL_K3S_VERSION: "v1.19.7+k3s1"

  - name: Wait for server startup
    pause: seconds=20

  # TODO: https://stackoverflow.com/a/47811099/7341217
  - name: Fetch token file
    slurp:
      # Currently, node-token is symlinked to token
      src: /var/lib/rancher/k3s/server/token
    register: node_token

  - name: Fetch kubeconfig
    fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: ~/.kube/the-cluster.yaml
      flat: true
      mode: u=rwx
  
  - name: Add vars to dummy host
    add_host:
      name: "MASTER_VARS"
      groups: master
      master_host: "{{ groups['master'][0] }}"
      node_token: "{{ node_token['content'] | b64decode }}"

- hosts: "*:!master"
  become: yes
  tasks:
  - name: Copy config
    template:
      src: ../templates/k3s/config.yaml.j2
      dest: /etc/rancher/k3s/config.yaml

- hosts: "servers:!master"
  become: yes
  environment:
    INSTALL_K3S_VERSION: "v1.19.7+k3s1"
  tasks:
  - name: Install servers
    shell:
      cmd: "/usr/local/bin/k3s-install.sh server"
      creates: "/usr/local/bin/k3s-uninstall.sh"

- hosts: "agents"
  become: yes
  environment:
    INSTALL_K3S_VERSION: "v1.19.7+k3s1"
  tasks:
  - name: Install agents
    shell:
      cmd: "/usr/local/bin/k3s-install.sh agent"
      creates: "/usr/local/bin/k3s-agent-uninstall.sh"
