- hosts: "*"
  become: yes
  tasks:
  - name: Uninstall k3s
    shell:
      cmd: /usr/local/bin/k3s-uninstall.sh
      removes: /usr/local/bin/k3s-uninstall.sh
    when: server | bool

  - name: Uninstall k3s
    shell:
      cmd: /usr/local/bin/k3s-agent-uninstall.sh
      removes: /usr/local/bin/k3s-agent-uninstall.sh
    when: agent | bool

