---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgAFnLBwEspRUfTHZSVsEtwlRBfF7ZI74fqj0CFfExgzVjpUPSoKbxAtAFazNoELGegyQ8LNdVU7tBsTJcAHfFn+sks126gJBz0tMAiT8nLwJ1SgNzdhUHCe2kcUkf7IFGXHDmxpWhthMXMzpZaLnHoF32lDo1eq9De/pU24KU+xMAf7LcjonWEK5P/jaCn+IIKnQZSpy1QA6BfVBK/Eyd0l4cf78kPbrVrI5liwsEGLphN0hNV4Je6qG/5Qrn8SrVf0w8veYhfpcPv4T7nFA5Ly2Q3v/jeR6Nq9hGdLpwZd+V8THE39KYu3Y7X5dOa62xuUgoBpJZAeSABNMEGwK5asfPMAF6DUpVhBlY//IgchWxGs54AC6BQDmXuEzasVCgx0uXmB/NZyqdOVEaX7iKVwkB9N5Di4C9PN+pU1/SbrkmH6IpzUZ6tP1PXe+EIzxAxk6nnTEU0AeY02T9A8k17o7hR9RGx6NtdyZF4jmqyqiUW+29PVok3Tjqol/rqvuE3YFE2YR3YrTiyFqsq5PGf05HGT3ou5XXgwfVJYUUkFV+k9u9WOxBHj0yh7CY+D8gMo525NlSRmugoDpBBqW8NfO5YMRH7un3BY7gcBeVg19RhXuA7Nwxk40mvHTDSmyox0/J0ZeQdSgyhCxORnklcQkl8r1OcMPhBunpbwGobqqcXROVWkrfhuNU31+otGcpeMHW2SgWitbZLtb5aypXFUDoiupfgxs/93osVD4wOwqAFlmvi7NyC9cAFCNwAGYWXgMRN+qk0dyPM+DFQuXVlb/mZIuZK7Oen7L5E=
  template:
    metadata:
      name: cloudflare-credentials
      namespace: crossplane-system
