// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1
{

    /// <summary>
    /// PodDNSConfigOption defines DNS resolver options of a pod.
    /// </summary>
    public class AutoscalingListenerSpecTemplateSpecDnsConfigOptionsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("value")]
        public Input<string>? Value { get; set; }

        public AutoscalingListenerSpecTemplateSpecDnsConfigOptionsArgs()
        {
        }
        public static new AutoscalingListenerSpecTemplateSpecDnsConfigOptionsArgs Empty => new AutoscalingListenerSpecTemplateSpecDnsConfigOptionsArgs();
    }
}
