// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1
{

    public class AutoscalingListenerSpecProxyArgs : global::Pulumi.ResourceArgs
    {
        [Input("http")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1.AutoscalingListenerSpecProxyHttpArgs>? Http { get; set; }

        [Input("https")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1.AutoscalingListenerSpecProxyHttpsArgs>? Https { get; set; }

        [Input("noProxy")]
        private InputList<string>? _noProxy;
        public InputList<string> NoProxy
        {
            get => _noProxy ?? (_noProxy = new InputList<string>());
            set => _noProxy = value;
        }

        public AutoscalingListenerSpecProxyArgs()
        {
        }
        public static new AutoscalingListenerSpecProxyArgs Empty => new AutoscalingListenerSpecProxyArgs();
    }
}
