apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcluster
    clusterctl.cluster.x-k8s.io: ""
    control-plane: cluster-api-provider-vcluster-controller-manager
  name: cluster-api-provider-vcluster-system
