apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcluster
    clusterctl.cluster.x-k8s.io: ""
  name: cluster-api-provider-vcluster-controller-manager
  namespace: cluster-api-provider-vcluster-system
