apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set-controller
  namespace: arc-system
spec:
  interval: 30m
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.12.1
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: gha-runner-scale-set
  namespace: arc-runners
spec:
  interval: 30m
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.12.1
