context: pinkdiamond
contexts:
    pinkdiamond:
        endpoints:
            - 10.6.0.3
            - 10.6.0.4
            - 10.6.0.5
        nodes:
            - 10.6.0.3
        ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQekNCOHFBREFnRUNBaEVBMENpQWZSaGk2ZStVU3pVcm9ZN2R4VEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qTXhNVEl6TURReU5EQXdXaGNOTXpNeE1USXdNRFF5TkRBd1dqQVFNUTR3REFZRApWUVFLRXdWMFlXeHZjekFxTUFVR0F5dGxjQU1oQU1FcGZyNkJvR3NPYUlpVmJicjRZWUJQekRwZnBBOWFMNGJGCmNuQTRRd0FabzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUcKQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkhYcE5BRjhpay90RTM5WgpadHNSckpiNUY5Wm9NQVVHQXl0bGNBTkJBQ3loOWppTDVpSkhHM0xKRTY4NXAwMjZKZ1p4V2Q5V1ltWXVzdkM3CmpTWWNFYkw1MGY0NytidWN4YnlnUXoxcnZibkdRZ0VWQWtZdFoybnUzRDJFaEFvPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJLVENCM0tBREFnRUNBaEVBdGJnZGpnOVNWUTRXQVRsVjUvS2dhVEFGQmdNclpYQXdFREVPTUF3R0ExVUUKQ2hNRmRHRnNiM013SGhjTk1qTXhNVEl6TURReU5EQXdXaGNOTWpReE1USXlNRFF5TkRBd1dqQVRNUkV3RHdZRApWUVFLRXdodmN6cGhaRzFwYmpBcU1BVUdBeXRsY0FNaEFOTThXK2E0RTdFTnRWbjN2MnordEcrZVpaZmNNdE56Cm13L3lMeFRoUGpPbm8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0I0QXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVVkZWswQVh5S1QrMFRmMWxtMnhHc2x2a1gxbWd3QlFZREsyVndBMEVBMUM4Tgo2QjBZd2oxVGU3WEV5cE5MeHJjU2pxekJwQUhMZk9nL0NoSFZCZDhFS3dTMjJZY3VBUjBCTmRjcVZraG5sSVpHCmkrYmZtUDBFVTZDb3JXRmlEQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSEJmKzllSVUwRVY3bkxiNGZrUWw4U1ZUcS9XRzIzNnNBclJTOGF3V3BlYgotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K

