config:
  thecluster-hosts:hosts:
    pik8s4:
      hostname: pik8s4
      arch: arm64
      installDisk: /dev/mmcblk0
      ip: 192.168.1.104
      clusterIp: 10.69.1.1
      vlan:
        tag: 69
        name: eth0.69
        interface: eth0
    pik8s5:
      hostname: pik8s5
      arch: arm64
      installDisk: /dev/mmcblk0
      ip: 192.168.1.105
      clusterIp: 10.69.1.2
      vlan:
        tag: 69
        name: eth0.69
        interface: eth0
    pik8s6:
      hostname: pik8s6
      arch: arm64
      installDisk: /dev/mmcblk0
      ip: 192.168.1.106
      clusterIp: 10.69.1.3
      vlan:
        tag: 69
        name: eth0.69
        interface: eth0
    vrk8s1:
      hostname: vrk8s1
      arch: amd64
      ip: 192.168.1.107
      clusterIp: 10.69.2.10
      installDisk: /dev/sda
      vlan:
        tag: 69
        name: eth0.69
        interface: eth0
    # pik8s0a:
    #   hostname: pik8s0a
    #   ip: 192.168.1.114
    #   clusterIp: 10.69.2.11
    #   installDisk: /dev/mmcblk0
    #   nodeTaints:
    #     thecluster.io/portable: true:NoSchedule
    pik8s8:
      hostname: pik8s8
      arch: arm64
      ip: 192.168.1.115
      clusterIp: 10.69.2.12
      installDisk: /dev/mmcblk0
      vlan:
        tag: 69
        name: eth0.69
        interface: eth0
    zeus:
      hostname: zeus
      arch: amd64
      ip: 192.168.1.10
      clusterIp: 10.69.2.1
      installDisk: /dev/sda
      nodeLabels:
        thecluster.io/zfs: true
    gaea:
      hostname: gaea
      arch: amd64
      ip: 192.168.1.11
      clusterIp: 10.69.2.2
      installDisk: /dev/sda
      nodeLabels:
        thecluster.io/zfs: true
      vlan:
        tag: 69
        name: eno2.69
        interface: eno2
    # apollo:
    #   hostname: apollo
    #   arch: amd64
    #   ip: 192.168.1.12
    #   clusterIp: 10.69.2.3
    #   installDisk: /dev/nvme0n1
    #   nodeLabels:
    #     thecluster.io/zfs: true
