apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
  namespace: cert-manager
spec:
  interval: 30m
  releaseName: cert-manager-csi-driver
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager-csi-driver
      version: v0.12.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
  # https://github.com/cert-manager/csi-driver/blob/main/deploy/charts/csi-driver/values.yaml
  values:
    image:
      repository: quay.io/jetstack/cert-manager-csi-driver
      tag: v0.12.0
    nodeDriverRegistrarImage:
      repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
      tag: v2.15.0
    livenessProbeImage:
      repository: registry.k8s.io/sig-storage/livenessprobe
      tag: v2.17.0
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
