// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Metallb.V1Beta2
{

    /// <summary>
    /// passwordSecret is name of the authentication secret for BGP Peer. the secret must be of type "kubernetes.io/basic-auth", and created in the same namespace as the MetalLB deployment. The password is stored in the secret as the key "password".
    /// </summary>
    [OutputType]
    public sealed class BGPPeerSpecPasswordSecret
    {
        /// <summary>
        /// name is unique within a namespace to reference a secret resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// namespace defines the space within which the secret name must be unique.
        /// </summary>
        public readonly string Namespace;

        [OutputConstructor]
        private BGPPeerSpecPasswordSecret(
            string name,

            string @namespace)
        {
            Name = name;
            Namespace = @namespace;
        }
    }
}
