version: '3'

# Attempt to mimic the output of `talosctl cluster create --provisioner docker ...`
# The CLI doesn't seem to have a clean way to start a node in maintenence
# mode, so we'll just stand it up manually for now.

name: rosequartz

x-controlplane: &controlplane
  image: ghcr.io/siderolabs/talos:v1.4.8
  environment:
    PLATFORM: container
  labels:
    talos.cluster.name: rosequartz
    talos.owned: false
    talos.type: controlplane
  tmpfs:
    - /run
    - /system
    - /tmp
  privileged: true
  security_opt:
    - seccomp:unconfined
    - label=disable

services:
  talos-controlplane-1:
    container_name: 'rosequartz-talos-controlplane-1'
    <<: *controlplane
    networks:
      default:
        ipv4_address: '10.5.0.2'
    ports:
      - 50000:50000/tcp
      - 6443:6443/tcp
  talos-controlplane-2:
    container_name: 'rosequartz-talos-controlplane-2'
    <<: *controlplane
    networks:
      default:
        ipv4_address: '10.5.0.3'
    ports:
      - 50001:50000/tcp
      - 6444:6443/tcp
  talos-controlplane-3:
    container_name: 'rosequartz-talos-controlplane-3'
    <<: *controlplane
    networks:
      default:
        ipv4_address: '10.5.0.4'
    ports:
      - 50002:50000/tcp
      - 6445:6443/tcp

networks:
  default:
    labels:
      talos.cluster.name: rosequartz
      talos.owned: false
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24
