---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    KC_BOOTSTRAP_ADMIN_PASSWORD: AgBMEwSDPo9BzaEpQiMa6aEG047sHzAv6HhKnxAIfTP75G+eMKDrysBjM0j2yw6PN8mv4qm9Vz6KuyZYbxPSMu67nFRmkLmhohafFqR72Is7AFSRLsbhO+64od6i8VKP05dWGjsOkBXCV1Ac79gnXvA9Ou9v4wmvlcmeLnH2iqzXGJKKEPy3XrA1YXeaz1LLrez50nyq+1V1zPaO8aZpVA2MzHP8O+4VxoJlKieAGUBO0iWeW+xC58/ONKQusgAnMo1uJI6d9Sek7usqbHox0n6RUoEkVRUc/fM1O5pcWZUuaZKU1053H3kPuihwilSEXJ0169GrT1PN6of3+p7IQY6MeZPuOcqd1GmCRkbynO2m2ZTksrykwZv4ss3p8SLl9cXdSxrAb+t8/IDnplzTJoUzokM/GYbUcFEcieGKJfGFlf6cLhYliscgIVQixjzUP7OVIlSKZJ2E6S+lWeMbki+e7sS5FUa/1buLraEm4ffn6aAruC0B/MlMGrGxs4UXPTOPEjzO3R+DpdVkLZBFJANZZ6EhwZDFuiujVlVTJGpcUEt4FVaQIlr6UwiVv/9ybwsOCEwya9z2dBKLGMdDVxOt+cbZqusGrfcOrnEIckMoJh6ZOGn+VRUQOINrlEOEMYzJYuyIyC4+VyS3n2tj5OuA0XAcB577iE+29xZ1n/fgI+JM2b3/Yw7ibEhxftGsRjQT+6eJTEQ7k/ZlCfB9p+WbrxTHukYr3i33HSBgV1NwgHiTPqL0b07E6q3aDg==
    KC_BOOTSTRAP_ADMIN_USERNAME: AgC+1eoUSzfsESWHHyL+xKE1Um2om4vqmYcMAIUFIkv/VzBAtLwdJyqA4zWds2Ym+ySFpMEpjrR4Jt7AkQNIJBq83nBa/ElvoecqRyoA1e7/MalROIE9nsEPnt0+sTIwYm2E4Lni4MwiUl3TaQD4cVdBG+07A7SP27KVeiEoeVArZdG47bqV8sjtnwbOBbVep9XFdaqW8sfEAwuWhxkV6cVoO9TKPvIUjVCJqZAXd4a4NfaT3FFMLUwBJ2gl2dWtZ/J+FUj9ddMK8ANYCxg2UpzajLiF1OOP0giA/+W06ESf+uo9AYV6feBTkOPA+UiArZlr9hoRMmj3Xpmy97WXL4K+6e38FqqMq7fyBxpwzP9Jc8YMImMvjtgcoSDLMaOUYxDy+1NnmCzJzW2FcK9/FbayFSwtbEPMAB2kHx1DRjXTPJeUoAofVNgfe8CQWkWqXu1hadmKM7OPR0bfDNpizODoPTtnsYjglgANa5HeP4skkZ6kEC8s5H/Aiijvo61qqLLKRfGC1jPTdG0KXpzn/nmv+9S89g3OP9k2YO/IZupPL4uDHeZ96sMPMzfTB9fz3P5opJhKtlxvRMvsz6JNxXGFDkZuTjqkesb1cbGoaIeP2NECBSishFohkq3ZrJetWaBrIAlVHCypePyHH4OCjiYjT4zYvtdxC6HfRlqoOvYTMZxHhveuICC0P++GQ5CkuJankME8Jg==
  template:
    metadata:
      name: keycloak
      namespace: keycloak
    type: Opaque
