apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  # - secret-sealed.yml # add once sealed: see hack/secrets/apps/keycloak/keycloak.yml
  - certificate.yml
  - postgres-cluster.yml
  - helm-repository.yml
  - helm-release.yml
  - ingress.yml
  - httproute.yml
