// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Infrastructure.V1Alpha2
{

    /// <summary>
    /// MetalMachineTemplateSpec defines the desired state of MetalMachineTemplate.
    /// </summary>
    public class MetalMachineTemplateSpecArgs : global::Pulumi.ResourceArgs
    {
        [Input("template", required: true)]
        public Input<Pulumi.Kubernetes.Types.Inputs.Infrastructure.V1Alpha2.MetalMachineTemplateSpecTemplateArgs> Template { get; set; } = null!;

        public MetalMachineTemplateSpecArgs()
        {
        }
        public static new MetalMachineTemplateSpecArgs Empty => new MetalMachineTemplateSpecArgs();
    }
}
