apiVersion: v2
name: velero
description: Velero install for THECLUSTER
type: application
version: 0.1.0
dependencies:
  - name: velero
    repository: https://vmware-tanzu.github.io/helm-charts
    version: 8.1.0
