apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: coredns-system
spec:
  selector:
    app.kubernetes.io/name: etcd
  clusterIP: None
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
