// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1
{

    /// <summary>
    /// RolloutStatus contains information about the rollout. It is set only if a rollout strategy was configured in the spec.
    /// </summary>
    [OutputType]
    public sealed class DataPlaneStatusRollout
    {
        /// <summary>
        /// Conditions contains the status conditions about the rollout.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRolloutConditions> Conditions;
        /// <summary>
        /// Deployment contains the information about the preview deployment.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRolloutDeployment Deployment;
        /// <summary>
        /// Services contain the information about the services which are available through which user can access the preview deployment.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRolloutServices Services;

        [OutputConstructor]
        private DataPlaneStatusRollout(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRolloutConditions> conditions,

            Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRolloutDeployment deployment,

            Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRolloutServices services)
        {
            Conditions = conditions;
            Deployment = deployment;
            Services = services;
        }
    }
}
