name: thecluster-ceph
description: Ceph infrastructure for THECLUSTER
runtime:
  name: nodejs
  options:
    packagemanager: yarn
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
  versions:
    value:
      ceph: 18.2.4
      chart: 1.17.6
      rook: 1.15.4
