// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TheCluster.Crds.Gatewayoperator.V1Alpha1
{
    /// <summary>
    /// ControlPlane is the Schema for the controlplanes API
    /// </summary>
    [TheCluster.CrdsResourceType("kubernetes:gateway-operator.konghq.com/v1alpha1:ControlPlane")]
    public partial class ControlPlane : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// ControlPlaneSpec defines the desired state of ControlPlane
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Alpha1.ControlPlaneSpec> Spec { get; private set; } = null!;

        /// <summary>
        /// ControlPlaneStatus defines the observed state of ControlPlane
        /// </summary>
        [Output("status")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Alpha1.ControlPlaneStatus> Status { get; private set; } = null!;


        /// <summary>
        /// Create a ControlPlane resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ControlPlane(string name, Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.ControlPlaneArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:gateway-operator.konghq.com/v1alpha1:ControlPlane", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal ControlPlane(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:gateway-operator.konghq.com/v1alpha1:ControlPlane", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private ControlPlane(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:gateway-operator.konghq.com/v1alpha1:ControlPlane", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.ControlPlaneArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.ControlPlaneArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.ControlPlaneArgs();
            args.ApiVersion = "gateway-operator.konghq.com/v1alpha1";
            args.Kind = "ControlPlane";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ControlPlane resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ControlPlane Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ControlPlane(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1
{

    public class ControlPlaneArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// ControlPlaneSpec defines the desired state of ControlPlane
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.ControlPlaneSpecArgs>? Spec { get; set; }

        /// <summary>
        /// ControlPlaneStatus defines the observed state of ControlPlane
        /// </summary>
        [Input("status")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.ControlPlaneStatusArgs>? Status { get; set; }

        public ControlPlaneArgs()
        {
        }
        public static new ControlPlaneArgs Empty => new ControlPlaneArgs();
    }
}
