apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-cloudflare-operator
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/controllers/cloudflare-operator-system
  interval: 10m
  prune: true
  wait: true
