apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arc-system.yaml
  - cert-manager.yaml
  - cloudflare-operator.yaml
  - cloudflare.yaml
  - cnpg.yaml
  - coredns.yaml
  - crossplane.yaml
  - flux.yaml
  - metallb.yaml
  - metrics-server.yaml
  - nats.yaml
  - nginx-gateway.yaml
  - velero.yaml
