---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-credentials
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgCHf9GYn9KE7/1n/GgOPKXJfuDSiuCo5m8qS1kC+y4aKKMAwz5pEwHYqkBqoHrrrCnOw8D/ScX96CoNnSTFLvFzGNJn6bvwelBMQ88/Slk7HyMSw5lXxiPbXyd1dtsav5TQaqLPtDd6K4fisbNUY8bNudlPzYv1cN4U8yGrw9whypvbfpkzgLhLfGe9l0KkgFu/WcsrZm8Enj2FbZjBzPp2rbNbBdQHCR/GK94lBgCiTDS3DBcB3ddFAtZDQX0BNOcTR4SJDwOx68neNumEr6Yjm073RV5kxuSCt9VMADOsCG0uWmMvz3g/KMVpSIqfkcpCuLWEEBu3UBdlCV1qZvR5rZmSs6YrX955ELRDitNoiS2pr/ooatdl3X8ksZlS4BOd1BBVhXJwnekL6A4p5tXQeAvottimiQiwkUAz/Hia4e2qYTSynZXbYcm70U4DY20LQDfpyliQCApBRPEtwiZmb0+91pt7t1OCfnA/OIctIJhDtU+pJE5refHJKbXp7xHLYwz7e+o+Kzay8z3+BbuM5grH5Vq3PSnvYFoe4EGKuW/fuSRSKDQgTr7JCRegcqIjRCZpMPCAplGCP/EX2R1S0lg/1zMZh/Bj0sxJsDBlN0CPhmF0MjVEzhD5Dte6bNyTyBvS5JJeka0FfACGHMoynCRAGXvRZKlWcjGdKhNCRJ0PfroAT51Pus2GOqkN2bfO5J+ULYu9fx/UWOpXQGNJuiZ0S7KPJKkIF22Bu5VC3fFv1KTLLr7+QCusCKeKcOPLg/cySgypUJHOdBkq4N/htw1mFqNQLl8FUAEydYhJE1E+VU/vKI8KIcQqfk9yZMO1+aNrMsaIAhEyuzIQMdc=
  template:
    metadata:
      name: aws-credentials
      namespace: crossplane-system
