// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as utilities from "../../utilities";

import {ObjectMeta} from "../../meta/v1";

/**
 * MachineHealthCheck is the Schema for the machinehealthchecks API.
 *  Deprecated: This type will be removed in one of the next releases.
 */
export class MachineHealthCheck extends pulumi.CustomResource {
    /**
     * Get an existing MachineHealthCheck resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): MachineHealthCheck {
        return new MachineHealthCheck(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kubernetes:cluster.x-k8s.io/v1alpha4:MachineHealthCheck';

    /**
     * Returns true if the given object is an instance of MachineHealthCheck.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MachineHealthCheck {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MachineHealthCheck.__pulumiType;
    }

    public readonly apiVersion!: pulumi.Output<"cluster.x-k8s.io/v1alpha4" | undefined>;
    public readonly kind!: pulumi.Output<"MachineHealthCheck" | undefined>;
    public readonly metadata!: pulumi.Output<ObjectMeta | undefined>;
    /**
     * Specification of machine health check policy
     */
    public readonly spec!: pulumi.Output<outputs.cluster.v1alpha4.MachineHealthCheckSpec | undefined>;
    /**
     * Most recently observed status of MachineHealthCheck resource
     */
    public readonly status!: pulumi.Output<outputs.cluster.v1alpha4.MachineHealthCheckStatus | undefined>;

    /**
     * Create a MachineHealthCheck resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: MachineHealthCheckArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["apiVersion"] = "cluster.x-k8s.io/v1alpha4";
            resourceInputs["kind"] = "MachineHealthCheck";
            resourceInputs["metadata"] = args ? args.metadata : undefined;
            resourceInputs["spec"] = args ? args.spec : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        } else {
            resourceInputs["apiVersion"] = undefined /*out*/;
            resourceInputs["kind"] = undefined /*out*/;
            resourceInputs["metadata"] = undefined /*out*/;
            resourceInputs["spec"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MachineHealthCheck.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a MachineHealthCheck resource.
 */
export interface MachineHealthCheckArgs {
    apiVersion?: pulumi.Input<"cluster.x-k8s.io/v1alpha4">;
    kind?: pulumi.Input<"MachineHealthCheck">;
    metadata?: pulumi.Input<ObjectMeta>;
    /**
     * Specification of machine health check policy
     */
    spec?: pulumi.Input<inputs.cluster.v1alpha4.MachineHealthCheckSpecArgs>;
    /**
     * Most recently observed status of MachineHealthCheck resource
     */
    status?: pulumi.Input<inputs.cluster.v1alpha4.MachineHealthCheckStatusArgs>;
}
