apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: pink-diamond
  namespace: pink-diamond
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: pink-diamond-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: pink-diamond
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: pink-diamond
  namespace: pink-diamond
spec:
  controlPlaneEndpoint:
    host: 192.168.1.100
    port: 6444
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: pink-diamond-cp
  namespace: pink-diamond
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha2
        kind: ServerClass
        name: rpi
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: pink-diamond-cp
  namespace: pink-diamond
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.5.3
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: pink-diamond-cp
  replicas: 3
  version: v1.28.2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
kind: TalosConfigTemplate
metadata:
  name: pink-diamond-workers
  namespace: pink-diamond
spec:
  template:
    spec:
      generateType: join
      talosVersion: v1.5.3
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: pink-diamond-workers
  namespace: pink-diamond
spec:
  clusterName: pink-diamond
  replicas: 2
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: pink-diamond-workers
      clusterName: pink-diamond
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: MetalMachineTemplate
        name: pink-diamond-workers
      version: v1.28.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: pink-diamond-workers
  namespace: pink-diamond
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha2
        kind: ServerClass
        name: rpi
