apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - pg-credentials-sealed.yml
  - secret-sealed.yml
  - helm-repository.yml
  - postgres-cluster.yml
  - pg-issuer.yml
  - pg-client-cert.yml
  - pg-db-config.yml
  - helm-release.yml
  - ingress.yml
  - email-identity.yml
