apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: bitwarden
spec:
  instances: 1
  storage:
    storageClass: ssd-rbd
    size: 5Gi
  postgresql:
    pg_hba:
      - hostssl bitwarden bitwarden all cert
  bootstrap:
    initdb:
      database: bitwarden
      owner: bitwarden
      secret:
        name: pg-credentials
