apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 10m
  releaseName: crossplane
  targetNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
  # https://github.com/crossplane/crossplane/blob/main/cluster/charts/crossplane/values.yaml
  values:
    replicas: 2
    image:
      repository: xpkg.crossplane.io/crossplane/crossplane # default
      tag: v2.0.2
    provider:
      packages:
        - xpkg.crossplane.io/crossplane-contrib/provider-kubernetes:v1.0.0
        - xpkg.crossplane.io/crossplane-contrib/provider-family-aws:v2.0.0
        - xpkg.crossplane.io/crossplane-contrib/provider-family-azure:v2.0.0
        - xpkg.crossplane.io/crossplane-contrib/provider-keycloak:v2.6.0
