apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: control-plane-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cacppt-leader-election-rolebinding
  namespace: cacppt-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cacppt-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cacppt-system
