apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: cloudflare
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      key: CLOUDFLARE_API_TOKEN
      name: credentials
