apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: strll.dev
  namespace: cloudflare-system
spec:
  url: https://helm.strrl.dev
  interval: 1h
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: unmango-cloudflare-operator
  namespace: cloudflare-system
spec:
  url: https://unmango.github.io/cloudflare-operator
  interval: 1h
