apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator: thecluster
    operator-deployment: kubernetes-operator
  name: {{ .Release.Name }}-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: thecluster
      operator-deployment: kubernetes-operator
  template:
    metadata:
      labels:
        operator: thecluster
        operator-deployment: kubernetes-operator
    spec:
      containers:
      - image: {{ include "image" . }}
        name: operatorenv:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
