// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.TheCluster.Crds.K8s.V1Alpha1
{
    /// <summary>
    /// GlobalConfiguration defines the GlobalConfiguration resource.
    /// </summary>
    [TheCluster.CrdsResourceType("kubernetes:k8s.nginx.org/v1alpha1:GlobalConfiguration")]
    public partial class GlobalConfiguration : KubernetesResource
    {
        [Output("apiVersion")]
        public Output<string> ApiVersion { get; private set; } = null!;

        [Output("kind")]
        public Output<string> Kind { get; private set; } = null!;

        [Output("metadata")]
        public Output<Pulumi.Kubernetes.Types.Outputs.Meta.V1.ObjectMeta> Metadata { get; private set; } = null!;

        /// <summary>
        /// GlobalConfigurationSpec is the spec of the GlobalConfiguration resource.
        /// </summary>
        [Output("spec")]
        public Output<Pulumi.Kubernetes.Types.Outputs.K8s.V1Alpha1.GlobalConfigurationSpec> Spec { get; private set; } = null!;


        /// <summary>
        /// Create a GlobalConfiguration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GlobalConfiguration(string name, Pulumi.Kubernetes.Types.Inputs.K8s.V1Alpha1.GlobalConfigurationArgs? args = null, CustomResourceOptions? options = null)
            : base("kubernetes:k8s.nginx.org/v1alpha1:GlobalConfiguration", name, MakeArgs(args), MakeResourceOptions(options, ""))
        {
        }
        internal GlobalConfiguration(string name, ImmutableDictionary<string, object?> dictionary, CustomResourceOptions? options = null)
            : base("kubernetes:k8s.nginx.org/v1alpha1:GlobalConfiguration", name, new DictionaryResourceArgs(dictionary), MakeResourceOptions(options, ""))
        {
        }

        private GlobalConfiguration(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("kubernetes:k8s.nginx.org/v1alpha1:GlobalConfiguration", name, null, MakeResourceOptions(options, id))
        {
        }

        private static Pulumi.Kubernetes.Types.Inputs.K8s.V1Alpha1.GlobalConfigurationArgs? MakeArgs(Pulumi.Kubernetes.Types.Inputs.K8s.V1Alpha1.GlobalConfigurationArgs? args)
        {
            args ??= new Pulumi.Kubernetes.Types.Inputs.K8s.V1Alpha1.GlobalConfigurationArgs();
            args.ApiVersion = "k8s.nginx.org/v1alpha1";
            args.Kind = "GlobalConfiguration";
            return args;
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GlobalConfiguration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GlobalConfiguration Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new GlobalConfiguration(name, id, options);
        }
    }
}
namespace Pulumi.Kubernetes.Types.Inputs.K8s.V1Alpha1
{

    public class GlobalConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiVersion")]
        public Input<string>? ApiVersion { get; set; }

        [Input("kind")]
        public Input<string>? Kind { get; set; }

        [Input("metadata")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Meta.V1.ObjectMetaArgs>? Metadata { get; set; }

        /// <summary>
        /// GlobalConfigurationSpec is the spec of the GlobalConfiguration resource.
        /// </summary>
        [Input("spec")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1Alpha1.GlobalConfigurationSpecArgs>? Spec { get; set; }

        public GlobalConfigurationArgs()
        {
        }
        public static new GlobalConfigurationArgs Empty => new GlobalConfigurationArgs();
    }
}
