---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pihole
  namespace: pihole
spec:
  encryptedData:
    password: AgCmN3STvUlI2OF669bnISHFNujV+tb8p69vkT+G8TnAvXef/pQdfmHLinnVgZDbK7XfkjZ6mhZHAuOtZQayF/dBZlGYIyiENAnUkW4DnrMHxRL2k5LaQGEiZ0PHa1hFIlCwqsWT9cVqGJ859FwDCDm5t2JWYnADGJfVHM46IBGLu9d5bVmwSCxNr1sjKHKf+voNnad/+l7hfKReo51uUs/NwkzuW7jj2OH/qgfmK2tF80PrlIUndRrpT31FzV9+78u61jSeVSoI8Pg6MdsghO0JTQH56M06cmsmjgq8NFTYOAtrABqgtg90hUwLON6vn57Uq92qDXBmMEj8irVt7iXbOU5DNa/oQ+m/1W1HeP27y8MyCS17SAnE2UGDLBHG3BYZ2dLmEEwA2zlKbXdTD0irsR6pbZ3NApTxSMLluYHCCb8Y3mxn2wJKFvEqe2qRofSDfLUiG/BuJC0EqM+rW/VYU6B7PsrLgeqgEhMd7HQEd8LIOSCdaGFciGe7Ze18cSXk8m7F6nrM76grKZgAu0/rx3SRmgafPN3WHDN0DCvzcmeT20sCNcyaCbPPEp1CTkSR7ADnRj384pjAy8MZHPJXY4u56F6RPOyTyJwc0tgGURGQX87nMc+VPOmHu3EZsFN7R5UOwE25aDsmLc3xdoFhkiNBwcBfNmonVu4X5WbQ4Iq1sOxtu9GvtnBnOL98Hhw=
  template:
    metadata:
      name: pihole
      namespace: pihole
    type: Opaque
