apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    # cert-manager-csi-driver's node-registrar container requires privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
