version: '3'

name: rosequartz

services:
  talos-controlplane:
    image: ghcr.io/siderolabs/talos:v1.5.2
    environment:
      PLATFORM: container
      TALOSSKU: 2CPU-2048RAM
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    labels:
      org.opencontainers.image.source: https://github.com/siderolabs/talos
      talos.cluster.name: rosequartz
      talos.owned: false
      talos.type: controlplane
    networks:
      default:
        ipv4_address: '10.5.0.2'
    ports:
      - 50000:50000/tcp
      - 6443:6443/tcp
    tmpfs:
      - /run
      - /system
      - /tmp
    volumes:
      - cni:/etc/cni
      - etcK8s:/etc/kubernetes
      - libexecK8s:/usr/libexec/kubernetes
      - opt:/opt
      - udev:/usr/etc/udev
      - var:/var
      - state:/system/state
    privileged: true
    security_opt:
      - seccomp:unconfined
      - label=disable
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0

volumes:
  cni:
  etcK8s:
  libexecK8s:
  opt:
  udev:
  var:
  state:

networks:
  default:
    labels:
      talos.cluster.name: rosequartz
      talos.owned: false
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/24
