// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1
{

    /// <summary>
    /// hostPath represents a pre-existing file or directory on the host machine that is directly exposed to the container. This is generally used for system agents or other privileged things that are allowed to see the host machine. Most containers will NOT need this. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath --- TODO(jonesdl) We need to restrict who can use host directory mounts and who can/can not mount host directories as read/write.
    /// </summary>
    public class ControlPlaneSpecDeploymentPodTemplateSpecSpecVolumesHostPathArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// path of the directory on the host. If the path is a symlink, it will follow the link to the real path. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath
        /// </summary>
        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        /// <summary>
        /// type for HostPath Volume Defaults to "" More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public ControlPlaneSpecDeploymentPodTemplateSpecSpecVolumesHostPathArgs()
        {
        }
        public static new ControlPlaneSpecDeploymentPodTemplateSpecSpecVolumesHostPathArgs Empty => new ControlPlaneSpecDeploymentPodTemplateSpecSpecVolumesHostPathArgs();
    }
}
