// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1
{

    /// <summary>
    /// PodSchedulingGate is associated to a Pod to guard its scheduling.
    /// </summary>
    public class GatewayConfigurationSpecControlPlaneOptionsDeploymentPodTemplateSpecSpecSchedulingGatesArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the scheduling gate. Each scheduling gate must have a unique name field.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GatewayConfigurationSpecControlPlaneOptionsDeploymentPodTemplateSpecSpecSchedulingGatesArgs()
        {
        }
        public static new GatewayConfigurationSpecControlPlaneOptionsDeploymentPodTemplateSpecSpecSchedulingGatesArgs Empty => new GatewayConfigurationSpecControlPlaneOptionsDeploymentPodTemplateSpecSpecSchedulingGatesArgs();
    }
}
