// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8s.V1
{

    /// <summary>
    /// Action defines an action.
    /// </summary>
    [OutputType]
    public sealed class VirtualServerRouteSpecSubroutesMatchesAction
    {
        public readonly string Pass;
        /// <summary>
        /// ActionProxy defines a proxy in an Action.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionProxy Proxy;
        /// <summary>
        /// ActionRedirect defines a redirect in an Action.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionRedirect Redirect;
        /// <summary>
        /// ActionReturn defines a return in an Action.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionReturn Return;

        [OutputConstructor]
        private VirtualServerRouteSpecSubroutesMatchesAction(
            string pass,

            Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionProxy proxy,

            Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionRedirect redirect,

            Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionReturn @return)
        {
            Pass = pass;
            Proxy = proxy;
            Redirect = redirect;
            Return = @return;
        }
    }
}
