// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8s.V1
{

    /// <summary>
    /// CertManager defines a cert manager config for a TLS.
    /// </summary>
    [OutputType]
    public sealed class VirtualServerSpecTlsCertManager
    {
        public readonly string Cluster-issuer;
        public readonly string Common-name;
        public readonly string Duration;
        public readonly bool Issue-temp-cert;
        public readonly string Issuer;
        public readonly string Issuer-group;
        public readonly string Issuer-kind;
        public readonly string Renew-before;
        public readonly string Usages;

        [OutputConstructor]
        private VirtualServerSpecTlsCertManager(
            string cluster-issuer,

            string common-name,

            string duration,

            bool issue-temp-cert,

            string issuer,

            string issuer-group,

            string issuer-kind,

            string renew-before,

            string usages)
        {
            Cluster-issuer = cluster-issuer;
            Common-name = common-name;
            Duration = duration;
            Issue-temp-cert = issue-temp-cert;
            Issuer = issuer;
            Issuer-group = issuer-group;
            Issuer-kind = issuer-kind;
            Renew-before = renew-before;
            Usages = usages;
        }
    }
}
