// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8s.V1
{

    /// <summary>
    /// ErrorPageReturn defines a return for an ErrorPage.
    /// </summary>
    [OutputType]
    public sealed class VirtualServerRouteSpecSubroutesErrorPagesReturn
    {
        public readonly string Body;
        public readonly int Code;
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesErrorPagesReturnHeaders> Headers;
        public readonly string Type;

        [OutputConstructor]
        private VirtualServerRouteSpecSubroutesErrorPagesReturn(
            string body,

            int code,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.K8s.V1.VirtualServerRouteSpecSubroutesErrorPagesReturnHeaders> headers,

            string type)
        {
            Body = body;
            Code = code;
            Headers = headers;
            Type = type;
        }
    }
}
