config:
  thecluster-proxmox:proxmox:
    endpoint: https://zeus.unmango.net
    insecure: false
    password:
      secure: AAABAIIYTNJk2e60etNsYhk7MbO4wIh3fv9W8TIOhjNJ13Yx5y52jwgkhAXbjIJ07X6s4iwyOf8lb9Cz3TM=
    username: pulumi@pam
  thecluster-proxmox:iso:
    node: zeus
  thecluster-proxmox:controlPlanes: [] # ControlPlane uses rpi4s
  thecluster-proxmox:workers:
    - name: zeus1
      node: zeus
      cpu: 8
      mem: 8192
    - name: zeus2
      node: zeus
      cpu: 8
      mem: 8192
    - name: apollo1
      node: apollo
      cpu: 8
      mem: 8192
    - name: apollo2
      node: apollo
      cpu: 8
      mem: 8192
    - name: zeus3
      node: zeus
      cpu: 8
      mem: 16384
    - name: zeus4
      node: zeus
      cpu: 8
      mem: 16384
