# permissions for end users to view wireguardclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: thecluster
    app.kubernetes.io/managed-by: kustomize
  name: wireguardclient-viewer-role
rules:
- apiGroups:
  - core.thecluster.io
  resources:
  - wireguardclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.thecluster.io
  resources:
  - wireguardclients/status
  verbs:
  - get
