# permissions for end users to edit wireguardclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: thecluster
    app.kubernetes.io/managed-by: kustomize
  name: wireguardclient-editor-role
rules:
- apiGroups:
  - core.thecluster.io
  resources:
  - wireguardclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.thecluster.io
  resources:
  - wireguardclients/status
  verbs:
  - get
