apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero-system
spec:
  interval: 10m
  releaseName: velero
  targetNamespace: velero-system
  chart:
    spec:
      chart: velero
      version: 10.1.3
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
  # https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml
  values:
    image:
      repository: velero/velero # default
      tag: v1.17.0
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.13.0
        volumeMounts:
          - mountPath: /target
            name: plugins
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 128Mi
    upgradeJobResources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    podSecurityContext:
      fsGroup: 1337
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      readOnlyRootFilesystem: true
    configuration:
      backupStorageLocation: []
      volumeSnapshotLocation: []
