// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3
{

    /// <summary>
    /// TalosControlPlaneSpec defines the desired state of TalosControlPlane
    /// </summary>
    [OutputType]
    public sealed class TalosControlPlaneSpec
    {
        /// <summary>
        /// ControlPlaneConfig is a two TalosConfigSpecs to use for initializing and joining machines to the control plane.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecControlPlaneConfig ControlPlaneConfig;
        /// <summary>
        /// InfrastructureTemplate is a required reference to a custom resource offered by an infrastructure provider.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecInfrastructureTemplate InfrastructureTemplate;
        /// <summary>
        /// Number of desired machines. Defaults to 1. When stacked etcd is used only odd numbers are permitted, as per [etcd best practice](https://etcd.io/docs/v3.3.12/faq/#why-an-odd-number-of-cluster-members). This is a pointer to distinguish between explicit zero and not specified.
        /// </summary>
        public readonly int Replicas;
        /// <summary>
        /// The RolloutStrategy to use to replace control plane machines with new ones.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecRolloutStrategy RolloutStrategy;
        /// <summary>
        /// Version defines the desired Kubernetes version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private TalosControlPlaneSpec(
            Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecControlPlaneConfig controlPlaneConfig,

            Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecInfrastructureTemplate infrastructureTemplate,

            int replicas,

            Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecRolloutStrategy rolloutStrategy,

            string version)
        {
            ControlPlaneConfig = controlPlaneConfig;
            InfrastructureTemplate = infrastructureTemplate;
            Replicas = replicas;
            RolloutStrategy = rolloutStrategy;
            Version = version;
        }
    }
}
