// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3
{

    /// <summary>
    /// Deprecated: starting from cacppt v0.4.0 provider doesn't use init configs.
    /// </summary>
    [OutputType]
    public sealed class TalosControlPlaneSpecControlPlaneConfigInit
    {
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecControlPlaneConfigInitConfigPatches> ConfigPatches;
        public readonly string Data;
        public readonly string GenerateType;
        /// <summary>
        /// Set hostname in the machine configuration to some value.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecControlPlaneConfigInitHostname Hostname;
        public readonly string TalosVersion;

        [OutputConstructor]
        private TalosControlPlaneSpecControlPlaneConfigInit(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecControlPlaneConfigInitConfigPatches> configPatches,

            string data,

            string generateType,

            Pulumi.Kubernetes.Types.Outputs.Controlplane.V1Alpha3.TalosControlPlaneSpecControlPlaneConfigInitHostname hostname,

            string talosVersion)
        {
            ConfigPatches = configPatches;
            Data = data;
            GenerateType = generateType;
            Hostname = hostname;
            TalosVersion = talosVersion;
        }
    }
}
