---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-credentials
  namespace: bitwarden
spec:
  encryptedData:
    password: AgB2IagoF4eizwq1lLDbce2jIXRp1SJ8hKpHAhCDlX7jU34yfF+XR61Y6fU+eY0Ebjo2qgsu9PRj0+GvX0VEFE0440ABgHd+IfmcppQPgawGEX2pzFdjCcIuukRbRKpshMhjwn+lOpoZA6kSsdPVJOAXTl9qkAF7q3jzjzOB/xEpHb+Fjm/e0YSRc0xdzeLLheFpS09RdvjeqdejWTKKCy1JwS9br4aCTNyMFmZwxHZVIuixU/n9aOd+FvjfgKxTB3goDxX2VGUOuoViI6tlpYMqEvE/dQQ8SNCqLNZH9N5Bdjw981e0CHRasipXM6Bt/eTJ0eLLJGiDnZHLrrDztCBtHk7M84FV3Gkad8tJPPGzxSgOuTSvtYPf/i3+IOOmqBSIRRW8yuQqxeNbv32qcGs2fPbfRpqoOS/bzHIAF9qBgW76Geva4lgAJQN6fR/qWscXcCd1WMMAd6vnHgU2ZejrFZr5OCF2GpdWOkG67nE07Mzyidn0hkN+GNeg5qiLjvHBtpiRuBus2HCU5qbP0ZCRQ8xO2y+xrJf/sHxppelWsOKjsKb200K1GYvDC+SPwk4qZ23X2MPNnKhMTA4qixddAY1uyjHFMzVBQTE2IQRhED/uP0jtOU+zai9m6v2HEICOoaVNxjwl8rjm+ZkbbDA+26/9jyvxS/6lVDSrU3eLU5om0xpOKv17e00MQPtxzPIROU7Fd7l7Zy8+vrrQ2X9477wvddyxwACHx3ljUZEIPg==
    username: AgCDO1iaK7flae65Ftmtt4HaNBEkAa0Ql84vWTZhJ4M+Z/d492MyRGOyz3pl5k1TW/KnzqEQtCDHu073X68CG8kbSnCUc/AuTWzHcW6eOGldB7u9oB5GxpZzBkBMjdpIJK6UlIfNfmI8fUOWHvgTLaNzRXz/TBrsyl2akoXuL4S5QBgiOPdr7gUJgfDGbUo2OQfgVa3nMscrEvfXl0Nvf2QO73DwjP6yozwhjCgIvOQP3S1VTXq61emgZ5nDvhg4h+95dhrD68AOLmqo6bF04zwK1MZC+oovneB0mo7/LBPHfXgKf3sfLXiwL113CNHif2a1b2j51uhmDEjL8sKTAYO0EBHSNSCmp/VDaaZlq4vZSpkdEbEzSOrA3+EjtkzVET1AQxLkWu7/6+qlDrMvRkJ91cF5lwFVFECInJ4SdKe6VNI1ytC6BKw+NWYN8epZmN9Z9m0iI44AtOH60mi0W7oHIqu/1VZ5udIaVtp98JJL3fR5ZdqVp63Sa3UMrIdbIOHYEpZX/O4izluEs/ZOAdG8S5dzbnK8Bc6zD0cIDdhRbcja7xc2JoYXI+rjYH28omOLwqm9JNIUVbNadzXV3xlfi2aCm8qB4dDP+drtzmZt5vh7i5PdJ7JVrsTmcS07cT4sGiKajWSqtmD4O2UuJT96QbK0Q4v8dm1ofaGtTkHUxSLdtPWNWhapSmhRhpIehz6a6/4uEaSczeM=
  template:
    metadata:
      name: pg-credentials
      namespace: bitwarden
    type: Opaque
