name: Setup Rosequartz Deploy
description: Setup the environment for deploying to Rosequartz
inputs:
  tf-workspace:
    description: The terraform workspace to retrieve config from
    required: true
  talosconfig:
    description: Path to the talosconfig file
    required: true
  kubeconfig:
    description: Path to the kubeconfig file
    required: true
runs:
  using: composite
  steps:
    - name: Write configuration files
      working-directory: clusters/rosequartz
      shell: bash
      run: |
        talosconfig="${{ inputs.talosconfig }}"
        kubeconfig="${{ inputs.kubeconfig }}"
        mkdir -p "$(dirname "$talosconfig")"
        mkdir -p "$(dirname "$kubeconfig")"
        terraform init -lockfile=readonly
        terraform output -raw talosconfig > "${{ inputs.talosconfig }}"
        terraform output -raw kubeconfig > "${{ inputs.kubeconfig }}"
        echo "TALOSCONFIG=$(realpath "$talosconfig")" >> "$GITHUB_ENV"
        echo "KUBECONFIG=$(realpath "$kubeconfig")" >> "$GITHUB_ENV"
      env:
        TF_WORKSPACE: ${{ inputs.tf-workspace }}
