apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nginx-gateway-fabric
  namespace: nginx-gateway
spec:
  url: oci://ghcr.io/nginx/charts/nginx-gateway-fabric
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.5.1
