apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-cert-manager
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/cert-manager
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: infra-cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-cloudflare-operator
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/cloudflare-operator-system
  interval: 10m
  prune: true
  dependsOn:
    - name: infra-cloudflare-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-cloudflare
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/cloudflare-system
  interval: 10m
  prune: true
  dependsOn:
    - name: infra-cloudflare
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-coredns
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/coredns-system
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: infra-configs-cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-metallb
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/metallb-system
  interval: 10m
  prune: true
  dependsOn:
    - name: infra-metallb
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-kube-system
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/kube-system
  interval: 10m
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-default
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/default
  interval: 10m
  prune: true
  dependsOn:
    - name: infra-configs-cloudflare-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs-nginx-gateway
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/configs/nginx-gateway
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: infra-configs-cert-manager
