apiVersion: v2
name: minio-operator
description: Minio Operator install for THECLUSTER
type: application
version: 0.1.0
dependencies:
  - name: operator
    repository: https://operator.min.io
    version: 5.0.11
