apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: xmage
spec:
  storageClassName: unsafe-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
