apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: necesse
  namespace: necesse
spec:
  storageClassName: ssd-rbd
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
