---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: necesse
  namespace: necesse
spec:
  encryptedData:
    password: AgBdfPGck8tAFjrFS0lmvnHpBIVXzRB0JpX6svBw26WsnnOqIFQrOXNGKmeJVFAcKTpYCzlp2YJ5+NbtWvIa8UO2znd2ekKoS6jRh2ENm97Km3BSHfpzAqQwcKBOtZ7QWbxuuwqmC4ekjQU0zwRfMqzm84tQH/NsVPlI7nWZuEAP25HI4b7mgMfK4kP14OsHXK/jJB2UqkMSLAgDJgWkxoLg952q8NR6jgF3WzqIlrglboVnYwSrxkm1ib2ykrxkxnG+uUJNIKozk1yIa/lNERRvcDhq8mFtfjxQeJdo9VsM/Y10esskD4fHX1LpO1CSoEaPXttvcE8ERKqjlPh9xp2zH0jeFlrKTZXQImy0O/lbUjeJ0CJLfoq17kQo0T1jjoKh0jfGdIX/kU+WqTQ9afGvgGYE1d9//4uWWM4TzbXxX9MFFIvK05flX6Dk127I/R1bvQHyhuKsrUBNMGG1KdYZMly6+BIleO311EI0yz+xN83KNwymQ2Mq8WAIvtziBep5xMMQKibLkx/sf1ndiYcbfbgxWhLG9+D5lklWzWA6XCJwt+QMyNhP9an7d/RXDxsEsa/T+/WVKISlQnFq35xglMoRxM1Xi4Js+mRaglEtTK21ZMvtZlD57d5j5mxj58rSohgRdploNDhcMWy4gWqj0gor5N5/t12t2BCR+kTWV7rjqa73aF3eedbafL4TGFgea6x8wUXdR7Y=
  template:
    metadata:
      name: necesse
      namespace: necesse
    type: Opaque
