apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-downloads
  namespace: media
spec:
  storageClassName: ec-cephfs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Ti
