apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slackerworld
  namespace: slackerworld
spec:
  storageClassName: unsafe-rbd
  volumeName: pvc-5f4277c3-1cbe-4152-a94b-fce965d8902d
  resources:
    requests:
      storage: 24Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
