apiVersion: v1
kind: Service
metadata:
  name: slackerworld
  namespace: slackerworld
  labels:
    app.kubernetes.io/name: slackerworld
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: slackerworld
  ports:
    - name: server
      port: 8211
      targetPort: 8211
      protocol: UDP
    - name: query
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: rest
      port: 8212
      targetPort: 8212
      protocol: UDP
