version: '3'
name: thecluster
services:
  devcontainer:
    build:
      dockerfile: Dockerfile.archlinux
      context: .
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"

  talos-controlplane:
    ports: []
    networks:
      default:
        ipv4_address: '10.6.0.2'

networks:
  default:
    labels:
      talos.cluster.name: rosequartz
      talos.owned: false
    ipam:
      driver: default
      config:
        - subnet: 10.6.0.0/24
