config:
  thecluster-stacks:stacks:
    pinkdiamond:
      type: cluster
      commit: 1dcad3691b0aff896deefbcafa28028870d06746 # renovate depName=UnstoppableMango/the-cluster tag=2.0.11 extractVersion=^pinkdiamond\/v(?<version>\d+\.\d+\.\d+)
    actions-runner-controller:
      type: app
      commit: ff25e2043877cd312577cdbe6bcf6d1111eab8e0 # renovate depName=UnstoppableMango/the-cluster tag=0.1.0 extractVersion=^actions-runner-controller\/v(?<version>\d+\.\d+\.\d+)
#      dependsOn:
#        - ceph-csi
