name: thecluster-stacks
description: THECLUSTER Pulumi stacks
runtime:
  name: nodejs
  options:
    packagemanager: yarn
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
  versions:
    value:
      # renovate: datasource=docker depName=pulumi/pulumi
      pulumiImage: 3.187.0-nonroot
