---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-operator-credentials
  namespace: cloudflare-system
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgC8LDFdp8YaP5/Ru/C3jMxshnHQxsdhmfJSywqH7tYOOuSL+z2hDeKKoumHV54Mmf2ewfGhDiZgoUoqMsxJ1kT6HEu855Lx144xfPAKAgfeu54C3wauSKWuxUMGcvDzKUvsEAswfej/0w8ckj5f6YuxKVOg+MMuGzaHgSXlgiv7KjB7WS4tmHrAPJpztNVRjoN0SdEhoLQsCZPkgeQCNWzdtbJ4o8DxkbDYU1p7nTX+4ZTwCwSYr81qAMTaBqzmkzdIQDnTkQUiiYqiRxkfHjjV8IxRzYQkueKk8zAkF0RQd9C5I1ATKrY4GK1bck6t1hvGs9NXdPIV0OycgUQf/S1cVIua9GMtXCqji0+TopUGnBMEQsTN3cjBQ5B3DKnP+PvGVXYhne55yrrGeksfdxO1WqL8nbmtj3gzKB2LcMUp7BpIZSnZXwiNEsds8t74UT+A17ejVLM+3QFWgzMdnNXOdSlJ5CcZvpbz6y608Nu1t9T8uDNcsxEhZxVjt0kuIGTSRp4HXGLtU+EHqTQMwTSrcsCTdeJ7f3SLSy32QrbwwiDjv8tnL/iDJUhH94lQi2P2IWJnuPJL6opMKLGGT1NQOBtRaLZeHgKYmHiFOKK/RAsAihnIh6hrDP7jIy4UNhPvFF4CVxHkdqPbaHyHGBwHPbiVek39BsLZwtDyVEBxdQKEMu+h7ZfwHK3qOcQiD3l9dYGNsTsS4MUb+6Sy+N3x2MskexPLDs0KoenLghiP2mBzSEtZrpxQvry84VdGmDVQXpjVVA==
  template:
    metadata:
      name: cloudflare-operator-credentials
      namespace: cloudflare-system
    type: Opaque
