---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-operator-credentials
  namespace: cloudflare-system
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgA2PLsbA+0EUr2pyojZt5NA4twEO6CSGu+kiN7YKdqzzPCzZCHAIpjkIvwyj5YLwMn/vDBm7tQGe/FS7yJQQcwuvUwYxd3QHUbL71rUM6RZst05t981AqlUuAo2+ieYc1cG+Eb0+b/Fd1O8D/zG3DnniSjfjZBC/gmoRsE67HGh8kujJ/B3FQ4s9pg8HnKICxa1uOTfFwEAaYE82aejR3sUcVkyTrc4DFzDStLS7ryVnu+Ejr6WlkpcrA/AjhzIFj9fGE0IOZv6NYfZOe5s5ehV2q1mHgPhrmFJoy5orF/P5a5LGdax1Y/1/veI/dF6sZ007KUx75dq7WQHQlDVwopBnvnedouUJCWL2cJFRel10PjsH5CcvOjZR60PadT/r8UwaD0s0evhhZoiHftFmoyHg9N5AM7kbPGxAvM863uC9Sz/KidlxkFawf8c2sdHGMxb6NzhyoOGQnt9ftsY+uf+KimUXRoSXQpFRFomQTjOzd+1y0z54Fs2Xyj6zHAjWwGdmMg2ECMTOPNYmeA/EiETrgheGnSUBu/zS3cH6pM+1+179rRVwj+biQzd7Zh8VyhHejrKX4fiKuWUPKjondcy+HwjNhH7JvP++Y+RthwAytttwSnNseKg+642/Tb+PotEKkTwm5FNfzBthqv8jwb7O0uaZkCUSJbajc7yfgAEgJ0wKHUUIjSGm1ffTyEx9Eo=
  template:
    metadata:
      name: cloudflare-operator-credentials
      namespace: cloudflare-system
