---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-operator-credentials
  namespace: cloudflare-system
spec:
  encryptedData:
    CLOUDFLARE_API_TOKEN: AgASguQc2fVQjLBtLqxnrpPjd6FrkhX6T+xSaBW9E5l8Gub5qzfTXww+2HJMvd0rIy2fxNbsl9jc9OYE67LeiJPZyWjmrOq3rN1hk2srXSdByMDudkSA9o11TpE63kqxfxranD7Y+5UySurNJ4JSvQNMCtP1JC7o9F5PryPEB3gz3Qg8qE/0Y5ll7RyG8mp2kFsV2bObhE5st7eBzAb1KVymnDsCJLUK1/1o9UCu0NJqQhFaUSmAYamtnRfepMWtPfCwrpJi6zCoVPpOXWYV1E+dJRKGKiNk/w2y2cFQWToSvQbllMa5F1/1fZW46MMrwBRn56SHQ6TOAqwuXhMDYuBnF2ypdubFkqPpRv218F08SpD4qH00uExkgkWyHMyEaMaXdGp7j11Hpkmko8MHbNjY14U3YRKxNV/kacP9/dRcIZGZxh2PdnW//7qp2oLz5Aq9te7gXKMJ5Bah0pVVc2sp0UmMyZZ3+NY2OV4lBBFU4Ms/t7165qgrgsAD6dpI1cym6byLDPj1wyMwzZsNiR7vJAPUIR33wMVRVDtIBmSGGcFkllJuy/PV2f4iz+R6/JcrO9xGJE0xf2cnc0tZ3Xz7Uz31f497faehTzrRc7LXL5tIEiqPtl2VEVNESYCE1jHp/fjn1mGS0VXy+szocLl9ylD/qS6ImlV9uATcwldNwF+YTYzpRo9qalQt7W8tH/TJ0WWZtKh2JBF2q2eOT62qVZ46PovpyIw8FmyNafba9rftVkVUhO2TNO+KxAQ+U640ITYRLQ==
  template:
    metadata:
      name: cloudflare-operator-credentials
      namespace: cloudflare-system
    type: Opaque
