apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-90892cbe-f0e7-4a26-82be-952324a31055
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: unsafe-rbd
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-palworld-0
    namespace: palworld
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000003-ec1b474f-0551-4671-8948-cf1c27603669
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      pool: unsafe-metadata
      dataPool: unsafe-data
      journalPool: unsafe-metadata
      imageName: csi-vol-ec1b474f-0551-4671-8948-cf1c27603669
      imageFeatures: layering
      imageFormat: "2"
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
