---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: palworld
  namespace: palworld
spec:
  encryptedData:
    adminPassword: AgALZrIu/lbb17C9v0ODu1y0M5c0v4SgT0CvmYmOuxs2WlPHDKxSh6FzuJ6JOHqckFk+eQyevsvmX3rdqr1pI+2w1iUDU8OpxKZq65TGGJ0I7IeWf3YEejtMO3MSyunEKLN5gSZP3/c9U6GD00OZc6ZqT8rsUjL29PB0rfKThNGJruRClRUs0CBzyFO8TsAbrPnV9Bp7rQDxD0tIN/l74ztUqxgbNXMmV5bUbpXr1tLCAbHvarEuP9Yrg3IY/jVTQLIVtI4xx0QGMSj97rM0/b4jSFBU9TfLpezN4SpV+TUBzju5WNVFt/JmndaAmMZKpg6LgNjkL8STAutNo3Cbv6/JrPDykSsgB+9sLJ5YHUddvEJ49qUsu3rCmjMwGRxjP8tNXCeV0eXE/bP0R2u4PKzmdvWXtPbSk7CnmrCCO/7dLH21S0EyfC4pcgwcH3APss9knL2qUXEjQTOtA8bsvn0RNx7cn0i8h8TU+EhbpKPu6wGIYaK5nl2nBFsnx4BeDQ3IryqS1EidJifa9OD6yRUd5ga0j8//CmDO3sHDE1XN30yThGPI+zzUB7KoNPjXF+1gHod9TtYVNcUuaFMAvTOC7iol59ejjaPqioBlGd0HNLbc+dIK6FZrmu05fV4Ze8XF+VEqNKCve9XFbMw2+8kVdCjDyXfc1qN9k9VsgtNCEml+coYVJQBlAexuQf8a5F26kd3bMnpEySm2W91MF7XjtkrjfmXj/VeJtp1D3OrkQv7XlAKmTIWhB44uit5iTIg=
  template:
    metadata:
      name: palworld
      namespace: palworld
    type: Opaque
