// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8s.V1
{

    /// <summary>
    /// ExternalEndpoint defines the IP/ Hostname and ports used to connect to this resource.
    /// </summary>
    [OutputType]
    public sealed class VirtualServerStatusExternalEndpoints
    {
        public readonly string Hostname;
        public readonly string Ip;
        public readonly string Ports;

        [OutputConstructor]
        private VirtualServerStatusExternalEndpoints(
            string hostname,

            string ip,

            string ports)
        {
            Hostname = hostname;
            Ip = ip;
            Ports = ports;
        }
    }
}
