// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Alpha1
{

    /// <summary>
    /// DeploymentOptions is a shared type used on objects to indicate that their configuration results in a Deployment which is managed by the Operator and includes options for managing Deployments such as the the number of replicas or pod options like container image and resource requirements. version, as well as Env variable overrides.
    /// </summary>
    [OutputType]
    public sealed class ControlPlaneSpecDeployment
    {
        /// <summary>
        /// PodTemplateSpec defines PodTemplateSpec for Deployment's pods.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Alpha1.ControlPlaneSpecDeploymentPodTemplateSpec PodTemplateSpec;
        /// <summary>
        /// Replicas describes the number of desired pods. This is a pointer to distinguish between explicit zero and not specified. This only affects the DataPlane deployments for now, for more details on ControlPlane scaling please see https://github.com/Kong/gateway-operator/issues/736.
        /// </summary>
        public readonly int Replicas;

        [OutputConstructor]
        private ControlPlaneSpecDeployment(
            Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Alpha1.ControlPlaneSpecDeploymentPodTemplateSpec podTemplateSpec,

            int replicas)
        {
            PodTemplateSpec = podTemplateSpec;
            Replicas = replicas;
        }
    }
}
