// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Gateway.V1Beta1
{

    /// <summary>
    /// ReferenceGrantTo describes what Kinds are allowed as targets of the references.
    /// </summary>
    [OutputType]
    public sealed class ReferenceGrantSpecTo
    {
        /// <summary>
        /// Group is the group of the referent. When empty, the Kubernetes core API group is inferred. 
        ///  Support: Core
        /// </summary>
        public readonly string Group;
        /// <summary>
        /// Kind is the kind of the referent. Although implementations may support additional resources, the following types are part of the "Core" support level for this field: 
        ///  * Secret when used to permit a SecretObjectReference * Service when used to permit a BackendObjectReference
        /// </summary>
        public readonly string Kind;
        /// <summary>
        /// Name is the name of the referent. When unspecified, this policy refers to all resources of the specified Group and Kind in the local namespace.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ReferenceGrantSpecTo(
            string group,

            string kind,

            string name)
        {
            Group = group;
            Kind = kind;
            Name = name;
        }
    }
}
