apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-605924c3-fe70-4556-a8d0-74cfcf5bcfc9
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-rbd
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pihole-a
    namespace: pihole
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000014-9db5c524-d5f8-443a-87ef-a0dcd58dc0b0
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      pool: default-ssd
      journalPool: default-ssd
      imageName: csi-vol-9db5c524-d5f8-443a-87ef-a0dcd58dc0b0
      imageFeatures: layering
      imageFormat: "2"
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-6465046b-af46-4a89-a586-c219d91a8d82
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOncePod
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-rbd
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pihole-b
    namespace: pihole
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000014-2a313317-dfd1-42e0-b821-ea8c8d7a82ff
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      pool: default-ssd
      journalPool: default-ssd
      imageName: csi-vol-2a313317-dfd1-42e0-b821-ea8c8d7a82ff
      imageFeatures: layering
      imageFormat: "2"
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
