apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcluster
    clusterctl.cluster.x-k8s.io: ""
  name: cluster-api-provider-vcluster-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cluster-api-provider-vcluster-controller-manager
  namespace: cluster-api-provider-vcluster-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcluster
    clusterctl.cluster.x-k8s.io: ""
  name: cluster-api-provider-vcluster-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-api-provider-vcluster-proxy-role
subjects:
- kind: ServiceAccount
  name: cluster-api-provider-vcluster-controller-manager
  namespace: cluster-api-provider-vcluster-system
