apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcluster
    clusterctl.cluster.x-k8s.io: ""
  name: cluster-api-provider-vcluster-leader-election-rolebinding
  namespace: cluster-api-provider-vcluster-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cluster-api-provider-vcluster-leader-election-role
subjects:
- kind: ServiceAccount
  name: cluster-api-provider-vcluster-controller-manager
  namespace: cluster-api-provider-vcluster-system
