apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vcluster
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  name: cluster-api-provider-vcluster-metrics-service
  namespace: cluster-api-provider-vcluster-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
