name: Setup End to End Tests
description: Setup End to End Tests
inputs:
  tf-api-token:
    description: The Terraform API token
    required: true
  stack-id:
    description: The stack identifier for the run
    required: true
runs:
  using: composite
  steps:
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
        cli_config_credentials_token: ${{ inputs.tf-api-token }}
        terraform_wrapper: false

    - uses: pulumi/actions@v4

    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: '**/package-lock.json'

    # TODO: Get a specfic version
    - name: Install talosctl
      run: curl -sL https://talos.dev/install | sh
      shell: bash

    - name: Terraform Init
      working-directory: clusters/rosequartz
      run: terraform init -lockfile=readonly
      env:
        TF_WORKSPACE: rosequartz-ci
      shell: bash

    - name: Setup workspace
      id: setup-workspace
      working-directory: clusters/rosequartz
      run: |
        workspace="rosequartz-${{ inputs.stack-id }}"
        terraform workspace new "$workspace"
        terraform workspace select "$workspace"
        echo "workspace=$workspace" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Create test node
      working-directory: clusters/rosequartz
      run: docker compose -f ci/docker-compose.yaml up -d
      shell: bash
outputs:
  workspace:
    description: The terraform workspace
    value: ${{ steps.setup-workspace.outputs.workspace }}
