---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adventureworld
  namespace: adventureworld
spec:
  encryptedData:
    adminPassword: AgBReDMlnWnpAc1+hJNONA1d13VVYVYQ6MjnNCZ66fYRlIcheQ7mef/5XsOSqHiNustnezWROYu3QFRlV7ETt99eLJDKV1iN60C+GM29rVkJbIGJPSGQwaAlVbXKYlgMoTQYnu4D3yznvBpCPYny88fBkqM3j3b79pn1gkhhnHOwhw/LJ4Ut4r3jIhPtisutyUA3kU5XWutUh19m+UmWP6Y9T2kD5X4CXcYsWoPxS3/BnFepK+4Z0Z0ph2k7rSiHyommdljMOR0y+/tpN8xoOieRTU5haHWKuQLQIrT0v2BU6KQ44wz4HuyS7ylm5i0AhkspTjLQ1TDL88OcFkFutl1WxY/rIA218NF+puWfmQnL3SZcTRsd98ZltGmMrrp9b7rdTRXB3tdkimLp7yTWkhtNQxYdwTVYCthUi7fSwrk8jxwZXuFB6+K9hNwD9MwLt2ujy1H+ERnuXjY+juHFWGWj+AQk/66Wwd64QxNxr3NFUnhTeSkdPiGaLwn9ma5puFFsZJ/dxt4NRFF4pO9dm+L+YAtrhu4nVNW2ZypxuEdCiffovYPDKb1hjM7JfHf4s68cVW/MBi2pToK1ros6KY1eOz6TYo10k77KlrpjKo5306X7IRQyqNGZ+STznMFUMpnFz3Z0ru6zV79hdNiyITJKaTDDCsPjxBo4tCh3Qdj9CUxxI37+5/PCLJacltv0arEOTmfy8CipISdAjDUJdBF0jqEJ61nDoSUmNz/9yqmJsGuAEw90iFmRA6VJjJlaRLk=
    serverPassword: AgBg3WsgEIPthhQdflh9T3GUrzFuVDkOd25BZcrZ0Stz1q9RGv2iPL63fDoECDNm2GanwQCrGAZU920GzRqTd+Tvp0N0yyki3hy+ayCHDSmzapnCmVWp8fBVrwFkl84VPCojkHalwOP3UYR63sjpYIAaVeRRG+V8iwshRkQs+icTfyl6mfdLMkeHyouSGBgdCqbMoMP9YPYwYI4/B2ULwpABWRjd6huQWZZe2RuXow+LwKlYw3+/pGXdl9rSTFLme+LjsvTkFFpCEom5Zb45P6lD22TUM7HIGC1sg/TTbPotA7sfwX92oh8kPHJLLu+vS5ZFYMktJo8SydH/fTpvSsLb/tzwYAmlft2zvKYU54rhA+N7y9vhh2swLZs3qKnRdxQSHOTWItY00zg1+qu88qh/Y4ym5bYOkIBpDIWn7fDk/hW+pXI4pn9bW1zrEoOMJDrsMgAG/80M+vix9nkxrU2RdVUDHsDHZUveLwj4USLTsBY2YL/1ZjWmZQTgho81nV+vNqzHU0mrrI0col/19OyA70UddxOZoI6T8IbS88jJq/EOuBN3SjVlHzIRyNUDW4k1IqSK9OiKwdEcBG+PC22SLk2DPcSdhUDJ8pM8hLVsTkQjUv7tH+a++uE7zIFjqF7XguBh2Q3Q3TgngAUt/7g3og0u3zFCE3JaHrmVYEeKX296/A+HoIwISTj420Ul9ceI//Z/l94zizRJN6BuOzxLPVxlkLTlrl0VJNs=
  template:
    metadata:
      name: adventureworld
      namespace: adventureworld
    type: Opaque
