apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cabpt-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabpt-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cabpt-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cabpt-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabpt-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cabpt-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cabpt-talosconfig-editor-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabpt-talosconfig-editor-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cabpt-system
