apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cabpt-selfsigned-issuer
  namespace: cabpt-system
spec:
  selfSigned: {}
