apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cabpt-leader-election-rolebinding
  namespace: cabpt-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cabpt-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cabpt-system
