// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Infrastructure.V1Beta1
{

    /// <summary>
    /// ServerRef is used for configuring Proxmox client
    /// </summary>
    [OutputType]
    public sealed class ProxmoxClusterSpecServerRef
    {
        /// <summary>
        /// endpoint is the address of the Proxmox-VE REST API endpoint.
        /// </summary>
        public readonly string Endpoint;
        /// <summary>
        /// SecretRef is a reference for secret which contains proxmox login secrets
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Infrastructure.V1Beta1.ProxmoxClusterSpecServerRefSecretRef SecretRef;

        [OutputConstructor]
        private ProxmoxClusterSpecServerRef(
            string endpoint,

            Pulumi.Kubernetes.Types.Outputs.Infrastructure.V1Beta1.ProxmoxClusterSpecServerRefSecretRef secretRef)
        {
            Endpoint = endpoint;
            SecretRef = secretRef;
        }
    }
}
