// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Minio.V2
{

    [OutputType]
    public sealed class TenantSpecSideCarsContainersEnvFrom
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecSideCarsContainersEnvFromConfigMapRef ConfigMapRef;
        public readonly string Prefix;
        public readonly Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecSideCarsContainersEnvFromSecretRef SecretRef;

        [OutputConstructor]
        private TenantSpecSideCarsContainersEnvFrom(
            Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecSideCarsContainersEnvFromConfigMapRef configMapRef,

            string prefix,

            Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecSideCarsContainersEnvFromSecretRef secretRef)
        {
            ConfigMapRef = configMapRef;
            Prefix = prefix;
            SecretRef = secretRef;
        }
    }
}
