// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Minio.V2
{

    [OutputType]
    public sealed class TenantStatusCertificates
    {
        public readonly bool AutoCertEnabled;
        public readonly Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantStatusCertificatesCustomCertificates CustomCertificates;

        [OutputConstructor]
        private TenantStatusCertificates(
            bool autoCertEnabled,

            Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantStatusCertificatesCustomCertificates customCertificates)
        {
            AutoCertEnabled = autoCertEnabled;
            CustomCertificates = customCertificates;
        }
    }
}
