// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Minio.V2
{

    [OutputType]
    public sealed class TenantSpecPoolsAffinity
    {
        public readonly Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecPoolsAffinityNodeAffinity NodeAffinity;
        public readonly Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecPoolsAffinityPodAffinity PodAffinity;
        public readonly Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecPoolsAffinityPodAntiAffinity PodAntiAffinity;

        [OutputConstructor]
        private TenantSpecPoolsAffinity(
            Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecPoolsAffinityNodeAffinity nodeAffinity,

            Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecPoolsAffinityPodAffinity podAffinity,

            Pulumi.Kubernetes.Types.Outputs.Minio.V2.TenantSpecPoolsAffinityPodAntiAffinity podAntiAffinity)
        {
            NodeAffinity = nodeAffinity;
            PodAffinity = podAffinity;
            PodAntiAffinity = podAntiAffinity;
        }
    }
}
