// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Snapshot.V1Beta1
{

    /// <summary>
    /// spec defines the desired characteristics of a snapshot requested by a user. More info: https://kubernetes.io/docs/concepts/storage/volume-snapshots#volumesnapshots Required.
    /// </summary>
    [OutputType]
    public sealed class VolumeSnapshotSpec
    {
        /// <summary>
        /// source specifies where a snapshot will be created from. This field is immutable after creation. Required.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Snapshot.V1Beta1.VolumeSnapshotSpecSource Source;
        /// <summary>
        /// VolumeSnapshotClassName is the name of the VolumeSnapshotClass requested by the VolumeSnapshot. VolumeSnapshotClassName may be left nil to indicate that the default SnapshotClass should be used. A given cluster may have multiple default Volume SnapshotClasses: one default per CSI Driver. If a VolumeSnapshot does not specify a SnapshotClass, VolumeSnapshotSource will be checked to figure out what the associated CSI Driver is, and the default VolumeSnapshotClass associated with that CSI Driver will be used. If more than one VolumeSnapshotClass exist for a given CSI Driver and more than one have been marked as default, CreateSnapshot will fail and generate an event. Empty string is not allowed for this field.
        /// </summary>
        public readonly string VolumeSnapshotClassName;

        [OutputConstructor]
        private VolumeSnapshotSpec(
            Pulumi.Kubernetes.Types.Outputs.Snapshot.V1Beta1.VolumeSnapshotSpecSource source,

            string volumeSnapshotClassName)
        {
            Source = source;
            VolumeSnapshotClassName = volumeSnapshotClassName;
        }
    }
}
