// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Actions.V1Alpha1
{

    /// <summary>
    /// nfs represents an NFS mount on the host that shares a pod's lifetime More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
    /// </summary>
    [OutputType]
    public sealed class AutoscalingRunnerSetSpecTemplateSpecVolumesNfs
    {
        /// <summary>
        /// path that is exported by the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// readOnly here will force the NFS export to be mounted with read-only permissions. Defaults to false. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
        /// </summary>
        public readonly bool ReadOnly;
        /// <summary>
        /// server is the hostname or IP address of the NFS server. More info: https://kubernetes.io/docs/concepts/storage/volumes#nfs
        /// </summary>
        public readonly string Server;

        [OutputConstructor]
        private AutoscalingRunnerSetSpecTemplateSpecVolumesNfs(
            string path,

            bool readOnly,

            string server)
        {
            Path = path;
            ReadOnly = readOnly;
            Server = server;
        }
    }
}
