// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Actions.V1Alpha1
{

    /// <summary>
    /// May contain labels and annotations that will be copied into the PVC when creating it. No other fields are allowed and will be rejected during validation.
    /// </summary>
    [OutputType]
    public sealed class AutoscalingRunnerSetSpecTemplateSpecVolumesEphemeralVolumeClaimTemplateMetadata
    {
        public readonly ImmutableDictionary<string, string> Annotations;
        public readonly ImmutableArray<string> Finalizers;
        public readonly ImmutableDictionary<string, string> Labels;
        public readonly string Name;
        public readonly string Namespace;

        [OutputConstructor]
        private AutoscalingRunnerSetSpecTemplateSpecVolumesEphemeralVolumeClaimTemplateMetadata(
            ImmutableDictionary<string, string> annotations,

            ImmutableArray<string> finalizers,

            ImmutableDictionary<string, string> labels,

            string name,

            string @namespace)
        {
            Annotations = annotations;
            Finalizers = finalizers;
            Labels = labels;
            Name = name;
            Namespace = @namespace;
        }
    }
}
