apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nats
  namespace: nats-system
spec:
  interval: 10m
  releaseName: nats
  targetNamespace: nats-system
  chart:
    spec:
      chart: nats
      version: 1.3.13
      sourceRef:
        kind: HelmRepository
        name: nats
  # https://github.com/nats-io/k8s/blob/main/helm/charts/nats/values.yaml
  values:
    config:
      nats:
        port: 4222 # default
      websocket:
        enabled: true
        port: 8080 # default
        ingress:
          enabled: true
          hosts: [nats.thecluster.lan]
          className: nginx
    container:
      image:
        repository: nats # default
        tag: 2.11.8-linux
    reloader:
      image:
        repository: natsio/nats-server-config-reloader # default
        tag: 0.19.2
    service:
      ports:
        nats:
          enabled: true # default
        leafnodes:
          enabled: true # default
        websocket:
          enabled: true # default
        mqtt:
          enabled: false
        cluster:
          enabled: false # default
        gateway:
          enabled: false # default
        monitor:
          enabled: false # default
        profiling:
          enabled: false # default
    natsBox:
      container:
        image:
          repository: natsio/nats-box # default
          tag: 0.18.1
    podTemplate:
      merge:
        spec:
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - gaea
