// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1
{

    /// <summary>
    /// Cluster network configuration.
    /// </summary>
    [OutputType]
    public sealed class ClusterSpecClusterNetwork
    {
        /// <summary>
        /// APIServerPort specifies the port the API Server should bind to. Defaults to 6443.
        /// </summary>
        public readonly int ApiServerPort;
        /// <summary>
        /// The network ranges from which Pod networks are allocated.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterSpecClusterNetworkPods Pods;
        /// <summary>
        /// Domain name for services.
        /// </summary>
        public readonly string ServiceDomain;
        /// <summary>
        /// The network ranges from which service VIPs are allocated.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterSpecClusterNetworkServices Services;

        [OutputConstructor]
        private ClusterSpecClusterNetwork(
            int apiServerPort,

            Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterSpecClusterNetworkPods pods,

            string serviceDomain,

            Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterSpecClusterNetworkServices services)
        {
            ApiServerPort = apiServerPort;
            Pods = pods;
            ServiceDomain = serviceDomain;
            Services = services;
        }
    }
}
