// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1
{

    /// <summary>
    /// The deployment strategy to use to replace existing machines with new ones.
    /// </summary>
    [OutputType]
    public sealed class ClusterSpecTopologyWorkersMachineDeploymentsStrategy
    {
        /// <summary>
        /// Rolling update config params. Present only if MachineDeploymentStrategyType = RollingUpdate.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterSpecTopologyWorkersMachineDeploymentsStrategyRollingUpdate RollingUpdate;
        /// <summary>
        /// Type of deployment. Allowed values are RollingUpdate and OnDelete. The default is RollingUpdate.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private ClusterSpecTopologyWorkersMachineDeploymentsStrategy(
            Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterSpecTopologyWorkersMachineDeploymentsStrategyRollingUpdate rollingUpdate,

            string type)
        {
            RollingUpdate = rollingUpdate;
            Type = type;
        }
    }
}
