// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1
{

    /// <summary>
    /// ClusterClassStatusVariable defines a variable which appears in the status of a ClusterClass.
    /// </summary>
    [OutputType]
    public sealed class ClusterClassStatusVariables
    {
        /// <summary>
        /// Definitions is a list of definitions for a variable.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterClassStatusVariablesDefinitions> Definitions;
        /// <summary>
        /// DefinitionsConflict specifies whether or not there are conflicting definitions for a single variable name.
        /// </summary>
        public readonly bool DefinitionsConflict;
        /// <summary>
        /// Name is the name of the variable.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private ClusterClassStatusVariables(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Cluster.V1Beta1.ClusterClassStatusVariablesDefinitions> definitions,

            bool definitionsConflict,

            string name)
        {
            Definitions = definitions;
            DefinitionsConflict = definitionsConflict;
            Name = name;
        }
    }
}
