apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 10m
  releaseName: headlamp
  targetNamespace: kube-system
  chart:
    spec:
      chart: headlamp
      version: 0.34.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  # https://github.com/kubernetes-sigs/headlamp/blob/main/charts/headlamp/values.yaml
  values:
    image:
      registry: ghcr.io # default
      repository: headlamp-k8s/headlamp # default
      # renovate: datasource=docker depName=ghcr.io/headlamp-k8s/headlamp
      tag: v0.34.0
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: headlamp.thecluster.lan
          paths:
            - type: Prefix
              path: /
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 512Mi
    # https://github.com/headlamp-k8s/plugins/tree/main/flux#readme
    config:
      pluginsDir: /build/plugins
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/ && chown -R 100:101 /build
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        securityContext:
          runAsNonRoot: false
          privileged: false
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
