apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 10m
  releaseName: metrics-server
  targetNamespace: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: 3.12.1
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  values:
    image:
      repository: registry.k8s.io/metrics-server/metrics-server
      tag: 0.8.0
