name: thecluster-migrate
description: Whatever crap I decide I need for migrating data
runtime:
  name: nodejs
  options:
    packagemanager: yarn
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
  versions:
    value: {}
