// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8s.V1Alpha1
{

    /// <summary>
    /// JWTAuth holds JWT authentication configuration.
    /// </summary>
    [OutputType]
    public sealed class PolicySpecJwt
    {
        public readonly string Realm;
        public readonly string Secret;
        public readonly string Token;

        [OutputConstructor]
        private PolicySpecJwt(
            string realm,

            string secret,

            string token)
        {
            Realm = realm;
            Secret = secret;
            Token = token;
        }
    }
}
