// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.K8s.V1Alpha1
{

    /// <summary>
    /// TransportServerListener defines a listener for a TransportServer.
    /// </summary>
    [OutputType]
    public sealed class TransportServerSpecListener
    {
        public readonly string Name;
        public readonly string Protocol;

        [OutputConstructor]
        private TransportServerSpecListener(
            string name,

            string protocol)
        {
            Name = name;
            Protocol = protocol;
        }
    }
}
