---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    api-token: AgAIx6NtDt3XM32/THxih9guHhE2qlUcRZEeG8ITsDURCkdAwgjJwUiKtM7Hb48ZmsfuqaoWSQq0M0/J7s70SX4d31R1XQiK5Js31EuuBRYa9OGoR68IRB5rnDnbqM5u9bRCJeC3/a+mfNgEOhERQrmxy0YaESMSVVdU86If5dRrl0Qa8ntLaeIkwgyUkjNGlkopt4IRTbwUb0AX5I1+FLBIJmAVcRXjVynAgDI/UUXOJZUmCDUzJLQiU89ejJu1s/JXQsYKp8hqDjoa//sCQEilEz3l9fe35eSYBPCwbn7qwU+AbfdfB7ZNld/S5jhAEHXkB4491SUmN8oXLc0hi76E9hADIEPxp8IJvzHVErSfj/rXXY8qtNZxJdWcIxYsMWHhqROaWaT/u68NeXR38jFsJZf5uFJwtkmuVF1uwcRuMJ8SK9Eekzpo9TAw0f00U9W1Ezw1UDdEOfXLLzfyNn1qnBLHIhpNKNu4uvvDutH5PltMdwlNN97krC4ruVy4EatW7kP9Peysjn8rPaPlkC97lQmiRxbWDmN3Iv7UDRjg+l+MiXaxMrX5emeccB687OCHu0hp+YGXPn0ze9o8EqEa7eZVb/9BMxdIEIJGORfmIrDBnVKAMUstepvedcB6oXjX2fvNc/RBlYFoM3SsAhH59ikErmLRRwKKBGso14/NpASMfY3lDaVfMFicYZ1Bdzr0fcPhfTxSAIB+5I/VWrDJfkLhjSfySM79chPlwMQieB98/+558q3+
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: cloudflare-operator-system
