---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    CLOUDFLARE_ACCOUNT_ID: AgCRqnCHWaYic4QPvp8fbnvU5SSNyRcCyP62o0hg60eKnmaFYnM7jwEpn7ieO5oygD+zvzK9RfVTKj9yGM+ffaC6acgSossa3iyNbB+D8W8n/7xQK4/+3J4UN/IXhsR8URc9KrE74QFbIA9DiyTMHCDjOoigHZ4JGrsFG8hZ5Tzjul8kAPXX5C1Xaqee7Se4++6+FkZ5FoDLYksROuEXqnmMuGVkckfv4sk/fuyqcjUPz7CafYGHFWYUGBpzLwsQj1v0YaDspXTqkZ7uc5naPU65/4/w52bOQbDsDFKaZ0dRABJ65NcvqlF3jo/2AGh/YQHcTtaYq0ybuhYQKohZd/zlxiJsGfhfsgHRo97+CAH1Cxdk4HIA41/vgs9e13/zkix0KwTRaWUrJj84F57dUPnwVxgmjyFkokz57Yrx9XLgthw7QnfLECFjjQ5WSTDWfaqEIMBBH83YH7oGcp0hSZF53eFQ/9ogkzKoU03UiTsYN6Bk0NOh07ssotM16ZEAypDKkIAPkAm6lnrXF7oZ8YwkcPDDq5LjgDrqCyDmeeDD2fwZyreRxihequhIx7JDsVzPma0NJxj7mlqE9i+u7ot8kdtUlJPVVE4NsUhB5AFQQp9lZN3Uk/yga4BlBoz1dMdcADDnOCL51e8lPQlAJtzs9NDxgB0VNH8FgJlUqvGreoM3msbA16gaaM7naQSC4Pr5qaejHuH2DJD6DJ7cwoDK5Pe923PpMPbJynxq+UVtSg==
    CLOUDFLARE_API_TOKEN: AgABnHc9V5kY1YnWNq2s5dF7IFnTzyGbOqWUFd90o9FopmUS9tXKYFqZ90ovh+RTCMU83vPexIIC7A7zLJx00xriIm+3BJeblZGuK+MvIp9xhIfYp4fzWUCPNTAPXsEG45tX/2X4iwgug0vQWsri7fcQfcl4femCizAIy8BT1mNOKybcAKBJuwSrAtxiqnN0UenkIyCz9fgW18BbByZ+K/rNnK50ohHIgUccENxaVgfGw2IvFkTiCnOIlZNr1ys9OFLQhdfM/FXmw/OLCINgbf4+ie8Bs1Wnp365YfHdxlviT7LRy7UMbLTGFgwxwVwlCt2faimN4Q/nlX+bDq9GDBLoG16DLa+7C874G7okbVkekCSCmROE7K5bvK2Ipt9fJZqI9W/DgNn9pvmpge7yUnFAYGtJRql9Ev568dD/3mWStPBFo8t67YHM7WKZZKKDgpsNRPzDx75d+iCNNLeiWFnWFPML7ijzuxgAMw/xdKG+vAv/7jdUqEdiYt/LDLpm6szpYws9NmOxm4vEja0kkwUXRyInpcBQ/fzW9oHlpp9jyxGEZaJPPwvmkTVvzU8Vnh058aUXC5DhCjAwlUwUIO7CEN8wLYaGqhwRRBL4MHsn6RaVQLQsTeSqdsFsDe7LLdW9+UbbCuSTRUWfhPNZDKzugCpQdTg6c7Ac42U+zB2jpscNgT34dvtqWCdU2g63W1BawhGgTXyy2o63Yp/tfvaVwBV8zYhcY3wNBTqePMSC/9miKW8gA0uX
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: cloudflare-operator-system
