---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: cloudflare-operator-system
spec:
  encryptedData:
    CLOUDFLARE_ACCOUNT_ID: AgChJeW1xsHtfACiaE2cOxByHjnVq68OFuzzO+OJ8zN3RPz/XWVtyQt8FJ8z4Bq3rDpQX/A1ZuLdMHW3bJ+knHx7oFVDk6P11bGGfqp7Ld+FEY6KYP9AYZl9X9aoLUI+oy44/i6GPSu8v8pyz7B7V5CgrSL2EiQ5kIyo2hbYIwXV3XNSansFQCmzSn39vNXz4vuwD3a5FpKDRAnYU6JSjR+fj3VqG3r8Va9MGCSJXWrTpocTM1mYrmUawC07qYCCfsr4plsFh5EM5NKOGWICsuPLMr9tkHHq+LQC/m4+UH8x3+SLJ14bTcVmtxLCwBNEpbvDLs8prz9lrQZ99aH+OQfKWVz4t3yHeeM7wUy0I+BsJlftp/z0GANZJ9JFslSQQ6vVg8I6syKVduEvr6CZQzDEUq531pTeCIzZz3XUawdVd/e9DwzlhA5altok1x36nuNrB2k6Y3n/DSEFGM9BLlMVwSP8oOXYc2Z83l3TeS9HEaYWuy+217HufMHyvwTBBLZC/VubHmN67wNwMmFjCq6NvGmL5Dg5fCGgDwcD0NbsSf8R8+a+BsCAt/Kg2Dv9MmB7VtdfeMffL2twAccHmQ5bDJFz+GwBXybnBCCxquSsfNy96exezhDINQ/UjpN+A8a7qO27ZTfKqJfuYZzg30BipLYt+MWI6xMukQRkktB4TImt1BBQbiguNTB3rvFKz5jmuxNQHZv43cO28zStwVJYBbm5TsDeSP1Vu8LdTuNbZA==
    CLOUDFLARE_API_TOKEN: AgCjZX8ES2dJ4cWnS2vvAIOq0+5LcqKVEay/uANKp6uGjBXEXpRSfA4WRtbxTJBLfhqK3i5Yihri2c9281vLiuhyqDI2PrtlgC3dqSNcONi5zeJ6nNcS2sRhMkGqUz3SXbyp8b1ppJM18vHjjvMBinezJ8UE4CB818rb5Rqufeu5P9ZVBvAOp5is4cCDyugg90te+yfV+S90hXl8dr7CzV4VglnV04bGg3WiLlznV8iHa9UhAwjcW7aQEXh4gMyQjlbMp1AcnqlRyaUeg5c2mzU0hdfg/fDUT4R7qOUa6hfv+058My6ib+t0+JNIqVEvyqNVoe7dJHl+6nIqtGabDUmokd2pN0cdxCIV7t7vL94VnlpHFrX0+P2myMplC+iO9VVc28aCHHn/R4voA1xQvDzNpKOYx1zKnUhwaHNiGgUpo3vm/hw9q1Rd5QA43DDYr9NTZuHHWAkWiVhhWlNbg9l2OhBj88QGpr0/aOTvGOa/iDSnjVI7nstDx9msPkR930jGPtG9b3cj2NAqGzbWJmF8iOlCm/c/PcSbqR2J+6xgR5nVPXAsUmE6/GyNIjVUrEOOi+AZQJgYyG9OaZ7LtdXDdMj3NDRL1DHWVscUvtgJuJmer2DxTpQQp6N2YVjuhD7PKyyJECxTKd9geCfPoPBaHppbnkcv9lup1AGVutsyNWh2VPZEAXTt/ecHgw0pdAVQTdyhp/RNllq5nJJm7Db+w2D1MjysLTmn4jxQvqXhj4xHeo87RTyw
  template:
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: cloudflare-operator-system
