// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Networking.V1Alpha1
{

    /// <summary>
    /// TunnelBindingSubject defines the subject TunnelBinding connects to the Tunnel
    /// </summary>
    [OutputType]
    public sealed class TunnelBindingSubjects
    {
        /// <summary>
        /// Kind can be Service
        /// </summary>
        public readonly string Kind;
        public readonly string Name;
        public readonly Pulumi.Kubernetes.Types.Outputs.Networking.V1Alpha1.TunnelBindingSubjectsSpec Spec;

        [OutputConstructor]
        private TunnelBindingSubjects(
            string kind,

            string name,

            Pulumi.Kubernetes.Types.Outputs.Networking.V1Alpha1.TunnelBindingSubjectsSpec spec)
        {
            Kind = kind;
            Name = name;
            Spec = spec;
        }
    }
}
