---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: unstoppablemango-hercules-ci-agent
  namespace: hercules-ci
spec:
  encryptedData:
    cluster-join-token.key: AgBSM1lHNvueWneETCpzDyq2gzm6fmXXk+Uxrk4AUHIa3NmmbxVchS05A0fcdz/sRvs+gaic43a2yhDDFbf473QFKIQJmGFOwJIhIEnQGjfjCkhxllbFeUc4PwI70up2webYdaarNc4VN9UnskcIafJIjDq/RqXkhLxTIRmQIwxRu4fw5YB7oTInwvWSk5Xfqn8KWyJ+oFrJAP9UCldp5lI81WOwlCxjHJ9jsdZndmf681zQJ1O6sQno/JoCJ6hadgQA+egWC02eMxR/A7ndlbYITxTg7LkrZqhRESKRzoki07ZggYXBYfQAva+tv0cEVmuuZLK/oPbsz7elwkiz3kC3yvs8Tw38c3mDKtrEKh9XpVUZZoqpfV2bMB0sCBpG5R9xSPfXrrxPZMLzRf3eNriI7a7jcFIt0CJZvZz1bmHhusv1larTTVQBKlKMKNLFetsNIlU6Od1AyxKaUsICiTWrjISTu/doSsSDqJGL4R/yrd2Ts6ffsEpD2AHZGmMMGSkS2kL5A5itsbo8y92peVlb6osPkY9ISyKI8jn1rKw1WdtIzvevP8Ne9L6ybpFnu76WrA1a33hm1+8yD6UKcoebRBfxRNwoo4Is6yrVrOP5ctfvCGY4mRNj1B02qtDVUmV4ei+VhbymZPqyCHCFQKnKKb62UA2x6pQokUVjQXuwqV20yQnoCHbDacDYFh0pF3bkExb8+jEGclPD0McIrUPFGwS+zFcyTif9ex50WDL/O/WAfKsmWQf7hprgMDvBvCVo4neAftbjyy8dhgY263N1y3ubSgkjJddcFx9LOkE9m6kiX4zJ//p2o72JWU3nI3L88Yiq54pXpDKqAbx5Z3yk4bAgV9PquCHsIsEnBKj62udqmgsv9sftQH04b8AV+/FT/Sq0CaoAGdjjHYkdxPFoqGotYiJAIEgwWRBtv42V8aF19bUe0DhQT+dbTn14cJuZ5A9oKzgQomdUEAEabl5V/UoXfnr0IsX2rk43ejg9tpsHHPwKgyEWp4fQ
  template:
    metadata:
      name: unstoppablemango-hercules-ci-agent
      namespace: hercules-ci
    type: Opaque
