// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8s.V1
{

    /// <summary>
    /// PolicySpec is the spec of the Policy resource. The spec includes multiple fields, where each field represents a different policy. Only one policy (field) is allowed.
    /// </summary>
    public class PolicySpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// AccessControl defines an access policy based on the source IP of a request.
        /// </summary>
        [Input("accessControl")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecAccessControlArgs>? AccessControl { get; set; }

        /// <summary>
        /// BasicAuth holds HTTP Basic authentication configuration policy status: preview
        /// </summary>
        [Input("basicAuth")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecBasicAuthArgs>? BasicAuth { get; set; }

        /// <summary>
        /// EgressMTLS defines an Egress MTLS policy.
        /// </summary>
        [Input("egressMTLS")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecEgressMtlsArgs>? EgressMTLS { get; set; }

        [Input("ingressClassName")]
        public Input<string>? IngressClassName { get; set; }

        /// <summary>
        /// IngressMTLS defines an Ingress MTLS policy.
        /// </summary>
        [Input("ingressMTLS")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecIngressMtlsArgs>? IngressMTLS { get; set; }

        /// <summary>
        /// JWTAuth holds JWT authentication configuration.
        /// </summary>
        [Input("jwt")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecJwtArgs>? Jwt { get; set; }

        /// <summary>
        /// OIDC defines an Open ID Connect policy.
        /// </summary>
        [Input("oidc")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecOidcArgs>? Oidc { get; set; }

        /// <summary>
        /// RateLimit defines a rate limit policy.
        /// </summary>
        [Input("rateLimit")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecRateLimitArgs>? RateLimit { get; set; }

        /// <summary>
        /// WAF defines an WAF policy.
        /// </summary>
        [Input("waf")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.PolicySpecWafArgs>? Waf { get; set; }

        public PolicySpecArgs()
        {
        }
        public static new PolicySpecArgs Empty => new PolicySpecArgs();
    }
}
