// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.K8s.V1
{

    /// <summary>
    /// ActionProxy defines a proxy in an Action.
    /// </summary>
    public class VirtualServerRouteSpecSubroutesMatchesActionProxyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ProxyRequestHeaders defines the request headers manipulation in an ActionProxy.
        /// </summary>
        [Input("requestHeaders")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionProxyRequestHeadersArgs>? RequestHeaders { get; set; }

        /// <summary>
        /// ProxyResponseHeaders defines the response headers manipulation in an ActionProxy.
        /// </summary>
        [Input("responseHeaders")]
        public Input<Pulumi.Kubernetes.Types.Inputs.K8s.V1.VirtualServerRouteSpecSubroutesMatchesActionProxyResponseHeadersArgs>? ResponseHeaders { get; set; }

        [Input("rewritePath")]
        public Input<string>? RewritePath { get; set; }

        [Input("upstream")]
        public Input<string>? Upstream { get; set; }

        public VirtualServerRouteSpecSubroutesMatchesActionProxyArgs()
        {
        }
        public static new VirtualServerRouteSpecSubroutesMatchesActionProxyArgs Empty => new VirtualServerRouteSpecSubroutesMatchesActionProxyArgs();
    }
}
