apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: smarter-device-manager
  namespace: smarter-device-manager
spec:
  url: https://smarter-project.github.io/smarter-device-manager
  interval: 30m
