apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smarter-device-manager
  namespace: smarter-device-manager
spec:
  interval: 10m
  releaseName: smarter-device-manager
  targetNamespace: smarter-device-manager
  chart:
    spec:
      chart: smarter-device-manager
      version: 0.0.10
      sourceRef:
        kind: HelmRepository
        name: smarter-device-manager
  values:
    image:
      repository: ghcr.io/smarter-project/smarter-device-manager
      tag: sha256-92e1a8e8d908d4ab85d4dd60cb076f6e39ff88a8c6d021478b07957bb824eefd.sig
    config:
      deviceplugin: |
        - devicematch: /dev/fuse
          nummaxdevices: 20
