// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Gateway.V1
{

    /// <summary>
    /// ExtensionRef is an optional, implementation-specific extension to the "filter" behavior.  For example, resource "myroutefilter" in group "networking.example.net"). ExtensionRef MUST NOT be used for core and extended filters. 
    ///  This filter can be used multiple times within the same rule. 
    ///  Support: Implementation-specific
    /// </summary>
    public class HTTPRouteSpecRulesBackendRefsFiltersExtensionRefArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Group is the group of the referent. For example, "gateway.networking.k8s.io". When unspecified or empty string, core API group is inferred.
        /// </summary>
        [Input("group", required: true)]
        public Input<string> Group { get; set; } = null!;

        /// <summary>
        /// Kind is kind of the referent. For example "HTTPRoute" or "Service".
        /// </summary>
        [Input("kind", required: true)]
        public Input<string> Kind { get; set; } = null!;

        /// <summary>
        /// Name is the name of the referent.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public HTTPRouteSpecRulesBackendRefsFiltersExtensionRefArgs()
        {
        }
        public static new HTTPRouteSpecRulesBackendRefsFiltersExtensionRefArgs Empty => new HTTPRouteSpecRulesBackendRefsFiltersExtensionRefArgs();
    }
}
