// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1
{

    /// <summary>
    /// DataPlaneStatus defines the observed state of DataPlane
    /// </summary>
    [OutputType]
    public sealed class DataPlaneStatus
    {
        /// <summary>
        /// Addresses lists the addresses that have actually been bound to the DataPlane.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusAddresses> Addresses;
        /// <summary>
        /// Conditions describe the status of the DataPlane.
        /// </summary>
        public readonly ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusConditions> Conditions;
        /// <summary>
        /// ReadyReplicas indicates how many replicas have reported to be ready.
        /// </summary>
        public readonly int ReadyReplicas;
        /// <summary>
        /// Replicas indicates how many replicas have been set for the DataPlane.
        /// </summary>
        public readonly int Replicas;
        /// <summary>
        /// RolloutStatus contains information about the rollout. It is set only if a rollout strategy was configured in the spec.
        /// </summary>
        public readonly Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRollout Rollout;
        /// <summary>
        /// Selector contains a unique DataPlane identifier used as a deterministic label selector that is used throughout its dependent resources. This is used e.g. as a label selector for DataPlane's Services and Deployments.
        /// </summary>
        public readonly string Selector;
        /// <summary>
        /// Service indicates the Service that exposes the DataPlane's configured routes
        /// </summary>
        public readonly string Service;

        [OutputConstructor]
        private DataPlaneStatus(
            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusAddresses> addresses,

            ImmutableArray<Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusConditions> conditions,

            int readyReplicas,

            int replicas,

            Pulumi.Kubernetes.Types.Outputs.Gatewayoperator.V1Beta1.DataPlaneStatusRollout rollout,

            string selector,

            string service)
        {
            Addresses = addresses;
            Conditions = conditions;
            ReadyReplicas = readyReplicas;
            Replicas = replicas;
            Rollout = rollout;
            Selector = selector;
            Service = service;
        }
    }
}
