apiVersion: core.thecluster.io/v1alpha1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: thecluster
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  # TODO(user): Add fields here
