apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-keycloak
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              resources:
                limits:
                  memory: 512Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-keycloak:v2.6.0
  runtimeConfigRef:
    name: provider-keycloak
