apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-byoh
    clusterctl.cluster.x-k8s.io: ""
  name: byoh-serving-cert
  namespace: byoh-system
spec:
  dnsNames:
  - byoh-webhook-service.byoh-system.svc
  - byoh-webhook-service.byoh-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: byoh-selfsigned-issuer
  secretName: byoh-webhook-service-cert
