apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-byoh
    clusterctl.cluster.x-k8s.io: ""
  name: byoh-leader-election-rolebinding
  namespace: byoh-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: byoh-leader-election-role
subjects:
- kind: ServiceAccount
  name: byoh-controller-manager
  namespace: byoh-system
