apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-byoh
    clusterctl.cluster.x-k8s.io: ""
  name: byoh-controller-manager
  namespace: byoh-system
