apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: byoh-system/byoh-serving-cert
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/provider: infrastructure-byoh
    clusterctl.cluster.x-k8s.io: ""
  name: byoh-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: byoh-webhook-service
      namespace: byoh-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-bootstrapkubeconfig
  failurePolicy: Fail
  name: vbootstrapkubeconfig.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - bootstrapkubeconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: byoh-webhook-service
      namespace: byoh-system
      path: /validate-infrastructure-cluster-x-k8s-io-v1beta1-byohost
  failurePolicy: Fail
  name: vbyohost.kb.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - byohosts
  sideEffects: None
