// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Metal.V1Alpha2
{

    public class ServerClassSpecQualifiersHardwareNetworkArgs : global::Pulumi.ResourceArgs
    {
        [Input("interfaceCount")]
        public Input<int>? InterfaceCount { get; set; }

        [Input("interfaces")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Metal.V1Alpha2.ServerClassSpecQualifiersHardwareNetworkInterfacesArgs>? _interfaces;
        public InputList<Pulumi.Kubernetes.Types.Inputs.Metal.V1Alpha2.ServerClassSpecQualifiersHardwareNetworkInterfacesArgs> Interfaces
        {
            get => _interfaces ?? (_interfaces = new InputList<Pulumi.Kubernetes.Types.Inputs.Metal.V1Alpha2.ServerClassSpecQualifiersHardwareNetworkInterfacesArgs>());
            set => _interfaces = value;
        }

        public ServerClassSpecQualifiersHardwareNetworkArgs()
        {
        }
        public static new ServerClassSpecQualifiersHardwareNetworkArgs Empty => new ServerClassSpecQualifiersHardwareNetworkArgs();
    }
}
