// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Pulumi.V1
{

    /// <summary>
    /// customTimeouts overrides the default retry/timeout behavior for resource provisioning.
    /// </summary>
    public class ProgramProgramResourcesOptionsCustomTimeoutsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// create is the custom timeout for create operations.
        /// </summary>
        [Input("create")]
        public Input<string>? Create { get; set; }

        /// <summary>
        /// delete is the custom timeout for delete operations.
        /// </summary>
        [Input("delete")]
        public Input<string>? Delete { get; set; }

        /// <summary>
        /// update is the custom timeout for update operations.
        /// </summary>
        [Input("update")]
        public Input<string>? Update { get; set; }

        public ProgramProgramResourcesOptionsCustomTimeoutsArgs()
        {
        }
        public static new ProgramProgramResourcesOptionsCustomTimeoutsArgs Empty => new ProgramProgramResourcesOptionsCustomTimeoutsArgs();
    }
}
