apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
  namespace: renovate-operator
spec:
  interval: 30m
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.4.0
