apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cert-manager-crds
  namespace: cert-manager
spec:
  url: https://github.com/cert-manager/cert-manager
  interval: 1h
  ref:
    tag: v1.18.2
  ignore: |
    /*
    !/deploy/
    !/deploy/crds/
    !/deploy/crds/**
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: cert-manager
spec:
  sourceRef:
    kind: GitRepository
    name: cert-manager-crds
  path: ./deploy/crds
  interval: 1h
  prune: false
  wait: true
