---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ramworld
  namespace: ramworld
spec:
  encryptedData:
    adminPassword: AgDWQCCjcSu/CZZEUIQr0aI39N4d3eauXdSIsuT3kxDDeJCgTQJ60f7z1fEHX8fAX2qiah1xVrPuADyFmTdyGg6AAv49POf1UbDQFg8RWB48rv0KadcnCab4O6Hv1VvDP93Yx+riXjg3Yz6Bk2/ImoTTNW0uJn9+xKF1Op1/Dh1VAz2GZj5XjC/QaXCK4wZS62X5WvgvlkhmhsCqGsU6/ygdB5UGCCH/EVtRg3/uScKjrj+03sJzMXuO7ADXQeO8/rlhYYQlWjfZa6hEuhaO9iH4kyEu9v09e+KGw87XTCZv1wl+30E6XcCv8ercVTSpI1NBHUdGpHajWX53s/omnJGBuBCw5/2tdj1Dg+KPiigxPxeTEpZiR6iQPgok4xqeaPCoOrtRBX3jg5/Thx4Xy5qO8EhWuPbiNKKSsQY1DNCBZPmrftdUDNOUPK+/+nu6Ce2rPARG1BOSIib9K3HAvoQGf0vF84h5vs+VJNVw+rfyFR7FaRPYMGmA3QCZE0Ya5Q3+xFMPeNaChKWoZT4Vbk1ejmryVLPCazWrasDgGAas44M6g+FOwJYueYghPIzsSW7SDTV+B/uXo5TJ+pQojKDZPxMvmJXH6b3OfQUtWthoNPZUXwdmIx6dhO5PFu61D72VBeF0UYBDbrGGmITDFhES3KLQKSWxwD9PRJhnrWdkncDyAnYmtTYOaadSwpWrZFW7JwRcZFw2woec4WjegAChlY77tLqIADzZBh5JbiCjMveRM03zAor0xpBBIm2klIM=
    serverPassword: AgCj5mxQ7AYu8JBDFds09upgFs8wRv9DAoVrzZ0vH2UMvPou8p4w0bnoGs5UT23IrJ4Jk+0FBN6ia5v8LKQbcJB3sc4HetkHXPiloRhThrajNs+9uJBBIJWM4iwWQ/VunDm+mutmAwUCSB5SXWZRMMxSmeXP3yWm1zlnIRzfCnXrYhoa28GicliI1nfCBey3t3ExIHhfBkkvI6ZwldBACLdxLoOxD+GdfY0/emlJlcGMaKh8VcuZAtVYSXvCt/cDvfZADE79iLrEqsZLOkGVJMSNdC4jUoj4Ye1Zkmr1h6kJjeavSgaZGRjs9suiwWZ57AwPMSrbVKrSC/43uq7Golc/t8mibwySMCMR7tAwujC1/qox4AVrXaMIeGV0rfasJuG4FFY2NMx0gHRYiMm/CkN7J9GeP2Uzpm9vJvfajuWDnmq/1ioIXa9jYFnGjDFGUbam2f7yYOB7ozLeKbMLwuYHxcJhL1QjyzZb1tesAn/TyejYPkADx0Z19POLMUzsINwJZZy/QDYd+JBV5Ya6Mtg7+5eVW7bUVEbPi5+sy/vhJrd0kA0k7/ykIYKsU40kIQzycvAaVZ1Am3AYeVyVlqOGpu/4lFLsM1jIGkXS0mHDbtmZ9KG2CBnIldmJiHsaknpehSiq6sJAV6nz2od3KTLOb0ykTmUkZXmx+pLRnKzjrDu2Ps5rpwACDvh2GH0c5U+4jg0VTsdw3xELs1hHJjjb8YXb5bRWXp1tRw==
  template:
    metadata:
      name: ramworld
      namespace: ramworld
    type: Opaque
