apiVersion: v1
kind: Service
metadata:
  name: ramworld
  namespace: ramworld
  labels:
    app.kubernetes.io/name: ramworld
  annotations:
    metallb.io/loadBalancerIPs: 10.0.69.208
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: ramworld
  ports:
    - name: server
      port: 8211
      targetPort: 8211
      protocol: UDP
    - name: query
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: rest
      port: 8212
      targetPort: 8212
      protocol: TCP
