// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1
{

    /// <summary>
    /// GatewayConfigurationStatus defines the observed state of GatewayConfiguration
    /// </summary>
    public class GatewayConfigurationStatusArgs : global::Pulumi.ResourceArgs
    {
        [Input("conditions")]
        private InputList<Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.GatewayConfigurationStatusConditionsArgs>? _conditions;

        /// <summary>
        /// Conditions describe the current conditions of the GatewayConfigurationStatus.
        /// </summary>
        public InputList<Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.GatewayConfigurationStatusConditionsArgs> Conditions
        {
            get => _conditions ?? (_conditions = new InputList<Pulumi.Kubernetes.Types.Inputs.Gatewayoperator.V1Alpha1.GatewayConfigurationStatusConditionsArgs>());
            set => _conditions = value;
        }

        public GatewayConfigurationStatusArgs()
        {
        }
        public static new GatewayConfigurationStatusArgs Empty => new GatewayConfigurationStatusArgs();
    }
}
