apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../external-snapshotter
  - ../gateway-api
  - ingress.yml
  - network-policy.yml
  - receiver.yml
  - sealed-secrets.yml
  - webhook-token-sealed.yml
