apiVersion: v2
name: filebrowser
description: Helm chart for installing filebrowser
type: application
version: 0.1.0
appVersion: 2.26.0
sources:
- https://github.com/filebrowser/filebrowser
- https://github.com/UnstoppableMango/the-cluster/tree/main/charts/filebrowser
kubeVersion: '>= 1.25'
icon: https://raw.githubusercontent.com/filebrowser/logo/master/icon.png
maintainers:
- name: UnstoppableMango
  url: https://github.com/UnstoppableMango
dependencies:
- name: oauth2-proxy
  repository: https://oauth2-proxy.github.io/manifests
  version: 6.24.2
  condition: oauth2-proxy.enabled
