global:
  registry: 'docker.io'
  uid: 911
  gid: 911

address: 0.0.0.0
port: 8080
baseUrl: /
viewMode: list
existingConfigMap: ''
extraVolumes: []
extraVolumeMounts: []
securityContext: {}

branding:
  name: ''
  theme: dark
  disableUsedPercentage: false

auth:
  method: proxy
  header: X-Forwarded-User

ingress:
  enabled: false
  annotations: {}
  ingressClassName: ''
  host: ''
  path: /
  pathType: ImplementationSpecific
  tls:
    enabled: false

persistence:
  enabled: true
  storageClassName: ''
  size: 1Gi

image:
  registry: docker.io
  repository: filebrowser/filebrowser
  tag: ''
  digest: ''

init:
  image:
    registry: docker.io
    repository: filebrowser/filebrowser
    tag: ''
    digest: ''
  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: false # So we can chown the right dirs

service:
  type: ClusterIP
  port: 8080
  clusterIP: ''
  loadBalancerIP: ''

oauth2-proxy:
  enabled: false
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
