global:
  registry: 'docker.io'
  uid: 911
  gid: 911

port: 8080
existingConfigMap: ''
extraVolumes: []
extraVolumeMounts: []
userHeader: ''

ingress:
  enabled: false
  annotations: {}
  ingressClassName: ''
  host: ''
  path: /
  pathType: ImplementationSpecific
  tls:
    enabled: false

persistence:
  enabled: true
  storageClassName: ''
  size: 1Gi

image:
  registry: docker.io
  repository: filebrowser/filebrowser
  tag: ''
  digest: ''

init:
  image:
    registry: docker.io
    repository: filebrowser/filebrowser
    tag: ''
    digest: ''

service:
  type: ClusterIP
  port: 8080
  clusterIP: ''
  loadBalancerIP: ''

oauth2-proxy:
  enabled: false
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
