apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  # - secret-sealed.yml # add once sealed: see hack/secrets/apps/slackpack/slackpack.yml
  - minecolonies-server-configmap.yml
  - mods-pvc.yml
  - service.yml
  - statefulset.yml
