apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ncps
  namespace: nix-system
  labels:
    app: ncps
    tier: proxy
spec:
  storageClass: unsafe-rbd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
