---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-github-oauth
  namespace: awx-system
spec:
  encryptedData:
    github_oauth.py: AgBsFiOHLWFEkFCSPrxuBEyFgb3Xhb73mWUq2RCv2YfX68mtSE5caZoEaQwnBtPSuOEe7HKLiDHYkgunBPbs9mWYYpbCW877+IR53tgEnKVcpLXBNZmoPUjTIc3OsinrvLYiJau3HV5rYMC3NqlRmuvO8qK1/zgVphJpxkBY6woHM32ufo9pipC/UX0yuXdXqLMoKvKROmoDQ2fB6O+vlvmqBW8W1bufR0RWHKU1YDIt0WAzu3LDyxLIuznRTx43UxqdEygmb7C5NZjCWPkyGn/t6hkU5tAHsxueo03S76dAi680IcBsFUj6/v9uV+kzuCUFEBM9g5GwMi91ln9tcByFXwJiBjMvAh4XhHp01s9IJ9QTygsK2KQt2B2YcNn2bzTtiMtBNt+XGCZPDQ/YjyCKJX2IYkWpTrWpO0fnrSG5Ph3ns1+6EZkumAfrSlhcTUshed7g0P3hj+KMJs9wa/ezrV2f8ozaHeMMfAp3TEhwNfE/Ol70nry6EWFlNxAD2oLmM4U08U5CrPz+rhJdZ0XP1x1twPSfBPUFshrlVixYyo91OJXXyMJsb+MMcMOs2EqTisP98kFgjtXF778/BIQL08EsSmJUwSXsHMjsB01tgMxncQuEpRTDEZCearbapFRN6ahLUPgnlOmlfEf2YO93IDOgOihCLmNznq8enociNP2sULWlt72p1h+jVpyW4R6KnV/B6JryqHnzliDhcASmVQRC9BctkNrqrdTRRhVR2xTrreyVuyJbwisBWMPjoi5pO2dAT++HSgT+IYALyvzD4QUhikNfS4748Koh3dRTSZ5+cOjaV5P/1o5Jp77ucOHxTeWeRxoaEiTHBNQtp0ze3kvW4qgQleIJY6w6L6J+WsAxHzr+9ZOtfoCTRigFpLSFTV6PYJAB/qi6/G+YxrjYufXs38vf/YLdjjestcx3x1DFsd+Gt8zI+rrnb/L/H9EbntfnZOFdxhH17l2ZToJUTCZCny1fUNaKqa9Falqw9Enrql01fGVlTSG2TvGY/byNvWRVvawGqDYpX+bi8A/HZ3FTkh0yNGZ/0xGE5I0FFXwJ2Tfu9AqGiOmFTrmRj7BHfQxftIjlol/7o8KmR4vOjipYcl9zAio6kaioYZufhyBFSOdxpM9EiLz3AjdLTQS/r+Kko5hbvWBbMMKFmcBK5bVQNAmGyqnYVrsYCKm5L8oera4IQtnfsw0LycyZByvYX9GJkf73uo1xsBd3otu7XKap4ttRa7FY7yUWfZ8uSiC8NTYCbKkPfGXN3b/r/A==
  template:
    metadata:
      name: awx-github-oauth
      namespace: awx-system
