---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: awx-github-oauth
  namespace: awx-system
spec:
  encryptedData:
    github_oauth.py: AgBpotBLVpYQu3/vsKSBCvKXTlNMlVGnumwjjOolSXpJRrNhjkFQruG2LlijgowGpSos3N0M9GTcw93aBtyMfGL6npdp9407O+SeuAdH6AFsRyjhLM0WTXf/Elwof6C7o+ayn7ZcOVclH9WMtpHdbwPxG2kd7zA5SZkqideiz/dWyRy2vg2e5jQPsHfpCrG3t0CPJTHtv37NdixNPD/MoTAEcKNmtXzUQzOopT0ftS06toGYqrVCGi8m+ys8SrGkbnyZAh+hfX8xkQoBKCgrrWiqauiYxLE/9tXE6MqVx/Okekj+QqOOH0DdEzzx2CwhcU4IGyrT52nedyBfTmJcCrmgFePM826/tZlOcoAuLLAbWQwjccXpWtkWBC70EnLaQSB4IOgehY0hTndXjhJT9ZjrVETMu3BkQB1zJ296GKeeVtxmjemB3uf06Jk4W5ZlnbxN4UacspCeoCOi9ecms+KdA042kfhNQTLz6vrXtDnG2SR9m+fCZKxgfWiKjfr/sAG8s2vjVR+2jXoQcsa8shGb+vyhSB8RWw7uRVKlzXxib9vVLMXM4Pn6OHoUpUdEQvaQfNiSw8GYzgOZgHvbm6Oklv2vGOHJoxXsWcilNgoD3Ek2dmhcwle/RUfPX9GA6grEUSn6P8EWdV0fFBe3Ffjs0ne81hmDVUIcM9mW3NbE3eQW22N/aDy/FlDBrTZzNUDt5sceqNqLZsOAULC6k1ViRRDZlXujqchOraskxI2H4uZEwLwzM9iKvF6RH8NsRVzmS9IF2CgCLN7BxS+9OcD1UwwtnRL4gECCHtjHZZsnAHsTppvcP4iUa5MoZj6xPQddJpINXiIRIiahxiQl+jmuwE6whA524plCIjzyEZ6aZV3WWQw344tzZ5vIoZKVl+/5LqWm8YR9qdri+igjjqcI9ITTBcfRNJZnfWa0hfaEbQa0CB9n/u0KtxwYz5sbO0VuuptPMFnKFYTBnJKn1C5gqYYy3coEM9t/Du6jv0Uzbg7fBZgbzp5W3uoGqfSfjYeZDAtytcLc5zQUn1Gv6fJ7q0iPeflb6bA2iXSWjpBlOP8NMM86wa1elFmsAUYc43hI4/Pcy/P7iInVQg==
  template:
    metadata:
      name: awx-github-oauth
      namespace: awx-system
