apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cabpt-serving-cert
  namespace: cabpt-system
spec:
  dnsNames:
  - cabpt-webhook-service.cabpt-system.svc
  - cabpt-webhook-service.cabpt-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: cabpt-selfsigned-issuer
  secretName: cabpt-webhook-service-cert
