apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
    control-plane: controller-manager
  name: cabpt-controller-manager-metrics-service
  namespace: cabpt-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    cluster.x-k8s.io/provider: bootstrap-talos
    control-plane: controller-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    cluster.x-k8s.io/provider: bootstrap-talos
    clusterctl.cluster.x-k8s.io: ""
  name: cabpt-webhook-service
  namespace: cabpt-system
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    cluster.x-k8s.io/provider: bootstrap-talos
    control-plane: controller-manager
