name: thecluster-kube-prometheus-stack
description: kube-prometheus-stack install for THECLUSTER
runtime:
  name: nodejs
  options:
    packagemanager: yarn
config:
  pulumi:tags:
    value:
      pulumi:template: typescript
