name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: unmango/actions/setup-nix@3ec4ed5a6af9c00f6a39e079df488573c77ebda6 # v1.0.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          # cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extra_nix_config: |
            extra-experimental-features = nix-command flakes pipe-operators

      - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15

      - run: nix flake check
