name: Containers

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/containers.yml
      - containers/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/containers.yml
      - containers/**

jobs:
  nix-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build runner image
        run: |
          nix build '.#runner'

  actions-runner:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=docker depName=ghcr.io/actions/actions-runner
      ACTIONS_RUNNER_VERSION: 2.334.0
    steps:
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: |
            ghcr.io/${{ github.repository }}/actions-runner
          flavor: |
            latest=auto
          # defensive tagging because I'm an idiot
          tags: |
            type=ref,event=branch,suffix=-${{ env.ACTIONS_RUNNER_VERSION }}
            type=ref,event=branch,suffix=-v${{ env.ACTIONS_RUNNER_VERSION }}
            type=ref,event=branch,suffix=-${{ env.ACTIONS_RUNNER_VERSION }}-${{ github.run_number }}
            type=ref,event=branch,suffix=-v${{ env.ACTIONS_RUNNER_VERSION }}-${{ github.run_number }}
            type=raw,value=${{ env.ACTIONS_RUNNER_VERSION }}
            type=raw,value=v${{ env.ACTIONS_RUNNER_VERSION }}
            type=sha

      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          file: containers/runner/Dockerfile
          build-args: |
            ACTIONS_RUNNER_VERSION=${{ env.ACTIONS_RUNNER_VERSION }}
          platforms: ${{ github.event_name == 'pull_request' && 'linux/amd64' || 'linux/arm64,linux/amd64' }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: ${{ github.event_name != 'pull_request' }}
          sbom: ${{ github.event_name != 'pull_request' }}
