name: Cron Job Containers

on:
  pull_request:
    branches: ['main']
    paths:
      - .github/workflows/cron-jobs.yml
      - .github/workflows/dockedr-container.yml
      - infra/cron-jobs/containers/**
  push:
    branches: ['main']
    tags: [v*.*.*]
    paths:
      - .github/workflows/cron-jobs.yml
      - .github/workflows/dockedr-container.yml
      - infra/cron-jobs/containers/**

jobs:
  clean-pvs:
    name: Clean PVs Cron Job
    uses: ./.github/workflows/docker-container.yml
    with:
      name: clean-pvs-cron-job
      path: infra/cron-jobs/containers/clean-pvs
