name: Deploy

on:
  workflow_call:
    inputs:
      project:
        description: |
          The name project to deploy. This should match both the name of
          a directory under `apps/` or `clusters/` and the name of the
          pulumi project stripped of the `thecluster-` prefix.
        type: string
        required: true
      stack:
        description: The name of the pulumi stack to deploy.
        type: string
        required: true
      kind:
        description: |
          The kind of stack to deploy. Acceptable values are `apps` `clusters`, or `infra`.
        type: string
        required: false
        default: apps
      verify:
        description: Whether to run a verification script or not.
        type: boolean
        required: false
        default: true
      verify-script:
        description: |
          The path to a verification script to run after deploying.
          This path should be relative to the project directory.
        type: string
        required: false
        default: './spec/verify.sh'
      uses-crds:
        description: Whether the stack uses the CRDs library.
        type: boolean
        required: false
        default: false
      uses-lib:
        description: Whether the stack uses the shared library.
        type: boolean
        required: false
        default: true
      pre-deploy-script:
        description: The path to a script to run before deploying the stack.
        type: string
        required: false

jobs:
  deploy:
    name: ${{ github.event_name == 'push' && 'deploy' || 'preview' }}
    runs-on: ubuntu-latest
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      PROJECT_DIR: ${{ inputs.kind }}/${{ inputs.project }}
      OPERATION: ${{ github.event_name == 'push' && 'up' || 'preview' }}
      STACK: ${{ inputs.stack }}
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}
    steps:
    - uses: actions/checkout@v4
    - run: git config --global --add safe.directory "/__w/the-cluster/the-cluster" # actions/runner#2033

    - name: Validate inputs
      run: |
        case "${{ inputs.kind }}" in
          apps | clusters | infra);;
          *) echo "Invalid kind" && exit 1;;
        esac

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: |
          ${{ env.PROJECT_DIR }}/package-lock.json
          lib/crds/package-lock.json

    - uses: ./.github/actions/setup-tools
      with:
        all: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ./.github/actions/pulumi-deploy
      with:
        project: ${{ inputs.project }}
        stack: ${{ inputs.stack }}
        kind: ${{ inputs.kind }}
        op: ${{ env.OPERATION }}
        verify: ${{ inputs.verify }}
        verify-script: ${{ inputs.verify-script }}
        uses-crds: ${{ inputs.uses-crds }}
        uses-lib: ${{ inputs.uses-lib }}
        pre-deploy-script: ${{ inputs.pre-deploy-script }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
