name: Deploy

on:
  workflow_call:
    inputs:
      project:
        description: |
          The name project to deploy. This should match both the name of
          a directory under `apps/` or `clusters/` and the name of the
          pulumi project stripped of the `thecluster-` prefix.
        type: string
        required: true
      stack:
        description: The name of the pulumi stack to deploy
        type: string
        required: true
      kind:
        description: |
          The kind of stack to deploy. Acceptable values are `app` or `cluster`
        type: string
        required: false
        default: app
      verify-script:
        description: |
          The path to a verification script to run after deploying.
          This path should be relative to the project directory.
        type: string
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIR }}
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      PROJECT_DIR: ${{ inputs.kind }}s/${{ inputs.project }}
      OPERATION: ${{ github.event_name == 'push' && 'up' || 'preview' }}
    steps:
      - name: Validate kind input
        run: |
          case "${{ inputs.kind }}" in
            app | cluster) ;;
            *) echo "Invalid kind" && exit 1;;
          esac

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: ${{ env.PROJECT_DIR }}/package-lock.json

      - uses: ./.github/actions/setup-tools
        with:
          all: true

      - uses: ./.github/actions/setup-config
        if: inputs.kind != 'cluster'
        with:
          cluster: rosequartz

      - run: npm ci

      - run: |
          if [ $(ls -1 Chart.{yml,yaml} 2>/dev/null | wc -l) -gt 0 ]; then
            helm dependency update
          fi

      - name: Pulumi ${{ env.OPERATION }}
        uses: pulumi/actions@v4
        with:
          stack-name: UnstoppableMango/thecluster-${{ inputs.project }}/${{ inputs.stack }}
          command: ${{ env.OPERATION }}
          work-dir: ${{ env.PROJECT_DIR }}

      - name: Validate
        if: ${{ inputs.verify-script != '' }}
        run: ${{ inputs.verify-script }}

      - uses: ./.github/actions/pulumi-deploy
        with:
          kind: ${{ inputs.kind }}
          project: ${{ inputs.project }}
          stack: ${{ inputs.stack }}
          op: ${{ github.event_name == 'push' && 'up' || 'preview' }}
          validate: ${{ github.event_name == 'push' }}
