name: Deploy

on:
  workflow_call:
    inputs:
      kind:
        required: true
        type: string
      name:
        required: true
        type: string
      stack:
        required: true
        type: string
      tf-stack:
        required: true
        type: string
      op:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/dashboard
    env:
      TF_WORKSPACE: ${{ inputs.tf-stack }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # renovate depName=hashicorp/terraform
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - uses: /.github/actions/setup-rq-deploy
        with:
          tf-workspace: ${{ inputs.tf-stack }}
          talosconfig: ./talosconfig
          kubeconfig: ./kubeconfig

      - uses: /.github/actions/pulumi-deploy
        with:
          kind: ${{ inputs.kind }}
          name: ${{ inputs.name }}
          stack: ${{ inputs.stack }}
          op: ${{ github.event_name == 'push' && 'up' || 'preview' }}
          validate: ${{ github.event_name == 'push' }}
