name: End To End Test

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/**/*e2e*'
      - 'apps/**/package-lock.json'
      - 'apps/**/Chart.yaml'
      - 'apps/**/.versions'
      - 'clusters/**/package-lock.json'
      - 'clusters/**/Chart.yaml'
      - 'clusters/**/.versions'
  workflow_dispatch:

env:
  RQ_STACK: ci
  RQ_TALOSCONFIG: ${{ github.workspace }}/talosconfig
  RQ_KUBECONFIG: ${{ github.workspace }}/kubeconfig
  TALOSCONFIG: ${{ github.workspace }}/talosconfig
  KUBECONFIG: ${{ github.workspace }}/kubeconfig
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  CLOUDFLARE_API_TOKEN: bogus

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    env:
      STACK_ID: ${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4

      - id: setup
        uses: ./.github/actions/setup-e2e
        with:
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
          stack-id: ${{ env.STACK_ID }}

      - uses: ./.github/actions/e2e-test
        with:
          stack-id: ${{ env.STACK_ID }}
          talosconfig: ${{ env.TALOSCONFIG }}
          kubeconfig: ${{ env.KUBECONFIG }}

      - uses: ./.github/actions/teardown-e2e
        with:
          tf-workspace: ${{ steps.setup.outputs.workspace }}
          stack-id: ${{ env.STACK_ID }}

  upgrade-e2e-test:
    runs-on: ubuntu-latest
    env:
      STACK_ID: ${{ github.run_id }}-${{ github.run_attempt }}-upg
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - id: setup
        uses: ./.github/actions/setup-e2e
        with:
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
          stack-id: ${{ env.STACK_ID }}

      - uses: ./.github/actions/e2e-test
        with:
          stack-id: ${{ env.STACK_ID }}
          talosconfig: ${{ env.TALOSCONFIG }}
          kubeconfig: ${{ env.KUBECONFIG }}

      - uses: actions/checkout@v4

      - uses: ./.github/actions/e2e-test
        with:
          stack-id: ${{ env.STACK_ID }}
          talosconfig: ${{ env.TALOSCONFIG }}
          kubeconfig: ${{ env.KUBECONFIG }}

      - uses: ./.github/actions/teardown-e2e
        with:
          tf-workspace: ${{ steps.setup.outputs.workspace }}
          stack-id: ${{ env.STACK_ID }}
