name: Helm Package

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        description: The name of the chart under /charts
      tag:
        type: string
        required: true
        description: The chart version to package

jobs:
  build:
    name: ${{ github.event_name == 'push' && 'Helm Publish' || 'Helm Package' }}
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-tools
        with:
          helm: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Login
        if: github.event_name == 'push'
        shell: bash
        run: echo '${{ github.token }}' | helm registry login -u '${{ github.repository_owner }}' --password-stdin ghcr.io

      - name: Helm Package
        shell: bash
        run: helm package ${{ format('{0}/{1}', 'charts', inputs.name) }} --version ${{ inputs.tag }}

      - name: Helm Push
        if: github.event_name == 'push'
        shell: bash
        run: helm push ${{ inputs.name }}-${{ inputs.tag }}.tgz oci://ghcr.io/${{ github.repository }}

      - name: Helm Logout
        if: github.event_name == 'push'
        shell: bash
        run: helm registry logout ghcr.io
