name: Helm Package

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
        description: The name of the chart under /charts
      path:
        type: string
        required: true
        description: Relative path to the chart

jobs:
  build:
    name: ${{ github.event_name == 'push' && 'Helm Publish' || 'Helm Package' }}
    runs-on: ubuntu-latest
    env:
      HELM_EXPERIMENTAL_OCI: "1"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: ./.github/actions/setup-tools
        with:
          helm: true
          minver: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: version
        name: Get Version
        run: echo "version=$(minver -t ${{ inputs.name }}/v)" >> "$GITHUB_OUTPUT"

      - name: Helm Login
        if: github.event_name == 'push'
        run: echo '${{ github.token }}' | helm registry login -u '${{ github.repository_owner }}' --password-stdin ghcr.io

      - name: Helm Package
        run: helm package ${{ format('{0}/{1}', 'charts', inputs.name) }} --version ${{ steps.version.outputs.version }}

      - name: Helm Push
        if: github.event_name == 'push'
        run: helm push ${{ inputs.name }}-${{ steps.version.outputs.version }}.tgz "oci://ghcr.io/${REPOSITORY,,}"
        env:
          REPOSITORY: ${{ github.repository }}

      - name: Helm Logout
        if: github.event_name == 'push'
        run: helm registry logout ghcr.io
