name: NodeJS Lib

on:
  pull_request:
    branches: ['main']
    paths:
      - lib/nodejs/**
      - .github/workflows/lib-nodejs.yml
  push:
    branches: ['main']
    tags: ['lib/nodejs/v*.*.*']
    paths:
      - lib/nodejs/**
      - .github/workflows/lib-nodejs.yml

jobs:
  nodejs:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        working-directory: lib/nodejs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache-dependency-path: lib/nodejs/packages-lock.json
          registry-url: https://npm.pkg.github.com/

      - uses: ./.github/actions/setup-tools
        with:
          minver: true
          pulumi: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm version "$(minver -t lib/nodejs/v)"
      - run: npm ci

      - run: npm publish --dry-run
        if: github.event_name != 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish
        if: github.event_name == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
