name: Main

on:
  pull_request:
    branches: [v2]
  push:
    branches: [v2]

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_CLI_ARGS: '-no-color'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set modified stacks
        id: stacks
        uses: ./.github/actions/modified-stacks
    outputs:
      rosequartz: ${{ steps.stacks.outputs.rosequartz }}
      cert-manager: ${{ steps.stacks.outputs.cert-manager }}

  rosequartz:
    name: Rosequartz Stack
    runs-on: ubuntu-latest
    needs: [setup]
    if: fromJson(needs.setup.outputs.rosequartz) && !failure() && !cancelled()
    defaults:
      run:
        working-directory: stacks/rosequartz
    env:
      RQ_STACK: ${{ github.event_name == 'pull_request' && 'ci' || 'prod' }}
      RQ_TALOSCONFIG: talosconfig
      RQ_KUBECONFIG: kubeconfig
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      # TODO: Get a specfic version
      - name: Install talosctl
        run: curl -sL https://talos.dev/install | sh

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -lockfile=readonly
        env:
          TF_WORKSPACE: ${{ github.event_name == 'push' && 'rosequartz-prod' || 'rosequartz-ci' }}

      - name: Setup workspace
        id: setup-workspace
        run: |
          workspace="rosequartz"
          if [ "$GITHUB_EVENT_NAME" == "push" ]; then
              workspace="$workspace-prod"
          else
              workspace="$workspace-${GITHUB_HEAD_REF//[\/.]/-}"
              terraform workspace new "$workspace"
          fi
          terraform workspace select "$workspace"
          echo "workspace=$workspace" >> "$GITHUB_OUTPUT"

      - name: Terraform Validate
        run: terraform validate

      - name: Create test node
        if: github.event_name == 'pull_request'
        run: docker compose -f ci/docker-compose.yaml up -d
        timeout-minutes: 1

      - name: Setup secrets
        if: github.event_name == 'push'
        run: |
          echo "TF_VAR_public_ip=${{ secrets.RQ_PUBLIC_IP }}" >> "$GITHUB_ENV"
          echo "TF_VAR_primary_dns_name=${{ secrets.RQ_PRIMARY_DNS_NAME }}" >> "$GITHUB_ENV"

      - name: Terraform Plan
        run: terraform plan -var-file=vars/$RQ_STACK.tfvars -out=tfplan
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        timeout-minutes: 5
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Write configuration files
        run: |
          terraform output -raw talosconfig > "$RQ_TALOSCONFIG"
          terraform output -raw kubeconfig > "$RQ_KUBECONFIG"

      - name: Cluster validation
        run: ./spec/validation.sh

      - name: Tear down
        if: github.event_name == 'pull_request' && !cancelled()
        run: |
          terraform destroy -auto-approve
          terraform workspace select rosequartz-ci
          terraform workspace delete "${{ steps.setup-workspace.outputs.workspace }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        timeout-minutes: 5

  cert-manager:
    name: Cert Manager Stack
    runs-on: ubuntu-latest
    needs: [setup, rosequartz]
    if: fromJson(needs.setup.outputs.cert-manager) && !failure() && !cancelled()
    defaults:
      run:
        working-directory: stacks/cert-manager
    env:
      TF_WORKSPACE: rosequartz-prod
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: stacks/cert-manager/package-lock.json

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Setup kubeconfig
        run: |
          terraform init -lockfile=readonly
          terraform output -raw kubeconfig > kubeconfig
          echo "KUBECONFIG=$(pwd)/kubeconfig" >> "$GITHUB_ENV"
        working-directory: stacks/rosequartz

      - run: npm ci

      - name: Pulumi Action
        uses: pulumi/actions@v4
        with:
          stack-name: UnstoppableMango/thecluster-cert-manager/rosequartz
          command: ${{ github.event_name == 'push' && 'up' || 'preview' }}
          work-dir: stacks/cert-manager
