name: Main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CI: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set modified stacks
        id: stacks
        uses: ./.github/actions/modified-stacks
    outputs:
      rosequartz: ${{ steps.stacks.outputs.rosequartz }}
      cert-manager: ${{ steps.stacks.outputs.cert-manager }}
      cloudflare-ingress: ${{ steps.stacks.outputs.cloudflare-ingress }}
      dashboard: ${{ steps.stacks.outputs.dashboard }}
      metrics-server: ${{ steps.stacks.outputs.metrics-server }}
      clusterapi: ${{ steps.stacks.outputs.clusterapi }}

  rosequartz:
    name: Rosequartz
    runs-on: ubuntu-latest
    needs: [setup]
    if: fromJson(needs.setup.outputs.rosequartz) && !failure() && !cancelled()
    concurrency: rosequartz-${{ github.ref }}
    defaults:
      run:
        working-directory: clusters/rosequartz
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: clusters/rosequartz/package-lock.json

      - run: npm ci

      - run: ./spec/e2e.sh
        if: github.event_name == 'pull_request'
        env:
          RQ_STACK: rq-${{ github.run_id }}-${{ github.run_attempt }}

      - name: Verify
        if: github.event_name == 'push'
        run: ./spec/verify.sh

  cert-manager:
    name: Cert Manager
    runs-on: ubuntu-latest
    needs: [setup, rosequartz]
    if: fromJson(needs.setup.outputs.cert-manager) && !failure() && !cancelled()
    concurrency: cert-manager-${{ github.ref }}
    defaults:
      run:
        working-directory: apps/cert-manager
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: apps/cert-manager/package-lock.json

      - run: npm ci
      - run: helm dependency update # Ugh https://github.com/helm/helm/issues/9903

      - id: setup-config
        uses: ./.github/actions/setup-config
        with:
          cluster: rosequartz
          stack: prod
          endpoint: ${{ secrets.RQ_PRIMARY_DNS_NAME }}

      - name: Pulumi Action
        uses: pulumi/actions@v4
        with:
          stack-name: UnstoppableMango/thecluster-cert-manager/rosequartz
          command: ${{ github.event_name == 'push' && 'up' || 'preview' }}
          work-dir: apps/cert-manager
          pulumi-version: 3.89.0 # renovate depName=pulumi/pulumi
        env:
          KUBECONFIG: ${{ steps.setup-config.outputs.kubeconfig }}

  metrics-server:
    name: Metrics Server
    runs-on: ubuntu-latest
    needs: [setup, rosequartz]
    if: fromJson(needs.setup.outputs.metrics-server) && !failure() && !cancelled()
    concurrency: metrics-server-${{ github.ref }}
    defaults:
      run:
        working-directory: apps/metrics-server
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: apps/metrics-server/package-lock.json

      - run: npm ci
      - run: helm dependency update # Ugh https://github.com/helm/helm/issues/9903

      - id: setup-config
        uses: ./.github/actions/setup-config
        with:
          cluster: rosequartz
          stack: prod
          endpoint: ${{ secrets.RQ_PRIMARY_DNS_NAME }}

      - name: Pulumi Action
        uses: pulumi/actions@v4
        with:
          stack-name: UnstoppableMango/thecluster-metrics-server/rosequartz
          command: ${{ github.event_name == 'push' && 'up' || 'preview' }}
          work-dir: apps/metrics-server
          pulumi-version: 3.89.0 # renovate depName=pulumi/pulumi
        env:
          KUBECONFIG: ${{ steps.setup-config.outputs.kubeconfig }}

      - name: Validate
        if: github.event_name == 'push'
        run: ./spec/validation.sh

  clusterapi:
    name: Cluster API
    runs-on: ubuntu-latest
    needs: [setup, rosequartz, cert-manager]
    if: fromJson(needs.setup.outputs.clusterapi) && !failure() && !cancelled()
    concurrency: clusterapi-${{ github.ref }}
    defaults:
      run:
        working-directory: apps/clusterapi
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: apps/clusterapi/package-lock.json

      - run: npm ci

      - id: setup-config
        uses: ./.github/actions/setup-config
        with:
          cluster: rosequartz
          stack: prod
          endpoint: ${{ secrets.RQ_PRIMARY_DNS_NAME }}

      - name: Pulumi Action
        uses: pulumi/actions@v4
        with:
          stack-name: UnstoppableMango/thecluster-clusterapi/rosequartz
          command: ${{ github.event_name == 'push' && 'up' || 'preview' }}
          work-dir: apps/clusterapi
          pulumi-version: 3.89.0 # renovate depName=pulumi/pulumi
        env:
          KUBECONFIG: ${{ steps.setup-config.outputs.kubeconfig }}

      - name: Validate
        if: github.event_name == 'push'
        run: ./spec/validation.sh
