name: Pull Request

on:
  pull_request:

jobs:
  media:
    name: Preview Media
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        
    - name: Install Pulumi CLI
      uses: pulumi/setup-pulumi@v2

    - run: npm ci

    - run: echo "RANCHER_URL=$(pulumi config get rancher2:apiUrl -C ./stacks/rancher)" >> $GITHUB_ENV
    - run: echo "RANCHER_ACCESS_KEY=$(pulumi config get rancher2:accessKey -C ./stacks/rancher)" >> $GITHUB_ENV
    - run: echo "RANCHER_SECRET_KEY=$(pulumi config get rancher2:secretKey -C ./stacks/rancher)" >> $GITHUB_ENV

    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: prod
        work-dir: stacks/media
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
