name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Setup Workflows
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.stacks.outputs.value }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'

    - run: npm ci

    - id: stacks
      run: npm run set-modified-stacks

  media:
    name: Preview
    needs: [setup]
    runs-on: self-hosted
    strategy:
      matrix:
        stack: ${{ fromJson(needs.setup.outputs.stacks) }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        
    - name: Install Pulumi CLI
      uses: pulumi/setup-pulumi@v2

    - run: npm ci

    - name: Set environment variables
      if: matrix.stack != 'rancher'
      working-directory: stacks/rancher
      run: |
        pulumi stack select prod
        echo "RANCHER_URL=$(pulumi config get rancher2:apiUrl)" >> $GITHUB_ENV
        echo "RANCHER_ACCESS_KEY=$(pulumi config get rancher2:accessKey)" >> $GITHUB_ENV
        echo "RANCHER_SECRET_KEY=$(pulumi config get rancher2:secretKey)" >> $GITHUB_ENV
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: prod
        work-dir: stacks/${{ matrix.stack }}
        expect-no-changes: ${{ github.actor == 'dependabot[bot]' }}
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
