name: Validate Modified Stacks Action

on:
  pull_request:
    branches: [v2]
    paths: ['.github/actions/modified-stacks/**']

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/actions/modified-stacks
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: .github/actions/modified-stacks/package-lock.json

      - run: npm ci
      - run: npm run build

      - name: Verify action has been built
        run: '[ -z "$(git status --porcelain)" ] || git status && exit 1'
