// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1
{

    /// <summary>
    /// AutoscalingRunnerSetSpec defines the desired state of AutoscalingRunnerSet
    /// </summary>
    public class AutoscalingRunnerSetSpecArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required
        /// </summary>
        [Input("githubConfigSecret")]
        public Input<string>? GithubConfigSecret { get; set; }

        /// <summary>
        /// Required
        /// </summary>
        [Input("githubConfigUrl")]
        public Input<string>? GithubConfigUrl { get; set; }

        [Input("githubServerTLS")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1.AutoscalingRunnerSetSpecGithubServerTlsArgs>? GithubServerTLS { get; set; }

        /// <summary>
        /// PodTemplateSpec describes the data a pod should have when created from a template
        /// </summary>
        [Input("listenerTemplate")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1.AutoscalingRunnerSetSpecListenerTemplateArgs>? ListenerTemplate { get; set; }

        [Input("maxRunners")]
        public Input<int>? MaxRunners { get; set; }

        [Input("minRunners")]
        public Input<int>? MinRunners { get; set; }

        [Input("proxy")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1.AutoscalingRunnerSetSpecProxyArgs>? Proxy { get; set; }

        [Input("runnerGroup")]
        public Input<string>? RunnerGroup { get; set; }

        [Input("runnerScaleSetName")]
        public Input<string>? RunnerScaleSetName { get; set; }

        /// <summary>
        /// Required
        /// </summary>
        [Input("template")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1.AutoscalingRunnerSetSpecTemplateArgs>? Template { get; set; }

        public AutoscalingRunnerSetSpecArgs()
        {
        }
        public static new AutoscalingRunnerSetSpecArgs Empty => new AutoscalingRunnerSetSpecArgs();
    }
}
