// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1
{

    /// <summary>
    /// Required
    /// </summary>
    public class EphemeralRunnerSpecGithubServerTlsCertificateFromArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Required
        /// </summary>
        [Input("configMapKeyRef")]
        public Input<Pulumi.Kubernetes.Types.Inputs.Actions.V1Alpha1.EphemeralRunnerSpecGithubServerTlsCertificateFromConfigMapKeyRefArgs>? ConfigMapKeyRef { get; set; }

        public EphemeralRunnerSpecGithubServerTlsCertificateFromArgs()
        {
        }
        public static new EphemeralRunnerSpecGithubServerTlsCertificateFromArgs Empty => new EphemeralRunnerSpecGithubServerTlsCertificateFromArgs();
    }
}
