---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claude
  namespace: claude
spec:
  encryptedData:
    oauth-token: AgANTwSxytiy2WPoMJp4wScKW08toMNK0IXhp72hv6vz6PBeoy5Re5RWwE4GkLNxZbyZEQBvM63DdyVYhNpHzaWSm6wi9pGs18fIC3jqbbpxR4lIoWBb0TB+ReskGas+fZRb2iJhkgWrJJyzfkz5Y8QBVMphSK+T1DQV9tPNFrZSOfQUzg4De5/FvSo1UMg3YHkcAU+E2yK5CqaiCvFRM4iHW9of6wdwMKGn2t+nryUWwwQRKmzBW72/rQ4ghYoGfrV4F3pdZnzVXrBzrrYVcluIkN6rUSiP5wjLAexKj5ixAxexmAU6pkfrLQy2QhypSizxE4iZxj8uJPWtUZPlOLDSucw+x7tsT9u0g0lRSl6sTtnKHqbyaGVlbQ7Cfqa1iGbKg84n/l6n9VxcSrz6bsJKzIw6LPNFcSnRy3NsvFD9+UEf9F/aYQbUz07DUCEVjyIeYqbkPvmnEQzG4sQgqc9XqB3AlNNmHl7m0h5dLz7ot7+2S8XCR29IIWnOz3GwuLjckUpZX2SEGSUGyoukZUV1ioAuJ76YnbdB22M+ZbdV4hr0+RN9l1zKdLlNdQnEvln7j2zfHwWQ5KW1foZqsHIXhqbDVKAYvTMHIrSYSPORYI0YZC/YwfrNOsjNmbYlabncX3g7vgW8lpWvLeTWfMr3OP7PrgOYR7EchydY6kcJqux1amxA5v0EMUuqiSs2vbZsg+vSA/dZpsfFlqziCTWg8IcEkPaGum6+B84peUoAuZEv/7rIjaN58AORZNLuR8jza0TQJBo7IIBwffk9EIYnnfjCGltn2m0gojR+siaLh5Io1fo6FI5AQFiOVY+H6r569QabOVnFp2sLhIw=
  template:
    metadata:
      name: claude
      namespace: claude
    type: Opaque
