---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-credentials
  namespace: gitea
spec:
  encryptedData:
    password: AgBOJPTnSGBhU3Jkl4RZJj73z6cgCH1BfejDP+Wbm2STg1S5te2HujgKWAa8wUrd75fZJ5Kr0mlZZzpS+63tJYcxnUIMZUvNQRgRY7jYOxP6G/Hob0AcOkmOrPf5xIdpXIwxllTCZ7VFE1sEfjiedr9FkZfFtObDU3MkSHXAyttmf2ldKEUdNljGW96E+fCeeasSG14Qq1GbTb80+ndgXHxGZZdPpJC/lVUyKzusdNclm+gwSPAjtYyeFS2sA2UtWO+CRzt8j7R4OjJuEOiQj5WKDFf/S3bju8wW7fXOMT5Fus0ip4QlAJTYoD3SGgjozLnl2Q7t4oLltFvU421ewCuT/8uuI+fjsvEUXZzcsNb2FaDQqVluxvBJOSgVfPRQmjRM1P+nsozgb8/HV5/3aJOkNvfXlX0yp2GvErn/PwYGg5U8xW6bEkEQ5BR18QFZtli6BXKztMpcLmsgIC144AGq94IIg/aVCxAgPOsWCr+UeyioqTrCfilMMa5SIO3YtMujBw9NsT4+tiZl1yHYpb8xH4U+Yz8z7huyei08fkjrVc0idbVami9M0kQCdJKcvHpl06up/JeO//cpTf+ajmDikzEmR/oXrG3TZE1uBZsnNGIZQdbx0Etqmb9VKCKZ/b9r0oKeI+Bd1vGxZEwKVEFUUtFCLY4u70ekgNufoDxg2yCxHoydNDRpxl8Ro2gEOhvICo9VnKePTidXnUvOsszdyEQWuZEdsJmmLEqOKLEE1w==
    username: AgCubr5V2v3dNdA1y3e4dpXKld+twEm66sFn2sIsYszejU74z64LwKv92RyBu0bMXuxlzlczva5ZkmqJ09BFqRlJ8t7vebcgFLOXmgS4wvEAiLU/WX94VNFSk9tk/95WXlwF0+MZBJc5fRiwe2RIEf3jYILjwYfYLzetxjAO18wEoHsQkFnm+fZ9cKjqp4hY7E3MmBfbP9QZMSZQb9O7RX3Nl+D9FF866jCq/LZqmqPwl9VOTMkqv2vN9HWOfhDBQcmW+pK7sZJPK9Ms0TYwITbzjXj50LZx+x4X/mo2efUC/F+BRJlqoxrxdAPE/ZeOLfT7FNDZo3FIyAKYR8L62CtOsShPflbssZ5hsChCy6sHnjjkVWuft4Z473zwo5pXPuOXIMdZ3/3eyTHq2k3K8B97sHcry/jdOC5eUomFgg2KFFLxQw8cKmHrsrs1UgsFiaWqbYkwZsJgWYidfAGn3TyLOR7bnVebRJUwxDAKKQKSKRE0EbnCE4AB8Ww28r9mvgjXkgimX913nF4/oq71C+3K9q7akbtqOay3YY1/lr+ksHpsui43YCSxa/qL/jYsla3n1yLzuIJA2IYGOUvM8fzBf+zK1/8jvM1WtkLHR6WxTCYJ/PlzLdzoOh7eFxYTlRZ4iy+ulaWXPBim1pW2/AwCJPN9pPhZay/ayHn8JT8eeOa3004j/qBHSkpSLV9OfeJ4IwjzVA==
  template:
    metadata:
      name: pg-credentials
      namespace: gitea
    type: Opaque
