apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-5fa9360e-9b78-4624-ab4a-71ad5e84b18f
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: unsafe-rbd
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitea-shared-storage
    namespace: gitea
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000003-a84cf1fb-d3bf-46c7-bf69-30aeac44f32f
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      pool: unsafe-metadata
      dataPool: unsafe-data
      journalPool: unsafe-metadata
      imageName: csi-vol-a84cf1fb-d3bf-46c7-bf69-30aeac44f32f
      imageFeatures: layering
      imageFormat: "2"
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-76a0c0dd-7609-4e43-a01f-b4d153e3ef15
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ssd-rbd
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-1
    namespace: gitea
  csi:
    driver: rook-ceph.rbd.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000014-858735c7-c17b-40fe-bfa1-ea75feafd08d
    fsType: ext4
    volumeAttributes:
      clusterID: rook-ceph
      pool: default-ssd
      journalPool: default-ssd
      imageName: csi-vol-858735c7-c17b-40fe-bfa1-ea75feafd08d
      imageFeatures: layering
      imageFormat: "2"
    nodeStageSecretRef:
      name: rook-csi-rbd-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-rbd-provisioner
      namespace: rook-ceph
