// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kubernetes.Types.Inputs.Gateway.V1Beta1
{

    /// <summary>
    /// Path specifies a HTTP request path matcher. If this field is not specified, a default prefix match on the "/" path is provided.
    /// </summary>
    public class HTTPRouteSpecRulesMatchesPathArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type specifies how to match against the path Value. 
        ///  Support: Core (Exact, PathPrefix) 
        ///  Support: Implementation-specific (RegularExpression)
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Value of the HTTP path to match against.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public HTTPRouteSpecRulesMatchesPathArgs()
        {
            Type = "PathPrefix";
            Value = "/";
        }
        public static new HTTPRouteSpecRulesMatchesPathArgs Empty => new HTTPRouteSpecRulesMatchesPathArgs();
    }
}
