apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default
  namespace: archive
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default-cephfs
  resources:
    requests:
      storage: 1Ti
