apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default
  namespace: archive
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: default-cephfs
  volumeName: pvc-7000b58c-0d8d-4bf6-8300-e885fcd8f102
  resources:
    requests:
      storage: 1Ti
