apiVersion: v1
kind: Pod
metadata:
  name: mounty
  namespace: archive
spec:
  containers:
    - name: shell
      image: ubuntu
      command: ["bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeMounts:
        - name: default
          mountPath: /mnt
  volumes:
    - name: default
      persistentVolumeClaim:
        claimName: default
