apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-7000b58c-0d8d-4bf6-8300-e885fcd8f102
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default-cephfs
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: default
    namespace: archive
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000003-42d14972-b082-416c-9f85-c67ce2e8d369
    volumeAttributes:
      clusterID: rook-ceph
      fsName: replicated
      pool: replicated-data
      subvolumeName: csi-vol-42d14972-b082-416c-9f85-c67ce2e8d369
      subvolumeGroup: csi
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
