name: Setup Kubeconfig
description: Create a kubeconfig for deploying
runs:
  using: composite
  steps:
    - name: Write configuration files
      working-directory: clusters/rosequartz
      shell: bash
      run: |
        terraform output -raw talosconfig > "$RQ_TALOSCONFIG"
        terraform output -raw kubeconfig > "$RQ_KUBECONFIG"
